### ISSUE TITLE
Documentation needed for how to upload two simultaneous streams for h3_client.rs

### ISSUE THREAD

**Issue by catshow** [quinn-rs/quinn#1011]
Hi I am looking for some documentation on how to upload multiple files simultaneously via the http 3 client to the http 3 server in the examples directory.  Any quick help would be greatly appreciated.

**Comment by djc** [comment]
What have you tried? This is an all-volunteer open source project; we don't necessarily have resources to write your code for you. Also, the quinn-h3 project is in a bit of a limbo state right now, with most energy going to https://github.com/hyperium/h3/.

**Comment by catshow** [comment]
I tried to clone the conn object and send it to an async method.  However, that was not clonable. I refactored my code to pre-generate all of the request objects and used the conn object and it works now.  I will look into using hyperium/h3.

```rust
    let mut send_handles: Vec<_> = Vec::new();
    let mut recv_handles: Vec<_> = Vec::new();

    let requests = operations.iter().map(|op| make_request(uri.clone(), op));
    for req in requests.into_iter() {
        let (send_request_handle, recv_response) = conn.send_request(req.unwrap());
        send_handles.push(send_request_handle);

        let recv_future = tokio::spawn(async move {
            process_response(recv_response).await;
        });

        recv_handles.push(recv_future);
    }

    let send_results = futures::future::join_all(send_handles).await;
    let recv_results = futures::future::join_all(recv_handles).await;
```

**Comment by djc** [comment]
I'll close this for now, then. Feel free to reopen if you need more help.
