### ISSUE TITLE
Re-export tokio

### ISSUE THREAD

**Issue by nashley** [quinn-rs/quinn#1016]
Currently, users have to depend on `tokio` as well as this crate in order to use this crate. Re-exporting `tokio` would allow users to just depend on this crate.

**Comment by djc** [comment]
I guess I'm open to doing so. Could you submit a PR?

**Comment by Matthias247** [comment]
I am not sure how this helps a lot. One needs pull in tokio manually anyway, to get an executor. And while doing so one needs to think about the correct/compatible version.

**Comment by kim** [comment]
I’m not sure I like this: if the `quinn` consumer is itself a library, further upstream is also constrained to the reexported `tokio` version. If they themselves depend on `tokio`, this means they need to carefully match the transitive dependency — or worse, apply an unpleasant `cargo` patch in case they have a reason to pin to a newer or older version than `quinn`.

It might be that it is preferable in any case to run the `quinn` stack in its own dedicated `Runtime`, but then I’m wondering if this shouldn’t be reflected in the surface API. Either way, it would be considered a breaking change for us.

**Comment by Ralith** [comment]
Why couldn't the executor be taken from the reexport? I'm generally in favor of reexports specifically because they save you from having to check version compatibility, though I'm uncertain how realistic it is for downstream code to not have other tokio-using libs as well, which makes the reexport less useful.

**Comment by Ralith** [comment]
> If they themselves depend on tokio, this means they need to carefully match the transitive dependency — or worse, apply an unpleasant cargo patch in case they have a reason to pin to a newer or older version than quinn.

I don't think this would have any impact to version conformance; cargo will dedup dependencies regardless of what's exported, and quinn already depends on tokio.

**Comment by kim** [comment]
> cargo will dedup dependencies regardless of what's exported

That’s news to me, unless the idea here is that nothing in the quinn surface would expect or return a tokio type. In which case I doubt the usefulness for the same reasons as you do, but wouldn’t care either.

**Comment by Matthias247** [comment]
> Why couldn't the executor be taken from the reexport? I'm generally in favor of reexports specifically because they save you from having to check version compatibility, though I'm uncertain how realistic it is for downstream code to not have other tokio-using libs as well, which makes the reexport less useful.

It could be. But probably only for the subset of applications which use Quinn only and nothing else with tokio (eg hyper). That might be small. Anyway, I’m not opposed to doing it.

**Comment by Ralith** [comment]
> That’s news to me

Tokio-based libs wouldn't work otherwise; use of `tokio::spawn` and tokio-driven I/O primitives constitutes a public dep.

**Comment by jean-airoldie** [comment]
> > Why couldn't the executor be taken from the reexport? I'm generally in favor of reexports specifically because they save you from having to check version compatibility, though I'm uncertain how realistic it is for downstream code to not have other tokio-using libs as well, which makes the reexport less useful.
> 
> It could be. But probably only for the subset of applications which use Quinn only and nothing else with tokio (eg hyper). That might be small. Anyway, I’m not opposed to doing it.

There is always the use case of needing the tokio dependency just to spawn a minimal runtime so that it doesn't panic when using quinn with another executor (unless they changed that since 0.2).

**Comment by nashley** [comment]
Closing due to lack of conviction. I can reopen if someone else has a convincing use-case.
