### ISSUE TITLE
does client support migration? how to use it in code

### ISSUE THREAD

**Issue by xcy19920603** [quinn-rs/quinn#1055]

**Comment by djc** [comment]
The client does support migrating, but there's currently no way to trigger migration from the client. Is that what you need?

**Comment by Ralith** [comment]
Migration is mostly a server-side feature; clients benefit without doing anything special.

**Comment by Rouzip** [comment]
I have the same question. How does quinn detect whether the first link is congested and migrate to the second path? Do we need to use quinn-proto to implement link state detection by ourselves?

**Comment by Ralith** [comment]
Migration has nothing to do with congestion. It refers to the capacity for a server to continue communicating with a client that has changed addresses.

**Comment by Rouzip** [comment]
> Migration has nothing to do with congestion. It refers to the capacity for a server to continue communicating with a client that has changed addresses.

Thanks for your answer! I learned that the QUIC algorithm can switch the underlying transmission link, but I didn't think of how to detect the timing of the switch, so I was wondering if I need to use quinn-proto for development instead of using the recommended quinn.

**Comment by Rouzip** [comment]
> Migration has nothing to do with congestion. It refers to the capacity for a server to continue communicating with a client that has changed addresses.

Thanks for you answer!

**Comment by xcy19920603** [comment]
there is a function in Quinn-proto/src/tests/mod.rs, line952, named migration. does it show me how to use migration?

**Comment by Rouzip** [comment]
> there is a function in Quinn-proto/src/tests/mod.rs, line952, named migration. does it show me how to use migration?

You can find the usage in the [examples](https://github.com/quinn-rs/quinn/blob/f2bbc0e3fc33365b4b959becf732f2d4dbfba742/quinn/examples/client.rs#L124).

**Comment by Ralith** [comment]
Closing as not actionable.
