### ISSUE TITLE
could it Adapt to android?

### ISSUE THREAD

**Issue by xcy19920603** [quinn-rs/quinn#1060]

**Comment by djc** [comment]
Like your previous issue, this one is pretty underspecified. Please be more specific about any use cases you have in mind, if you've tried anything and if so, what you've found, or any indications you've seen that make you think it doesn't work.

I don't think I've explicitly heard from anyone using this on Android, but I also don't know of any particular reason it shouldn't. You should probably just do some experiments to see if it works. If you're interested, you can pay me to do experiments for you.

**Comment by FireMasterK** [comment]
What would need to be done is to use something like [jni-rs](https://github.com/jni-rs/jni-rs) and then build a library with NDK. You'd have to use [cargo-ndk](https://docs.rs/crate/cargo-ndk/) for this I believe.

I have a similar use case - a JVM application.

What I would really like/want is some sort of higher-level API - where I don't have to open connections manually, create the raw request manually, read/write manually.

However, I fully understand if this is out of scope for quinn.

**Comment by djc** [comment]
@FireMasterK are you talking about HTTP/3 or about QUIC? QUIC itself doesn't really have requests per se. For HTTP/3, we have the quinn-h3 crate within this project, although work on that is mostly on halt and development has shifted to https://github.com/hyperium/h3 (which has a Quinn adapter in h3-quinn).

Depending on what you need, maybe the commercial support I offer could be helpful.

**Comment by FireMasterK** [comment]
I see, the h3 crate is exactly what I'm looking for, thanks!

> Depending on what you need, maybe the commercial support I offer could be helpful.

This wouldn't be useful for me unfortunately since I'm just a hs student :P

**Comment by djc** [comment]
Fair enough. Have you also looked into using an actual Java stack for QUIC/HTTP 3? https://bitbucket.org/pjtr/flupke/src/master/ might be easier to get started with (unless you explicitly want to use Rust for some reason).

**Comment by FireMasterK** [comment]
I have indeed, there was no TLS certificate verification the last time I checked in flupke, and the http/3 component hasn't been updated in close to a year.

cronet supports android but not the JVM, so that's not an option.

[quiche4j](https://github.com/kachayev/quiche4j) might be a good option for me considering it should technically work, but updating it requires a lot of refactoring because a lot has changed.

I'm trying to use Rust because I don't know C :)

**Comment by djc** [comment]
Perhaps someone on the h3 side is willing to mentor you through building JVM bindings for h3.

**Comment by FireMasterK** [comment]
Will try that, thanks!

**Comment by Ralith** [comment]
Closing since I don't think there's any action for us to take here, but feel free to open an new issue if you hit specific issues running Quinn on android!
