### ISSUE TITLE
Interop with draft-29

### ISSUE THREAD

**Issue by FireMasterK** [quinn-rs/quinn#1068]
Error on WSL:
```
quinn$ cargo run --example client https://youtube.com:443/
   Compiling quinn v0.7.0 (/mnt/c/tmp/quinn/quinn)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 56s
     Running `target/debug/examples/client 'https://youtube.com:443/'`
connecting to youtube.com at 74.125.200.136:443
ERROR: failed to connect: aborted by peer: the cryptographic handshake failed: error 120: 28:TLS handshake failure (ENCRYPTION_INITIAL) 120: no application protocol
```
No WSL
```
quinn>cargo run --example client https://youtube.com:443/
   Compiling quinn v0.7.0 (C:\tmp\quinn\quinn)
    Finished dev [unoptimized + debuginfo] target(s) in 16.30s
     Running `target\debug\examples\client.exe https://youtube.com:443/`
connecting to youtube.com at 74.125.200.93:443
Mar 15 23:10:18.568 ERROR quinn::builders: I/O error: The requested address is not valid in its context. (os error 10049)
ERROR: failed to connect: closed
error: process didn't exit successfully: `target\debug\examples\client.exe https://youtube.com:443/` (exit code: 1)
```

I just changed https://github.com/quinn-rs/quinn/blob/819eba6caa08ac31e4c5696bad58e5179e54c27d/quinn/examples/client.rs#L65 to port 443 (without which, it kept trying 4433).

Am I missing something, because the last release states there's support for draft 29 and 32?

I'm running on the latest main branch, hope that's not an issue.

**Comment by djc** [comment]
The error on WSL makes sense to me, the example code probably doesn't set an ALPN protocol whereas YouTube only accepts HTTP/3 connections. The error outside WSL probably happens because the example client tries to bind to an IPv6 socket, and I guess your machine doesn't have IPv6 set up?

**Comment by Ralith** [comment]
> I guess your machine doesn't have IPv6 set up?

I think the issue here is that Windows sockets aren't dual-stack by default (see e.g. #1058).

**Comment by FireMasterK** [comment]
I do have ipv6:
```
quinn>curl -6 icanhazip.com
2a0a:b640:...
```

> (I'm guessing) YouTube only accepts HTTP/3 connections

The Alt-Svc header only contains h3-29, could this be why?

**Comment by FireMasterK** [comment]
I happen to have a similar error when running the examples in [h3](https://github.com/hyperium/h3):
```
h3$ cargo run --example client https://www.youtube.com/
    Finished dev [unoptimized + debuginfo] target(s) in 3.56s
     Running `target/debug/examples/client 'https://www.youtube.com/'`
DNS Lookup for https://www.youtube.com/: 74.125.24.190:443
Error: ConnectionClosed(ConnectionClose { error_code: Code::crypto(78), frame_type: Some(CRYPTO), reason: b"28:TLS handshake failure (ENCRYPTION_INITIAL) 120: no application protocol" })
```

h3 uses HTTP/3 and not the application-specific quic protocol, right?

**Comment by djc** [comment]
> The Alt-Svc header only contains h3-29, could this be why?

Yeah, that would explain it.

For the h3 issue, you should probably file an issue on their side. I'm going to close this since I don't think there's anything actionable here.

**Comment by FireMasterK** [comment]
Should I create a new issue for the following error?
```
NS Lookup for https://www.youtube.com/: 216.58.214.14:443
Mar 26 10:23:24.620 ERROR quinn::builders: I/O error: The requested address is not valid in its context. (os error 10049)
Error: LocallyClosed
error: process didn't exit successfully: `target\debug\examples\client.exe https://www.youtube.com/` (exit code: 1)
```

I get this in both `quinn` and `h3` (only affects windows)

**Comment by Ralith** [comment]
That's not an interop error, or indeed a QUIC error a tall; the OS is complaining that you're trying to connect to an IPv4 address with an IPv6 single-stack socket.

**Comment by FireMasterK** [comment]
Indeed, I am aware of that, I just brought it up here because we discussed this in an earlier comment on this issue, but in my case, I have both an ipv4 and ipv6 address.

**Comment by Ralith** [comment]
You have one socket, which is bound to one address. If you want to portably operate on two address families, you need to explicitly place it in dual-stack mode or use multiple sockets. This is true for any transport protocol. See the perf code at https://github.com/quinn-rs/quinn/blob/main/perf/src/lib.rs#L16 for an example of enabling dual-stack mode.

**Comment by FireMasterK** [comment]
I am a bit confused about what I can do to fix/solve this, I'm supposed to somehow enable `IPV6_V6ONLY` right?

Would there be any way to enable dual-stack mode in this example https://github.com/hyperium/h3/blob/master/examples/client.rs?

From what I can understand, the error is because of these lines which bind to ipv6 only:

https://github.com/hyperium/h3/blob/36cf6266f09b00ef9dd67f0f9126bb38f028cf62/examples/client.rs#L42-L44

https://github.com/quinn-rs/quinn/blob/e801527c9bec4a6e2d50835599c961754866e3b0/quinn/examples/client.rs#L96

The other idea I had was to listen to ipv4 or ipv6 depending on what IP the DNS query returns, I am unsure whether this would be a good solution...

**Comment by Ralith** [comment]
> I'm supposed to somehow enable IPV6_V6ONLY right?

Yes, that is what the example I linked above illustrates.

> Would there be any way to enable dual-stack mode in this example https://github.com/hyperium/h3/blob/master/examples/client.rs?

Yes, pass in a socket configured in dual-stack mode as demonstrated above using `EndpointBuilder::with_socket`, as illustrated at https://github.com/quinn-rs/quinn/blob/main/perf/src/bin/perf_client.rs#L90. This replaces the `bind` call, which is a convenience method for constructing a socket that uses your environment's defaults.

> The other idea I had was to listen to ipv4 or ipv6 depending on what IP the DNS query returns, I am unsure whether this would be a good solution...

That works fine too, but dual-stack mode is a bit more elegant/convenient.
