### ISSUE TITLE
Suboptimal use of initial credits during address validation phase

### ISSUE THREAD

**Issue by Matthias247** [quinn-rs/quinn#1082]
Extracting this from https://github.com/quinn-rs/quinn/issues/1075 since it can stand alone:

When the client makes a handshake with an `INITIAL` packet padded to 1200 bytes, the server is allowed to respond up to 3 * 1200 = 3600 bytes without an acknowledgement.

However with GSO enabled, the server currently sends only 2452 bytes, which is about 2/3 of the limit:

```
Mar 19 18:11:27.319 TRACE drive{id=0}:send{space=Initial pn=0}: quinn_proto::connection: ACK
Mar 19 18:11:27.319 TRACE drive{id=0}:send{space=Initial pn=0}: quinn_proto::connection: CRYPTO: off 0 len 90
Mar 19 18:11:27.319 TRACE drive{id=0}:send{space=Handshake pn=0}: quinn_proto::connection: CRYPTO: off 0 len 1007
Mar 19 18:11:27.319 TRACE drive{id=0}:send{space=Handshake pn=0}: quinn_proto::connection::packet_builder: PADDING * 13
Mar 19 18:11:27.319 TRACE drive{id=0}:send{space=Handshake pn=1}: quinn_proto::connection: CRYPTO: off 1007 len 1161
Mar 19 18:11:27.319 TRACE drive{id=0}:send{space=Handshake pn=1}: quinn_proto::connection: blocked by anti-amplification
Mar 19 18:11:27.319 TRACE drive{id=0}: quinn_proto::connection: sending 2452 bytes in 2 datagrams
```

From those 13 are padding bytes, due to the CRYPTO frames not fully filling up the potential frame payload (need a similar fix as #998 for `CRYPTO` frames). 

Those wasted 13 bytes are improvable, but the even bigger drawback is that currently `3600-2452 == 1148 byte` or about 33% of the initial connection budget are not used, which makes it less likely to finish handshake in 1 RTT.

This could be improved by either allowing a small non full datagram which still fits into the anti-amplification limit, by reducing the path MTU size during the handshake (allow for 3x 1200 bytes - but that makes things less efficient if the client sends a bigger MTU like Chrome does with 1350 bytes), or by rounding up.

**Comment by Ralith** [comment]
I think rounding up would be inconsistent with the spec's requirements for anti-amplification. I think supporting a non-full trailing packet is the most promising route; at least Chrome clearly expects this behavior, since otherwise its enlarged Initial isn't useful, and we'll probably eventually want to let users configure the default MTU, in which case large initial MTUs could further reduce or even entirely forbid the server's first flight, which is rather backwards.

I am a bit concerned that reduced size limit packets could be tricky to implement correctly and/or conflict with some assumptions we've encoded, but I think we've been pretty good about expressing limits in terms of bytes rather than packets so it might not be too bad.

**Comment by Matthias247** [comment]
Right. and a lot of code path take `path.mtu` as an argument. Those would need to be changed to use a different variable which starts with `path.mtu` but can get smaller during address validation.

This should also avoid sending super tiny packets. If less than 200 bytes are sendable it's likely not worth trying to attempt sending. But I'm actually not sure whether rounding up isn't mostly equivalent. A lot of infrastructure cares about the number of packets and not bytes. A small packet will cause the same impact as a full MTU packet for those.

**Comment by Ralith** [comment]
It's definitely an appealing simplicity. I'd like to hear other implementers' thoughts on it, at least.

**Comment by Ralith** [comment]
There was some mention in slack of initializing the server's MTU to the size of the client's initial. How about that for a pragmatic workaround? That should give better-than-ever performance against Chrome, at least.

**Comment by Matthias247** [comment]
It's an idea. But I'm somewhat concerned about asymmetric MTUs (e.g. due to some IP encapsulation) and then failing to send responses due to that.

**Comment by Matthias247** [comment]
I did a bit of research on what other implementations do. So far everyone seems to settle on exact byte counting and capping the last datagram based on that. I'm suprised nobody is rounding up to full MTU - maybe just because they didn't think about it? I still can't see a strong reason from a DOS protection point of view for not doing it.

### Quiche

Increments allowed bytes when retrieving new incoming packets: https://github.com/cloudflare/quiche/blob/4fbbc0d882717b366082373638edb0a97d557f7f/src/lib.rs#L1569-L1571

Restricts packet size to that amount: https://github.com/cloudflare/quiche/blob/4fbbc0d882717b366082373638edb0a97d557f7f/src/lib.rs#L2255-L2263

### MsQuic

Increments allowed bytes when retrieving new incoming packets: https://github.com/microsoft/msquic/blob/ffab42f06abb6b7f6103fced16e9c3a7e28ce3c4/src/core/connection.c#L5117-L5122

Restricts packet size to that amount: https://github.com/microsoft/msquic/blob/bf46c38af454701b52e141c990c3bc6632782035/src/core/packet_builder.c#L76-L83

### Quicly

Does something similar

Calculating the allowance: https://github.com/h2o/quicly/blob/839a9347d85cdc5f2e42d2650a70caa332cb3874/lib/quicly.c#L2792-L2800

Clamping outgoing packet size with it: https://github.com/h2o/quicly/blob/839a9347d85cdc5f2e42d2650a70caa332cb3874/lib/quicly.c#L2821-L2823

**Comment by Ralith** [comment]
That may come down to the spec being quite strict here:

> an endpoint MUST limit the amount of data it sends to the unvalidated address to three times the amount of data received from that address

**Comment by Matthias247** [comment]
Actually my I understanding of msquic might have been wrong. 

While it calculates an exact `SendAllowance`, it seems it later on checks just a `SendAllowance > 0`:

https://github.com/microsoft/msquic/blob/e7f63f5470658a7c7106f18cdf12ab6fa30fff50/src/core/packet_builder.h#L218-L228

https://github.com/microsoft/msquic/blob/fa4e0d4375dc4573ce718f829ac1713622bdcda8/src/core/send.c#L1021-L1050

This would indicate to me it would be rounding up to MTU size

**Comment by Matthias247** [comment]
Google Quic (quiche) also seems to round up

The limit is increased when a UDP packet is received: https://quiche.googlesource.com/quiche/+/2121bae1e84a3254d50210c2012a839f514d9dcb/quic/core/quic_connection.cc#2856

`QuicConnection::LimitedByAmplificationFactor()`  returns `false` only if the full limit had been used: 
https://quiche.googlesource.com/quiche/+/2121bae1e84a3254d50210c2012a839f514d9dcb/quic/core/quic_connection.cc#6192

That check is used to prevent creation of new packets: https://quiche.googlesource.com/quiche/+/2121bae1e84a3254d50210c2012a839f514d9dcb/quic/core/quic_connection.cc#3361

However once it was decided that another packet fits, the exact size doesn't matter anymore.

**Comment by Ralith** [comment]
Wait, do Google's and Cloudflare's impls have the same name? I'm confused.

In any case, this seems like adequate evidence that we can get away with rounding up. This should probably be formally raised with the WG as well, since clearly the spec doesn't reflect reality here.

**Comment by djc** [comment]
(Yes, they have the same name.)
