### ISSUE TITLE
Drop quinn-h3

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#1085]
HTTP 3 implementation effort is now concentrated at https://github.com/hyperium/h3. Maintaining quinn-h3 incurs maintenance overhead (see e.g. #1083), so we should identify any remaining dependencies on it and strip it out as soon as those are addressed.

**Comment by djc** [comment]
The main dependencies: how do we do interop testing (particularly with implementations that don't support hq)? And the other thing is test coverage. I found that some bits of quinn are exercised by the quinn-h3 tests that are not exercised by other tests at all (I think the tokio `AsyncRead` impl is one example).

**Comment by Ralith** [comment]
This has been done.
