### ISSUE TITLE
Reading tasks bloking when another stream is sending

### ISSUE THREAD

**Issue by vvicente-adyta** [quinn-rs/quinn#1110]
Using two unidirectional streams (one to send and one to receive), in both the client and the server, the receiving tasks stops returning `Ready` on  `receiving_stream.read().await` until the peer sending the stream closes it with `send.finish()`.

The idea is to have this two ends exchanging data as it becomes available in unidirectional streams (one in each direction).

```rust
    let send = conn.open_uni().await.unwrap();
    let sender = tokio::spawn(send_data(send));
    let receiver = tokio::spawn(receive_data(uni_streams));
    let _r = tokio::join!(sender, receiver);
   ```
   
The `receive_data` is very similar as the example in book and the `send_data` sends data in a loop while available. 
Regarding the blocking on the receiving end while another stream is transmitting:
Is this behavior the expected one (I cannot find an explicit answer in the drafts)?
If not, how can I treat this two tasks not to block one another (joining the two tokio::spawn does not solve)?

**Comment by Ralith** [comment]
> the receiving tasks stops returning Ready on receiving_stream.read().await until the peer sending the stream closes it with send.finish().

This is the intended behavior. If there's no data on an open stream, there's nothing for `read` to yield. The state of other independent streams doesn't matter.

> Regarding the blocking on the receiving end while another stream is transmitting

Sending and receiving on independent streams should not interfere with eachother. If they appear to be doing so, please post a self-contained repro.

**Comment by vvicente-adyta** [comment]
> Sending and receiving on independent streams should not interfere with eachother. If they appear to be doing so, please post a self-contained repro.
This is what I believe to be the case actually. i created a minimal example repo: https://github.com/vvicente-adyta/quinn-block-minimal.

**Comment by Ralith** [comment]
Your problem is that you're calling `std::thread::sleep` in your receive task. This blocks the entire thread, including other async tasks. If you replace that with `tokio::time::sleep(x).await`, your code works as intended.

**Comment by vvicente-adyta** [comment]
> Your problem is that you're calling std::thread::sleep in your receive task. This blocks the entire thread, including other async tasks. If you replace that with tokio::time::sleep(x).await, your code works as intended.  

Thank you. It did solve the problem... so I'll close the issue.
