### ISSUE TITLE
`RecvStream::read_unordered` doesn't exist

### ISSUE THREAD

**Issue by TheRawMeatball** [quinn-rs/quinn#1118]
I was reading the documentation here: https://docs.rs/quinn/0.7.2/quinn/generic/struct.RecvStream.html and despite searching the docs and the codebase locally, I couldn't find this function. Has it been removed and the docs are missing, or is the link just broken?

**Comment by djc** [comment]
I think it was removed in favor of read_chunk() with an ordered false argument, but we forgot to update this documentation.

**Comment by TheRawMeatball** [comment]
Ah, makes sense

**Comment by djc** [comment]
@TheRawMeatball would you mind submitting a PR to fix the docs?
