### ISSUE TITLE
export keys for packet analysis

### ISSUE THREAD

**Issue by dvc94ch** [quinn-rs/quinn#1121]
Since this is rusttls/noise agnostic it might make sense to put it in quinn-proto. When an environment variable is set the keys used for packet encryption should be written to a file. This allows packet analyzers to decrypt the traffic without leaking the private keys.

**Comment by djc** [comment]
Quinn already has support for enabling this in rustls:

https://github.com/quinn-rs/quinn/blob/main/quinn/src/builders.rs#L184

I think the Noise implementation (or, potentially the quinn-noise bridge) should take care of how to write out these keys.

**Comment by dvc94ch** [comment]
quinn-noise uses it's own customized noise implementation. have a wip quinn-noise implementation and a wip rust packet dissector that makes use of it.
