### ISSUE TITLE
connect  quic go server wrong 

### ISSUE THREAD

**Issue by bipo123** [quinn-rs/quinn#1134]
I have a quic server  with quic-go.
server and client work in go.
then I  run client with quinn is wrong ,report this error  failed to connect: aborted by peer: the cryptographic handshake failed: error 120 , I have  load  client cert  pem format.

**Comment by Ralith** [comment]
TLS alert 120 is no_application_protocol; see https://datatracker.ietf.org/doc/html/rfc8446#appendix-B.2. You need to configure a protocol identifier supported by the server.

**Comment by Ralith** [comment]
Presuming resolved for lack of response.

**Comment by vvhh2002** [comment]
I have same issue.
`./target/debug/examples/client https://www.cloudflare.com
connecting to www.cloudflare.com at [2606:4700::6810:7b60]:443
ERROR: failed to connect: aborted by peer: the cryptographic handshake failed: error 120
`

**Comment by djc** [comment]
@vvhh2002 did you configure an application protocol, as suggested by Ralith's earlier comment?

**Comment by vvhh2002** [comment]
Thank you very much, after I configured `alpn_protocols`, it worked
