### ISSUE TITLE
Support QUICv1

### ISSUE THREAD

**Issue by heinrich5991** [quinn-rs/quinn#1138]
[RFC 9000](https://datatracker.ietf.org/doc/html/rfc9000) is out. It specifies QUIC version 1.

I couldn't find an issue for support of this version, and from reading the source code, it looked like it wasn't yet supported:
https://github.com/quinn-rs/quinn/blob/7f1aa1ead3dc02f32e0f2be9afbe9b6ac65bfbcb/quinn-proto/src/lib.rs#L151-L153

**Comment by Ralith** [comment]
That's correct, this is TODO. Biggest blocker is a release from rustls containing https://github.com/ctz/rustls/pull/544.

**Comment by lberrymage** [comment]
> That's correct, this is TODO. Biggest blocker is a release from rustls containing [ctz/rustls#544](https://github.com/ctz/rustls/pull/544).

That release in turn [is waiting](https://github.com/ctz/rustls/projects/2#column-13985913) on [rustls#447](https://github.com/ctz/rustls/issues/447) for anyone curious.

**Comment by djc** [comment]
FWIW, I don't think the rustls release will block on removing all panics.

**Comment by protheory8** [comment]
Still blocked on Rustls 0.20?

**Comment by djc** [comment]
Rustls 0.20 has been released, we're now waiting on the rustls-native-certs release (hopefully coming soon).

**Comment by Ralith** [comment]
QUIC 1 should be supported in HEAD as of #1050, though we haven't yet performed introp testing.

**Comment by Dessix** [comment]
I see multi-version support [mentioned (back in March)](/quinn-rs/quinn/pull/1050#issuecomment-808436589) in the comments for 1050, but it's not clear whether or not the current `HEAD` supports back to `hq-29` yet. If it isn't yet implemented, is multi-version support being tracked somewhere?

**Comment by Ralith** [comment]
"hq-29" is an application-layer protocol, which is orthogonal to the QUIC transport version. You can use as many application-layer protocol versions as you like.

 We dropped plans for support for multiple QUIC transport versions since everyone else is already on 1.0 at this point anyway. Do you have a requirement for it?

**Comment by Ralith** [comment]
Support released in 0.8.
