### ISSUE TITLE
Support Client Cert verification for ServerConfig

### ISSUE THREAD

**Issue by kamel1239** [quinn-rs/quinn#1153]
Hi, 

Is it possible to support client certificate verification the same way like in [RustTls](https://docs.rs/rustls/0.17.0/rustls/trait.ClientCertVerifier.html) ? 

If yes, I couldn't find a way to do it...as the only input in `ServerConfig::new ` is the `HandshakeTokenKey` unlike in RustTls where you can add a callback to verify the client certificate.

if no, is it possible to add this feature please ? 

Thank you.

**Comment by djc** [comment]
The `crypto` field of Quinn's `ServerConfig` is public, so you can assign your own `rustls::ServerConfig` to it:

https://docs.rs/quinn/0.7.2/quinn/generic/struct.ServerConfig.html#structfield.crypto
