### ISSUE TITLE
How to process messages one at a time

### ISSUE THREAD

**Issue by sotrh** [quinn-rs/quinn#1161]
I'm messing around with making a simple game server (Tic Tac Toe, nothing too complicated), and I've come across an issue with processing messages. Currently when the client sends "ping" the server should send "pong" and the same sort of thing should happen with "marco" and "polo". Due to timing issues the server is getting this messages at the same time leading the buffer on the server to have "pingpolo". Is there a way to receive these messages separately, or do I just need to have some way of parsing them when they come in?

I'm using `bi_streams` with `RecvStream::read()` and `SendStream::write_all()`.

Full Code: https://github.com/sotrh/quinn-networking

**Comment by Ralith** [comment]
QUIC streams are contiguous, undelimited byte streams, so this is the intended behavior. Various strategies are available to address your use case, depending on detalis. You could delimit messages within a stream using something like [`tokio_util::codec::length_delimited`](https://docs.rs/tokio-util/0.6.7/tokio_util/codec/length_delimited/index.html). Alternatively, you could open a new stream for each message. Opening streams is basically free, and this also gives the receiver the option of not necessarily waiting for each message to be delivered before it can begin processing the next.

**Comment by sotrh** [comment]
Is there a good example of opening new streams for each message?

**Comment by Ralith** [comment]
I don't have one off hand. Is there something specific that's unclear? You can call `connection.open_bi().await` as many times as you like, subject to peer flow control limits.

**Comment by sotrh** [comment]
Ok, I'll try that.
