### ISSUE TITLE
Issues with multiple connections.

### ISSUE THREAD

**Issue by lionel1704** [quinn-rs/quinn#1166]
I've been seeing some issues with multiple connections & messages being exchanged at an endpoint. I put together a small example to try and reproduce it. Some of the issues I'm seeing are:
`Timeout`, `Reset`, `INVALID_TOKEN` 

These issues happen when trying to establish a connection (at the receiving end) and while trying to read the incoming message.

[Here is the example](https://github.com/lionel1704/qp2p/blob/56675284908cb46e59662829c8a1dd5d800b7591/src/tests/quinn.rs#L197)

The test is a little memory heavy, so heads up!

**Comment by djc** [comment]
"seeing some issues" is pretty broad, and that's quite a bit of code. Can you give a specific example of a scenario with what you expect to happen and what happens instead? Also, have you tried to turn on TRACE-level logging to see what happens? Also, what version are you using, and have you tried latest main?

**Comment by lionel1704** [comment]
Apologies for the limited information. The issue isn't consistently reproducible but I guess if I were to narrow it down it'd be here:
```
let (ep, incoming) = EndpointBuilder::default().bind(address)?;
let _ = tokio::spawn(async move {
     loop {
          match incoming.next().await {
               Some(quinn_conn) => match quinn_conn.await {
                    Ok(quinn::NewConnection {
                         connection,
                         uni_streams,
                         ..
                    }) => {
                         let peer_address = connection.remote_address();
                         // listen for messages
                    }
                    Err(err) => {
                         // This is where I'm seeing the error
                         error!(
                              "An incoming connection failed because of an error: {:?}",
                              err
                         );
                    }
               },
               None => {
                    trace!("quinn::Incoming::next() returned None. There will be no more incoming connections");
                    break;
               }
          }
     }
});
```
The error is mostly `ConnectionError::Timeout` but sometimes I see `ConnectionError::Reset` or `ConnectionError::ConnectionClosed({ error_code: INVALID_TOKEN, ... })`

(I'll try with latest main and will update the TRACE logs below as well)

**Comment by lionel1704** [comment]
Logs leading up to `ConnectionError::Reset`
[reset-error.log](https://github.com/quinn-rs/quinn/files/6846366/reset-error.log)

Logs leading up to `ConnectionError::TimedOut`
[timeout-error.log](https://github.com/quinn-rs/quinn/files/6846381/timeout-error.log)

**Comment by Ralith** [comment]
How many concurrent connections, exactly, are you running? I se internal IDs in the five figure range. Is this a release build? What's your CPU load during the test?

**Comment by lionel1704** [comment]
The test creates a single endpoint which acts like a server and a 150 other endpoints connect to the server and send 100 messages each (on separate uni-streams). The server processes theses incoming messages and responds back.

Yes it's a release build and one of the cores in my CPU goes upto 100% at the start of the test and eventually settles down to ~50%.

**Comment by Ralith** [comment]
Are you saying that there's at most 150 concurrent connections? That seems at odds with the very high logged internal IDs.

**Comment by lionel1704** [comment]
Could the number of open uni-streams be the cause of the high number of internal IDs?

**Comment by Ralith** [comment]
No, all streams on a single connection are driven by the single connection task.

Regardless of the number of connections, it sounds like your CPU is saturated. If there's not enough CPU time to do everything that needs doing then timeouts, and resets when the timed-out peer tries to continue communication, aren't unreasonable. A good next step would be seeing if you have any issues at lower load, and profiling to see where all the CPU time is going.

**Comment by lionel1704** [comment]
@Ralith the CPU saturation clue was quite helpful. I took another look at my CPU activity during the test and found it suspicious that only one core was being used. Assuming that this is cargo's doing, I moved the code into an _example_ and that used all the cores available and I had the test passing! (Most of the time)

Sometimes however, I am still seeing the following error:
```
received an invalid Retry Token in a client Initial
```
(I'll enable quinn logs and share that info as well)

**Comment by Ralith** [comment]
tokio has both single- and multi-threaded modes and tests are usually singlethreaded for sanity's sake, yeah. If you're running many endpoints, parallelism will help.

> invalid Retry Token

This indicates that you've enabled stateless retry (which is not the default) and the server endpoint didn't see the retry packet until longer than `ServerConfig::retry_token_lifetime` (default 15 seconds) after it issued the token, causing the connection to be rejected. If your client receives this error (`TransportError::INVALID_TOKEN`), it can safely retry.

**Comment by lionel1704** [comment]
Thanks! I disabled stateless retry and ran the example again. And it is consistently passing now. Thanks! :tada: I'll close this issue now and reach out if I have any other issues :)
