### ISSUE TITLE
Add api to endpoint to kill a connection.

### ISSUE THREAD

**Issue by dvc94ch** [quinn-rs/quinn#1167]
So one issue that came up in the review of libp2p-quic was the use of unbounded channels. The suggestion was that if the libp2p connection buffer is full, the endpoint should kill the connection instead of unbounded buffering. This would require adding an api to the endpoint to kill the connection.

**Comment by djc** [comment]
Why is closing the connection not good enough? Would it be sufficient if we made the channels bounded?

**Comment by dvc94ch** [comment]
Well the problem is that the endpoint produces events and the connection processes them. Since these two components run separately there needs to be some buffering of endpoint events that are sent to the connection. The connection then has it's own buffer for flow control. I'm not sure exactly why the accept buffer in the endpoint and the flow control buffer in the connection aren't enough, but the use of unbounded channels was not appreciated in the review :man_shrugging:.

cc @Demi-Marie @tomaka

**Comment by dvc94ch** [comment]
Well, for now we just sleep the task once the incoming_slot or event_slot is filled. but in case more brute force measures are desired I'll reopen the issue.
