### ISSUE TITLE
extract udp socket handling into a separate crate

### ISSUE THREAD

**Issue by dvc94ch** [quinn-rs/quinn#1178]
I kind of did that for libp2p-quic [here](https://github.com/ipfs-rust/udp-socket) but it might make sense to unify the code bases, as it's probably useful to many people using udp sockets.

**Comment by Ralith** [comment]
It's an interesting idea. There's some possible drawbacks:
- In the long run, people with different use cases might end up each using only a small subset of the capabilities of such a library, which makes it less appealing.
- It could make porting to new platforms much more difficult for a given user, if such a port is expected to cover every feature, not just that user's requirements (see e.g. winit's maintenance challenges)

**Comment by kpp** [comment]
I think such a crate should not be general but specialized for use whithin quinn(-proto). 

> make porting to new platforms much more difficult for a given user

Extracting or not, such an issue remains. So far it is handled as a `fallback` module. We can do the same.

**Comment by dvc94ch** [comment]
> In the long run, people with different use cases might end up each using only a small subset of the capabilities of such a library, which makes it less appealing.

I assume the concern here is mainly with the maintainance overhead if people start requesting lots of features quinn doesn't use. But we can say no to such feature requests.

**Comment by Ralith** [comment]
If it's explicitly quinn- (or at least QUIC-) specific, and only split out for the benefit of people working with quinn-proto directly for whatever reason, then I don't see any major issues.

**Comment by djc** [comment]
Sounds okay to me, too.
