### ISSUE TITLE
Examples: client does not work and fails to connect after timeout

### ISSUE THREAD

**Issue by fgadaleta** [quinn-rs/quinn#1186]

**Comment by Ralith** [comment]
Connect to what?

**Comment by fgadaleta** [comment]
to the server (in the examples)

**Comment by Ralith** [comment]
Your system is probably resolving `localhost` to a different address family than the server is listening on, and giving you a single-stack socket.

**Comment by fgadaleta** [comment]
uhm that's weird. My system is resolving `localhost` to `127.0.0.1` as expected

**Comment by fgadaleta** [comment]
This is server

```
 cargo run --example server ./ 
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/server ./`
listening on [::1]:4433

```


And this is client 

```
cargo run --example client https://localhost:4433/Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/client 'https://localhost:4433/Cargo.toml'`
connecting to localhost at 127.0.0.1:4433
ERROR: failed to connect: timed out

```

**Comment by djc** [comment]
Your server is listening on IPv6, the client connects on IPv4.

**Comment by fgadaleta** [comment]
oh gosh you are right!
how is that?!

**Comment by djc** [comment]
The example server listens to IPv6 by default, IIRC.

**Comment by couchand** [comment]
In case anyone comes along trying to figure out how to resolve the issue:  you can configure the server to listen on IPv4 explicitly by passing the `--listen` CLI flag.  Something like:

```
$  cargo run --example server ./ --listen 0.0.0.0:4433
```

See: https://github.com/quinn-rs/quinn/blob/fc691a8d972935325ece688910df508d0d9ebd01/quinn/examples/server.rs#L40-L41
