### ISSUE TITLE
Why quinn::RecvStream is not implementing trait std::io::Read

### ISSUE THREAD

**Issue by tubzby** [quinn-rs/quinn#1189]
Currently, I'm trying to build a QUIC server. I have thought about using serde_json for serialization. 

I think [serde_json::from_reader ](https://docs.rs/serde_json/1.0.67/serde_json/fn.from_reader.html) is something I'm looking for, so I can receive JSON object one another in a sequense.

As the function name indicates, it requires trait std::io::Read, but it seems quinn::RecvStream doesn't implement that for some reason.

My question is, what's the reason for not implementing trait io::Read? I have been writing Golang for several years, it's much common to implement io.Reader if your library provides some function to read something out.

Or is there's something I have missing here ,or any other different approach?

**Comment by djc** [comment]
Since `quinn::RecvStream` is all about async operation, it implements tokio's [`AsyncRead`](https://docs.rs/tokio/1.11.0/tokio/io/trait.AsyncRead.html) instead.

**Comment by djc** [comment]
You might also like to use something like https://docs.rs/tokio-serde/0.8.0/tokio_serde/.

**Comment by tubzby** [comment]
Thanks, tokio_serde seems exactly what I need.

**Comment by tubzby** [comment]
Another question, tokio Frame codec seems to enforce some kind of delimiter, like a head of the length: https://github.com/tokio-rs/tokio/blob/master/tokio-util/src/codec/length_delimited.rs

But for json, this is not needed, any workaround?

**Comment by Ralith** [comment]
At a glance, https://docs.serde.rs/serde_json/struct.StreamDeserializer.html will probably be helpful, but you'll need to couple it to async I/O yourself.

**Comment by tubzby** [comment]
@Ralith yes, I can implement a new type wrapping up the stream inside, and implement std::io::Read.

**Comment by Ralith** [comment]
You can't implement `std::io::Read` because that's synchronous. Even if you could, you wouldn't want to, since you're trying to parse JSON, not get raw bytes.

**Comment by Ralith** [comment]
Closing as there's no action for us to take here. Feel free to hop in the gitter/matrix chat if you need advice!
