### ISSUE TITLE
Question about datagrams

### ISSUE THREAD

**Issue by protheory8** [quinn-rs/quinn#1200]
`README.md` mentions support for datagrams, does this mean that Quinn supports [An Unreliable Datagram Extension to QUIC](https://datatracker.ietf.org/doc/draft-ietf-quic-datagram) or does this mean something else (perhaps an implementation that isn't compatible with this extension)?

**Comment by djc** [comment]
Yes, we implement that extension (though I don't know if we're compliant with the latest draft).
