### ISSUE TITLE
Server Certificate verification does not verify certificate signed by intermediate CA

### ISSUE THREAD

**Issue by vlvicente** [quinn-rs/quinn#1203]
When setting a client connection with certificate verification, the server certificate is only trusted if it is signed by a root CA or if we load the intermediate CA which signed the server cert. 
Shouldn't the lib be able to verify the certificate as stated by the _rustls_ crate:
> You do not need to provide anything other than a set of root certificates to trust. Certificate verification cannot be turned off or disabled in the main API.

The error is:
```
16:14:16 [WARN] Sending fatal alert BadCertificate
ERROR: failed to connect: the cryptographic handshake failed: error 42: invalid certificate: UnknownIssuer
```
I've tested this behavior by loading a set of root CA and using the native-certificates set as default feature in the crate.
In my example I'm using a certificate signed by **Sectigo RSA Domain Validation Secure Server CA** which was emmited by the root **USERTrust RSA Certification Authority** but quinn only verifies the certificate if I load the Sectigo certificate.

Note that when using _TcpStream_ and _rustls::Stream_ to make a simple https call, the certificate is verified without setting the intermediate CA.

**Comment by Ralith** [comment]
@vvicente-adyta are you still having issues with this?

**Comment by vvicente-adyta** [comment]
Solved long ago... did not remember to close here... For what I remember the problem was in webpki lib and was solved in some version upgrade.
