### ISSUE TITLE
connection migration demo

### ISSUE THREAD

**Issue by Rouzip** [quinn-rs/quinn#1205]
Hello, I have read the demo code in quinn examples. And it just rebinds the address before web request. In the https://github.com/quinn-rs/quinn/issues/1160#issuecomment-880439526, Ralith said `A client implicitly migrates to whatever address it sends packets from. No manual action at the application layer is needed.`.  Can I migrate connection during web request? (rebind the client socket?)

**Comment by Ralith** [comment]
https://github.com/quinn-rs/quinn/pull/1217 should resolve the suspected issue.
