### ISSUE TITLE
Remove use of the unwrap crate from quinn tests

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#1215]
This crate was a workaround for `unwrap` panic messages having a crappy source location, but this was fixed upstream in https://github.com/rust-lang/rust/issues/47809. It's now a superfluous dependency, which could be easily dropped.

**Comment by Rouzip** [comment]
> This crate was a workaround for `unwrap` panic messages having a crappy source location, but this was fixed upstream in [rust-lang/rust#47809](https://github.com/rust-lang/rust/issues/47809). It's now a superfluous dependency, which could be easily dropped.

Hello, I think I can try to fix it.

**Comment by djc** [comment]
@Rouzip would be great, thanks!
