### ISSUE TITLE
Must finish() be called after sending data?

### ISSUE THREAD

**Issue by go-jar** [quinn-rs/quinn#1255]
After sending data by SendStream, I must call finish() to make peer receive data. 
```
send.write_all(request.as_bytes())
    .await
    .map_err(|e| anyhow!("failed to send request: {}", e))?;
send.finish()
    .await
    .map_err(|e| anyhow!("failed to shutdown stream: {}", e))?;
```

But I want to use the same stream to send data and peer can receive data every time. I don't know how to make it, because SendStream has no  method flush(). 
Client:
```
send.write_all(b"hello")
    .await
    .map_err(|e| anyhow!("failed to send request: {}", e))?;
send.flush()

send.write_all(b"world")
    .await
    .map_err(|e| anyhow!("failed to send request: {}", e))?;
send.flush()

send.finish()
    .await
    .map_err(|e| anyhow!("failed to shutdown stream: {}", e))?;
```
Server:
```
let resp = recv
        .read_to_end(usize::max_value())
        .await
        .map_err(|e| anyhow!("failed to read response: {}", e))?;
println!("recv: {:?}", resp);

let resp1 = recv
        .read_to_end(usize::max_value())
        .await
        .map_err(|e| anyhow!("failed to read response: {}", e))?;
println!("recv: {:?}", resp1);
```

**Comment by Ralith** [comment]
Data on streams is sent immediately; there is no need to flush. Finish is only for indicating when you are permanently done sending data on that stream.

**Comment by go-jar** [comment]
> Data on streams is sent immediately; there is no need to flush. Finish is only for indicating when you are permanently done sending data on that stream.

Thanks！ But server won't receive any data until client call finish(). And once the finish() is called, the stream is terminated. So client must call open_uni() or open_bi() to send data again.

**Comment by djc** [comment]
Well, you're using `read_to_end()` on the server, so of course the server-side reads won't give you anything until the client calls `finish()`.

**Comment by go-jar** [comment]
> Well, you're using `read_to_end()` on the server, so of course the server-side reads won't give you anything until the client calls `finish()`.

Thanks!

**Comment by Ralith** [comment]
`read` will yield any available data, yeah. Note that just like TCP, write boundaries are not preserved within streams, so if you want to send discrete messages on a single stream you'll need some form of framing (e.g. [tokio's LengthDelimited codec](https://docs.rs/tokio-util/0.6.9/tokio_util/codec/length_delimited/index.html))

**Comment by go-jar** [comment]
> `read` will yield any available data, yeah. Note that just like TCP, write boundaries are not preserved within streams, so if you want to send discrete messages on a single stream you'll need some form of framing (e.g. [tokio's LengthDelimited codec](https://docs.rs/tokio-util/0.6.9/tokio_util/codec/length_delimited/index.html))

Thanks!
