### ISSUE TITLE
next() method not found in Incoming

### ISSUE THREAD

**Issue by euberdeveloper** [quinn-rs/quinn#1262]
Part of my code in the server is:

```rs
let (endpoint, mut incoming) = quinn::Endpoint::server(server_config, listen_address)?;
println!("listening on {}", endpoint.local_addr()?);

while let Some(conn) = incoming.next().await {
        // my code
}
```

I have this compile error when I call `.next()`:

```no method named `next` found for struct `quinn::Incoming` in the current scope```

Is it anything with the version `0.8.0` of Quinn?

**Comment by euberdeveloper** [comment]
Sorry for the mistake, I am new to rust

I just had to use ```use futures_util::stream::stream::StreamExt;``` because the implementation of the trait with `next` for `Incoming` was not on scope

**Comment by Ralith** [comment]
That's correct; no worries! I've actually been thinking of adding an inherent version, to avoid the mandatory (surprisingly heavy) futures_util dep.

**Comment by wmmc88** [comment]
> That's correct; no worries! I've actually been thinking of adding an inherent version, to avoid the mandatory (surprisingly heavy) futures_util dep.

I thought #1263 removes the need for `use futures_util::stream::stream::StreamExt;`, but it seems like its still required?
