### ISSUE TITLE
How to disable ack?

### ISSUE THREAD

**Issue by go-jar** [quinn-rs/quinn#1265]
When transmitting a video stream, write_all() takes a long time, so I want to disable ack. May I ask how to disable ack?

**Comment by Ralith** [comment]
ACKs have nothing to do with how long it takes to send data. How much bandwidth are you using? Is the link saturated?

**Comment by go-jar** [comment]
> ACKs have nothing to do with how long it takes to send data. How much bandwidth are you using? Is the link saturated?

The write_all() generally takes 40ms, which is approximately equal to rtt. If there is no ack, will it take less time?

**Comment by Ralith** [comment]
No. If you're not saturating the link (are you?) you may be limited by flow control, which is up to you to configure appropriately.

**Comment by go-jar** [comment]
May I ask how to check if the link is saturated?

**Comment by Ralith** [comment]
Compare the rate that you're exchanging data with the rate that the network path between you and your peer is capable of supporting. This is usually determined by the plan you have from your service provider, on both ends.

**Comment by go-jar** [comment]
> Compare the rate that you're exchanging data with the rate that the network path between you and your peer is capable of supporting. This is usually determined by the plan you have from your service provider, on both ends.

Thanks! I still have a question, does write_all().await will end until the sent data has received ack?

**Comment by go-jar** [comment]
I find that the link is not saturated. May be send_stream.finish().await will end until all sent data received ack.

**Comment by Ralith** [comment]
From the documentation:

> [SendStream::finish] completes when the peer has acknowledged all sent data

If you don't want to wait for the peer to acknowledge everything, don't `await` on `finish`. It's entirely optional to do so.

**Comment by go-jar** [comment]
> From the documentation:
> 
> > [SendStream::finish] completes when the peer has acknowledged all sent data
> 
> If you don't want to wait for the peer to acknowledge everything, don't `await` on `finish`. It's entirely optional to do so.

Thanks!

**Comment by Ralith** [comment]
Yes. You don't need to call `finish` at all.

**Comment by go-jar** [comment]
> Yes. You don't need to call `finish` at all.

Thanks!
