### ISSUE TITLE
crash on unwrap in SendStream::poll_shutdown

### ISSUE THREAD

**Issue by cfal** [quinn-rs/quinn#1298]
hi! i have a test app that has no unsafe code. i'm seeing a crash on unwrap in poll_shutdown [here](https://github.com/quinn-rs/quinn/blob/main/quinn/src/send_stream.rs#L143) very often. i have tested at HEAD as well as with 0.8.0 and it happens with both.

here's the full stack trace while running at HEAD: https://gist.github.com/cfal/209e73c7b00e0d83101240bcc13ab3f3

thank you!

**Comment by Ralith** [comment]
Can you share your code?

**Comment by Ralith** [comment]
Closing as nobody else has observed this and there's been no further engagement from the reporter.
