### ISSUE TITLE
possible to implement io uring?

### ISSUE THREAD

**Issue by hiqsociety** [quinn-rs/quinn#1319]
https://github.com/bytedance/monoio

**Comment by djc** [comment]
Yes, this should be possible. I'd probably try tokio-uring before monoio but quinn-proto should allow you to build it anyway you like.

**Comment by hiqsociety** [comment]
monoio definitely faster than tokio uring coz it's thread per core concept.

**Comment by Ralith** [comment]
Note that this isn't necessarily a performance win, and may compromise conformance. For example, I'm not sure if generic receive offload is supported by io_uring yet, and that's an important contributor to making heavy UDP workloads fast. Full correctness parity will also require support for setting/getting ECN flags and the local IP address packets are addressed from/to.

**Comment by Ralith** [comment]
Closing as a dup of https://github.com/quinn-rs/quinn/issues/915.
