### ISSUE TITLE
any automatic letsencrypt auto renewal cert example?

### ISSUE THREAD

**Issue by hiqsociety** [quinn-rs/quinn#1321]
any automatic letsencrypt auto renewal cert example?

great work by the way.

**Comment by djc** [comment]
I don't see how QUIC and ACME are connected. In principle you should be able to use any ACME clients that work with rustls.

**Comment by Ralith** [comment]
Automated certificate acquisition/renewal is well out of scope of quinn('s documentation), as it involves considerable additional complexity such as a web server and tends to be deployment-specific. Off-the-shelf tools like certbot should work fine.
