### ISSUE TITLE
Hey when does quinn go to version 1.x.x ? Thx

### ISSUE THREAD

**Issue by Kiddinglife** [quinn-rs/quinn#1327]

**Comment by Ralith** [comment]
Probably when we've gone a few significant releases without a breaking change. Why?

**Comment by Kiddinglife** [comment]
Just wondering how stable Quinn is now. Anyway, will close this issue ticket.

**Comment by djc** [comment]
In large parts of the Rust ecosystem, there's limited correlation between whether an API/library is stable or not and whether it has a version number smaller or greater than 1.0. I like to think Quinn is pretty stable; we do occasionally release some breaking API changes but our high-level APIs have not changed much over time.

**Comment by Ralith** [comment]
Right, there are no *high-impact* breaking changes expected for the foreseeable future, though there will likely continue to be occasional minor technical breaks. We invest significant effort in forwards-compatible API design.
