### ISSUE TITLE
Can you share snippet of code to broadcast data to client using single connection 

### ISSUE THREAD

**Issue by vinay10949** [quinn-rs/quinn#1331]
Can you share snippet of code to broadcast data to client using single connection .

Also share Peer to Peer Comunication snippet .

**Comment by Ralith** [comment]
Please refer to https://github.com/quinn-rs/quinn/tree/main/quinn/examples.

**Comment by vinay10949** [comment]
@Ralith Code doesnt have P2P example . can you demonstrate ,A simple P2P chat app

**Comment by Ralith** [comment]
QUIC requires no special measures for P2P use, just like plain UDP or TCP. Where did you get stuck?

**Comment by vsawant1989** [comment]
@Ralith  Basically we want broadcast data to many peers ,at the same time the peers should be able to send data to sender. 
The problem is with connection.We cannot use same connection

**Comment by djc** [comment]
QUIC does not have broadcast functionality like UDP. Like TCP, QUIC is a connection-oriented protocols where two participates set up a connection by handshaking. If you want to communicate between many peers, you'd have to set up one connection per pair of peers or use some kind of gossip protocols.

We don't just write examples on spec. If you have a well-defined problem with some code you've written we might help you troubleshoot.
