### ISSUE TITLE
open connection without opening stream

### ISSUE THREAD

**Issue by sakridge** [quinn-rs/quinn#1339]
In our application it is fairly latency sensitive and when we open the connection sometimes we are seeing multiple seconds to send the first stream bytes. We are able to predict when we need the connection somewhat before we know what to send. It didn't seem possible to open the connection without sending anything, is there actually a way to do this?

**Comment by Ralith** [comment]
Connections are initiated immediately upon request. It's not even possible to send stuff until the connection's open unless you're going out of your way to use 0-RTT.

**Comment by sakridge** [comment]
ok, thanks
