### ISSUE TITLE
memory leakage

### ISSUE THREAD

**Issue by Yaoxiao1** [quinn-rs/quinn#1348]
My program is using a relay server to transfer message from peer to peer, each time when a connection was created, the server would take more memory than before, as the server might running for a long period, the memory will finally run out.
I wrote a test program and used a memory profiler called [bytehound](https://github.com/koute/bytehound) to check the leaked memory , the test program created 100 pairs of connecntions under `tokio::spawn`, let call it P1-P2 pair, in each connection, P1 will send a 20KB message to P2 first, and P2 will send another 20KB message back, and repeat for serveral seconds. 
according to the memory profiler,  the memory usage will grow fast when creating connections, after the message-transfer, most of the memory will be freed, but there is still small part of them remain unfreed. please see below picture,
![2022-04-25 14-44-56 的屏幕截图](https://user-images.githubusercontent.com/34466246/165034991-e0cf70f2-beef-4fdf-8ea0-ebde024e6a60.png)
![2022-04-25 14-45-13 的屏幕截图](https://user-images.githubusercontent.com/34466246/165035034-a8365ef1-57df-4f07-8a15-00550143e1ed.png)
overall it created about 1MB memory leakage, and the Connection took 493KB of them, and when creating more connections, the protion of leakage caused by Connection will be higher and higher, below is a flamegraph of leaked memory
![2022-04-25 14-53-25 的屏幕截图](https://user-images.githubusercontent.com/34466246/165035832-6271ac14-bbb4-4f06-b27e-f3c82a25b149.png)
it looks like the Connection allocate some reserved space for message and didnot free them, I'm not sure, can you help explain?
Thanks.

**Comment by djc** [comment]
If I understand the flamegraph correctly, it's actually rustls that holds on to a large allocation. I think https://github.com/rustls/rustls/issues/794 would be the relevant issue.

**Comment by Matthias247** [comment]
FWIW, most of the rustls state shouldn't be required at all after the connection was initially established. Maybe there's some potential to compact or drop things.

**Comment by Matthias247** [comment]
For the question itself, it might also be useful to look into configuring suitable idle and keepalive timeouts to make sure connection state is not kept around forever. If one side has a keepalive mechanism running that is lower than the idle timeout of both sides, then connection state will be around for pretty much forever in the absence of networking issues.

**Comment by djc** [comment]
rustls already supports dropping the Connection and only retaining the required key state.

**Comment by Ralith** [comment]
`CRYPTO` frames may be delivered on an established connection, so that might be too big a hammer.

**Comment by Ralith** [comment]
> Once the handshake completes, if an endpoint is unable to buffer all data in a CRYPTO frame, it MAY discard that CRYPTO frame and all CRYPTO frames received in the future

So we can actually just drop data at that point; that might be a good next step, then.
