### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sakridge** [quinn-rs/quinn#1352]
Could there be a new release please with `set_max_concurrent_uni_streams`?

**Comment by Ralith** [comment]
Sure, though we should probably roll back #1269 and maybe get async-std support merged first.

**Comment by sakridge** [comment]
Any updates?

**Comment by Ralith** [comment]
I've been hoping for feedback on https://github.com/quinn-rs/quinn/pull/1357, but it doesn't seem to be happening. In the mean time I've finished reviewing https://github.com/quinn-rs/quinn/pull/1346, which now needs some additional work.

Do you have a pressing need for a release? A git dependency is usually sufficient for development purposes, but perhaps we could backport the new interfaces you're interested in to 0.8 if a formal release is important and the breaking changes don't get sorted out soon.

**Comment by sakridge** [comment]
> Do you have a pressing need for a release? A git dependency is usually sufficient for development purposes, but perhaps we could backport the new interfaces you're interested in to 0.8 if a formal release is important and the breaking changes don't get sorted out soon.

Yes. We would like to ship code based on this feature. We can't ship based on a git dependency.

**Comment by sakridge** [comment]
> We're referring to https://github.com/quinn-rs/quinn/pull/1315 here, right?

yes.

**Comment by Ralith** [comment]
Fixed by (publication of) https://github.com/quinn-rs/quinn/pull/1358.
