### ISSUE TITLE
new_connection.uni_streams.next().await does not return until finish() is called

### ISSUE THREAD

**Issue by lso400** [quinn-rs/quinn#1365]
Client:
```
  let connecting = endpoint.connect(server_addr, SERVER_NAME).unwrap();
    let mut new_connection = connecting.await.unwrap();
    log::info!(
        "[client] connected: addr={}",
        new_connection.connection.remote_address()
    );
    loop {
        log::info!("checking if streamed is opened");
        if let Some(Ok(mut recv_stream)) = new_connection.uni_streams.next().await {
            // the below line never gets printed
            log::info!("stream opened from server");  
        }
    }
```

The client seems to get stuck in `new_connection.uni_streams.next().await` however the server has already opened a stream and started writing into it.
The client is able to read the stream only when the server calls `sender_stream.finish().await`

**Comment by djc** [comment]
What version?

**Comment by lso400** [comment]
```
quinn = "0.8.3"
rustls = { version = "*", features = ["dangerous_configuration", "quic"] }
rcgen = "0.9.2"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
tokio = { version = "1.17.0",  features = ["full"] }
```

**Comment by Ralith** [comment]
Quinn always processes writes immediately; there is no equivalent to TCP's notorious "nagle's algorithm." Hence, this should not happen. Can you demonstrate it with a minimal standalone reproduction?

**Comment by Ralith** [comment]
There is no compatibility issue. However, `try_recv` will immediately return `None` if there's nothing in the channel, which will cause that code to busy-loop, which will interfere with any other async task from functioning correctly on that thread.

**Comment by lso400** [comment]
But the `written into stream` log line is printed, does it not mean the `write_all` has finished?
I tried putting `sender_stream.flush().await.unwrap()` after the write and it does not help as well
Also tried replacing `try_recv` with `recv`, no luck.
Would you have any suggestion to get around this? Thanks.

**Comment by Ralith** [comment]
I suggest you fix the busy-loop in your code. async can't work as intended when a single task is consuming the entire CPU thread to do nothing.

**Comment by Ralith** [comment]
To be clear, blocking the thread with a blocking `recv` is almost as bad, since it too prevents other tasks from using the thread. You should use an `async`-capable channel that you can `await` on rather than spinning or blocking, if your application requires this pattern.

**Comment by lso400** [comment]
Thanks a lot! Replacing `crossbeam` with `async-channel` solved my issue!
