### ISSUE TITLE
Wasm/web support?

### ISSUE THREAD

**Issue by FredrikNoren** [quinn-rs/quinn#1388]
Hey guys,

Do you have any plans to support wasm as a target for quinn? (On the web I mean, i.e. being able to compile a project with quinn and then running it on a website).

**Comment by Ralith** [comment]
For very good security reasons, webpages cannot send/receive arbitrary UDP packets, so it is impossible to run a QUIC implementation inside one. You might be interested in [`WebTransport`](https://web.dev/webtransport/) an upcoming web standard that will allow similar capabilities.

**Comment by FredrikNoren** [comment]
@Ralith Ok, thank you!

**Comment by timvw01** [comment]
@Ralith Would this also apply for a rust / quinn client in wasm32-unknown-unknown? Where can i find more info on this? 

Thanks.

**Comment by Ralith** [comment]
I don't think wasm32-unknown-unknown defines any socket APIs at all, so that will depend on what nonstandard APIs your specific runtime environment provides.

**Comment by Ralith** [comment]
See https://github.com/quinn-rs/quinn/issues/1388#issuecomment-1199750713.

**Comment by tbillington** [comment]
Just for completeness, would quinn support webtransport once it's released, or is that explicitly not a planned feature/target?

For context am building a project in bevy using quinn and evaluating what it would take to support WASM :) cheers

**Comment by Ralith** [comment]
There are now implementations of WebTransport that use Quinn, e.g. https://github.com/kixelated/webtransport-rs. Quinn is a QUIC implementation, and WebTransport is built on top of (HTTP/3 which is built on top of) QUIC.

**Comment by Ralith** [comment]
For visibility, https://github.com/quinn-rs/quinn/pull/1996 will fix the build on wasm32-unknown-unknown. WebTransport should be preferred where applicable as discussed above, but this should help for the exceptional cases where WebTransport cannot be used.

**Comment by guest271314** [comment]
@Ralith

> For very good security reasons, webpages cannot send/receive arbitrary UDP packets, 

That's not technically correct. WICG Direct Sockets is exposed in Isolated Web Apps on Chromium-based browsers (Chromium, Chrome, Brave, Opera, Edge). `UDPSocket` is one interface, where it's possible to do this in the browser

```
var s = new UDPSocket({localPort:10000, localAddress:"0.0.0.0"});
s.closed.then(console.log).catch(console.error);
var {readable, writable} = await s.opened;
var encoder = new TextEncoder();
var decoder = new TextDecoder();
readable.pipeTo(
  new WritableStream({
    write({data}) {
      console.log(decoder.decode(data));
    },
    close() {
      console.log("close");
    }
  })
).catch(console.log);
```

and on the command line send packets to the browser over UDP 

```
deno -A --unstable-net deno-udp.js 'Test, test, test. Test to the point it breaks.'
```

```
const encoder = new TextEncoder();
const listener = Deno.listenDatagram({
  port: 10001,
  transport: "udp",
});
const peerAddress = {
  transport: "udp",
  hostname: "0.0.0.0",
  port: 10000,
};
await listener.send(encoder.encode(Deno.args.at(-1)), peerAddress);
```

**Comment by Ralith** [comment]
That's very different than an arbitrary web page, but it would be a cool application!

**Comment by guest271314** [comment]
> That's very different than an arbitrary web page, but it would be a cool application!

Watch this 

- https://github.com/guest271314/telnet-client
- https://github.com/guest271314/direct-sockets-http-ws-server

Connecting the to Isolated Web App using WebRTC Data Channels from an arbitrary Web page (this issue in DevTools), where inside of the Isolated Web App `TCPSocket` is used to connect to a server using `txiki.js`, then the data is sent back to the arbitrary Web page
![Image](https://github.com/user-attachments/assets/d2a552a1-f72b-4d42-badf-49af4cb86209)

Starting `TCPServerSocket` (running in the browser in the IWA) from an arbitrary Web page and making HTTP and WebSocket connection to `TCPServerSocket` 
![Image](https://github.com/user-attachments/assets/114810f0-4491-42de-906f-bea3f0aa0ea1)

So, it's possible using differnt approaches to connect to and/or initialize and control a UDP socket or TCP server from arbitrary Web pages.

I found this repository because now I'm trying to implement a WebTransport server over HTTP/2 (h2c or otherwise) or outright HTTP/3 in JavaScript in the browser.

**Comment by guest271314** [comment]
@Ralith 

From an email between myself and an IWA maintainer

> Does the new API provide a means to create an HTTP/2 TCPServerSocket?

>> No, verifying certificates isn't necessary to implement an HTTP/2 server. You could do that today with TCPServerSocket, or implement a QUIC server with UDPSocket.

> I don't see a way to implement TLS in an IWA for TCPServerSocket. I don't think Chromium supports "clear text" HTTP/2. A QUIC *server* over UDPSocket?

>> There's nothing stopping you from implementing your own TLS client/server library on top of the Direct Sockets API. The API proposed here makes that easier by allowing you to validate certificates using the browser's certificate store instead of providing your own.

> From my reading of the WICG repository HTTPS is explicitly not allowed https://github.com/WICG/direct-sockets/issues/19.
>
> I'm curious how you would implement HTTPS/TLS in an IWA for Direct Sockets. 

>> That issue is obsolete. There is nothing stopping you from implementing a WebTransport server other than building an implementation using JavaScript or WebAssembly.

**Comment by guest271314** [comment]
My first thought was compile quinn to WASM and then compile that WASM to JavaScript with Binaryen's `wasm2js`.

What I'm really trying to understand is the basic HTTP/3 headers necessary to initialize a HTTP/3 connection for use with WebTransport client and WebTransport server implemented in JavaScript in the browser. I've done HTTP, HTTP/1.1 WebSocket upgrade. Now I'm exploring WebTransport.

I'm thinking maybe, just maybe, I could just write out the response headers and initialize the streaming connection using JavaScript in the browser alone - without WebAssembly.
