### ISSUE TITLE
Very low throughput when perfing

### ISSUE THREAD

**Issue by alexj0l** [quinn-rs/quinn#1390]
Hi everyone,
when I'm running `cargo run --bin perf_client` on a host and `cargo run --bin perf_server` on another host within mininet network I get a maximal upload/download throughput of 19-20MiB/s. What's the reasons of this? 
For comparison, I've tried to perf another QUIC Implementation (msquic) and I get there almost 1GiB/s.
Could someone help me?

**Comment by djc** [comment]
Maybe try with `--release`?

**Comment by Ralith** [comment]
Presuming resolved.
