### ISSUE TITLE
A way of explicitly detecting a timeout/connection close

### ISSUE THREAD

**Issue by WilliamVenner** [quinn-rs/quinn#1395]
Hi there,

Is there a way to explicitly detect if a connection has timed out or closed without affecting or opening streams?

I have a situation where I am waiting on a future that must be aborted if the connection times out or the connection closes. Unfortunately at this point I am unable to open, read or write to any streams of the connection, so I need to explicitly listen for a timeout/connection close.

Is there any way to do this in Quinn currently?

Many thanks

**Comment by WilliamVenner** [comment]
I found https://docs.rs/quinn/latest/quinn/struct.SendStream.html#method.stopped !!

**Comment by Ralith** [comment]
It's also common to use the end of incoming datagrams/streams/whatever from the streams in `NewConnection` to determine this.
