### ISSUE TITLE
Connection loss notification

### ISSUE THREAD

**Issue by MOZGIII** [quinn-rs/quinn#1398]
I'm looking for a way to detect when a connection was lost, but I can't find anything I could use.

It seems like there is some machinery available internally for that, but I don't see it exposed.

My use case is proxying the incoming connections to the dynamically coming and going upstream, and I need to know when an upstream is gone. The upstreams count can be huge (say 10000 per server), and the proxy is a dynamic amount of long-running bidi data flows (low-intensive though).

**Comment by Ralith** [comment]
See https://github.com/quinn-rs/quinn/pull/1396.

**Comment by MOZGIII** [comment]
Cool, thx! While we're at it: any chance of getting this released to crates.io in the near future?

**Comment by Ralith** [comment]
I don't have specific plans for a release soon. Is there a problem with using the existing approach described in that PR?

**Comment by MOZGIII** [comment]
No, all good. It's just that PR is pretty important (at least it seems to be) but without the release changes from it are not discoverable via docs.rs. The changes themselves can be used if pulled via git of course, but that still is a bit of a problem for discovery.
On the topic of the issue: solved, just what I was looking for.

**Comment by Ralith** [comment]
To be clear, the text of the PR describes how to accomplish this using the existing, released, API.

**Comment by MOZGIII** [comment]
Yep, that works too!
