### ISSUE TITLE
tag for 0.8.5?

### ISSUE THREAD

**Issue by mystenmark** [quinn-rs/quinn#1408]
I noticed that the highest tag on github is 0.8.3, but the current version on crates.io is 0.8.5 - I assume whoever did the release never ran `git push --tags` - if you wouldn't mind updating the tag that would be great. Thanks!

**Comment by djc** [comment]
Sorry about that -- pushed the tags.

**Comment by jxs** [comment]
Cargo.toml also seems outdated, shows [`0.8.0`](https://github.com/quinn-rs/quinn/blob/main/quinn/Cargo.toml#L3)

**Comment by djc** [comment]
That's expected, the changes so far have been in the other crates that the quinn crate depends on.

**Comment by Ralith** [comment]
Also, that's the Cargo.toml from main, whereas you probably wanted the 0.8.x branch: https://github.com/quinn-rs/quinn/blob/0.8.x/quinn/Cargo.toml#L3

**Comment by jxs** [comment]
yeah exactly, my confusion was that I added `quinn` as a dependency and saw `0.8.5` then went to check the features and expected `master`'s `Cargo.toml` version to match it. 
Thanks for the clarification :)
