### ISSUE TITLE
`Connection::closed` never terminates if called on an already-closed connection

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#1411]
We need to check the current state before waiting.

**Comment by darioalessandro** [comment]
Hey @Ralith , I am trying to help with this. 

Is this the method that hangs? 

https://github.com/quinn-rs/quinn/blob/166e0fb60a64b10da9b4aeec5bce9c3c39a057d5/quinn/src/connection.rs#L323-L342

**Comment by Ralith** [comment]
Thanks for the interest! It looks like this was actually fixed incidentally in 3e2935ff5faced76f71a4f4df9a423f592514272.

**Comment by darioalessandro** [comment]
Sweet
