### ISSUE TITLE
0.9 release planning

### ISSUE THREAD

**Issue by terrarier2111** [quinn-rs/quinn#1419]
When will there be a new release? It has almost been a year since the last one was made and there were a decent amount of new things that quinn's users could benefit from is there a reason why no new release was made in such a long period of time?

**Comment by Ralith** [comment]
0.8.5 was released about a month ago. I'd be happy to put out 0.9 soon,
though, since we finally merged the big pending API changes.

**Comment by djc** [comment]
I think we should probably get #1219 in first, though?

**Comment by Ralith** [comment]
I'm actually conflicted on that. IIRC that's a purely internal change, and if it has bugs, it might be nice to be able to yank its release without pushing people back to 0.8. I would like to fix https://github.com/quinn-rs/quinn/issues/1421 though, if we get a repro for it.

**Comment by Ralith** [comment]
With that fixed I don't have anything else on my wishlist, and I'm content to pursue #1219 as followup non-breaking update. Any other blockers?

**Comment by Fhokud** [comment]
Can you update the version on the release page？It still stays at 0.8.0.

**Comment by zicklag** [comment]
@Fhokud it looks like the release hasn't actually been made yet.

---

I think I'm going to be using Quin with the new custom executor option so I can integrate it with Bevy's built-in async executor, so if this is ready, a release would be useful to me too.

**Comment by djc** [comment]
Some more work to do in #1431.
