### ISSUE TITLE
[Feature] Custom Socket Implementations

### ISSUE THREAD

**Issue by zicklag** [quinn-rs/quinn#1432]
Do you think that custom socket implementations would be something you would be open to in the `quinn` crate?

Right now you must have an `std::net::UdpSocket` to create an endpoint, but I was thinking about trying to run in the browser using WebRTC for the unreliable transport.

Do you think this something we'd like to support, or would it be better to create a custom Web-specific API built on `quinn-proto`?

I'd have to look into it more, but I think that the existing `quinn` API would work fine if we created some kind of a transport abstraction. The executor shouldn't be a problem, because we can still spawn async tasks in WASM.

**Comment by djc** [comment]
Have a look to see if https://github.com/quinn-rs/quinn/pull/1364 will cover your use case.

**Comment by zicklag** [comment]
Ah, actually I think that's perfect! Sorry for the noise.

I had missed the `Endpoint::new_with_abstract_socket()` method and only noticed the `Endpoint::new` method which required a UDP socket.

Thanks!

**Comment by Ralith** [comment]
Also keep an eye out for WebTransport coming natively to browsers in the
future. With some effort, it should be usable to communicate directly from
a browser to a native Quinn server.
