### ISSUE TITLE
Upgrade tokio to resolve ntapi & tokio-rs/mio dependency warning

### ISSUE THREAD

**Issue by temportalflux** [quinn-rs/quinn#1437]
Tokio 1.13 uses ntapi 0.3.6 as a dependency, which will be rejected by a future version of Rust. This causes compiler warnings for users of quinn. Upgrading to tokio >1.17 (preferably latest of 1.21) may resolve this warning (https://github.com/tokio-rs/tokio/releases/tag/tokio-1.17.0).
"warning: the following packages contain code that will be rejected by a future version of Rust: ntapi v0.3.6"

Only found this dependency in the quinn tree by using `cargo tree`, and searching for ntapi.

**Comment by djc** [comment]
You can just cargo update your workspace and everything will be fine, right?

**Comment by temportalflux** [comment]
I.... did not know I could do that... and that fixed it too 😅
