### ISSUE TITLE
Connection setup in quinn-proto

### ISSUE THREAD

**Issue by jodiserla** [quinn-rs/quinn#1441]
Hello, I was wondering how the connection setup works in quinn-proto. I am implementing Quic in a framework that has its own event loop and an udp_state which reads from, and writes to an udp socket. What I am trying to do is implement quinn-proto on top of that udp_state and triggering the read/write method when applicable.
I have a bit hard time understanding how the connection setup works in quinn_proto. 
I start by calling the connection method listed in the endpoint, but its quite unclear to me what should happen afterwards - how can the other endpoint accept the connection? How do I know when both endpoints are connected? Are there any code examples, or docs I could check out to see how this should be done in quinn-proto?

**Comment by Ralith** [comment]
> how can the other endpoint accept the connection?

`Endpoint::handle` will return a `DatagramEvent::NewConnection` when you pass it a datagram that successfully initiates a handshake.

> How do I know when both endpoints are connected?

When `Connection::poll` returns `Event::Connected`.

> Are there any code examples, or docs I could check out to see how this should be done in quinn-proto?

The API docs for `quinn_proto::Connection` will probably be of particular interest. In addition to the high level quinn crate itself, the test support code at https://github.com/quinn-rs/quinn/blob/main/quinn-proto/src/tests/util.rs might be a useful example.

**Comment by djc** [comment]
Note that since 0.9, the Quinn crate also has a runtime abstraction as well as an AsyncUdpSocket abstraction, so a viable alternative for your separate runtime/event loop use case might be to build on top of that instead of reinventing some of the wheels on top of quinn-proto.

**Comment by jodiserla** [comment]
I feel like the problem is partly from the NeedIdentifiers and
NewIdentifiers, but I am not 100% sure..
