### ISSUE TITLE
"ReadDatagram notified with no datagrams pending" panic

### ISSUE THREAD

**Issue by stormshield-pj50** [quinn-rs/quinn#1454]
Dear all,

I am trying to receive datagrams on a Quic connection using two futures handled by a FuturesUnordered structure. Each future clones the connection and call read_datagram() on the cloned connection. I got a panic in quinn/src/connection.rs:730. 

In order to reproduce the crash you can use my forked quinn repo and [this commit](https://github.com/stormshield-pj50/quinn/commit/060aa197dca5e289bd875c0269c66459e5ec41d0).  It basically setups a datagram client/server. You can reproduce the issue by running on the same machine:

cargo run --example datagram_server
cargo run --example datagram_client

Thanks for looking at this,
Philippe

**Comment by Ralith** [comment]
Looks like a bit of missed refactoring when we moved away from streams. Should be fixed by https://github.com/quinn-rs/quinn/pull/1455.

**Comment by Ralith** [comment]
Fix published in 0.9.2.
