### ISSUE TITLE
Is QUIC Still a Draft?

### ISSUE THREAD

**Issue by zicklag** [quinn-rs/quinn#1467]
I see this line in the docs:

https://github.com/quinn-rs/quinn/blob/389d7ce5067fbef460f0730861340b15f13d4803/docs/book/src/quic.md?plain=1#L4

From what I can tell from the IETF tracker, it seems that now QUIC is no longer in the draft phase is that right?

**Comment by Ralith** [comment]
Correct. The text there should be updated or removed.

**Comment by zicklag** [comment]
Cool, opened a PR to tweak the wording.
