### ISSUE TITLE
The client can't reach the server on windows 11

### ISSUE THREAD

**Issue by Nawy** [quinn-rs/quinn#1490]
I tried to make a request to the server, but It wasn't going through. The error is timeout.

The client is Windows 11 Pro (21H2) OS Build: 22000.1516.
```
Running `C:\Users\Nawy\quinn\target\debug\examples\client.exe https://77.50.177.242:4433/Cargo.toml`
connecting to 77.50.177.242 at 77.50.177.242:4433
ERROR: failed to connect: timed out
```
The same network, and the same Wi-Fi, but on Macbook the expected error:
```
connecting to 77.50.177.242 at 77.50.177.242:4433
ERROR: failed to connect: the cryptographic handshake failed: error 42: presented server name type wasn't supported
```

Okay, I decided to try different QUIC client. In my case QUICHE. I tested one more time on Windows with the QUICHE client. And it works.
```
PS C:\Users\Nawy\quiche> cargo run --bin quiche-client -- https://77.50.177.242:4433
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target\debug\quiche-client.exe https://77.50.177.242:4433`
[2023-02-03T16:22:42.777234300Z ERROR quiche_apps::client] 0.0.0.0:59319: recv failed: TlsFail
[2023-02-03T16:22:43.025517200Z ERROR quiche_apps::client] connection timed out after 296.619ms
error: process didn't exit successfully: `target\debug\quiche-client.exe https://77.50.177.242:4433` (exit code: 0xffffffff)

```

Outcome quinn's client doesn't work properly on Windows 11. I'm researching why, or maybe you know why?

**Comment by Ralith** [comment]
What does the server see? What do you see in wireshark?

**Comment by Nawy** [comment]
I fixed the problem with the server, just bind the address to 0.0.0.0 but not to 127.0.0.1 (loopback). And it works.
