### ISSUE TITLE
0-RTT key lifecycle

### ISSUE THREAD

**Issue by yushizhao** [quinn-rs/quinn#1491]
Hi team, I see 0-RTT requires a cryptographic session ticket cached. I wonder how long would a cached 0-RTT key keeps available? And  who is responsible for keeping it?

**Comment by Ralith** [comment]
That's really a TLS question, not specific to QUIC. In general, clients are responsible for storing tickets (IIRC rustls caches in-memory by default, but you might want to customize that to persist across restarts), and the server is responsible for judging when a key is expired.

**Comment by yushizhao** [comment]
Okay, so we should look for rustls API to understand and customize the behavior, right? Would you mind give a little guideline where we can tune rustls in quinn clients?

**Comment by Ralith** [comment]
Yep. See `quinn/examples/client.rs`.
