### ISSUE TITLE
timeout unexpectedly

### ISSUE THREAD

**Issue by szguoxz** [quinn-rs/quinn#1509]
Server:
`   Arc::get_mut(&mut server_config.transport)
        .unwrap()
        .max_idle_timeout(Some(quinn::VarInt::from_u32(300_000).into()))
        .keep_alive_interval(Some(Duration::from_secs(60)))
        .max_concurrent_uni_streams(255_u8.into());`

client:
`  t.max_idle_timeout(Some(quinn::VarInt::from_u32(300_000).into()))
        .keep_alive_interval(Some(Duration::from_secs(60)))
        .max_concurrent_uni_streams(255_u8.into());`
I set my time out and keep alive on server and client side. But I still get time out quite often on accept:
conn.accept_uni().await

Did I do someting wrong?

**Comment by Ralith** [comment]
The config you quoted should avoid timeouts if there are no other issues. Are you perhaps blocking a tokio thread so it can't service the connection? Does wireshark report packets on the connection within the last 300 seconds when it times out?

**Comment by Ralith** [comment]
Closing for lack of response. Feel free to reopen if you're still having this issue and can address the above questions.
