### ISSUE TITLE
0.10 release planning

### ISSUE THREAD

**Issue by djc** [quinn-rs/quinn#1528]
Time to start talking about the next semver-incompatible release, I guess?

We definitely want to wait for:

- [x] #1510 

Other things to consider:

- [x] Should we try to get #1219 in?
- [x] How do we plan for QUIC V2? (It seems to be sitting in some late part of the IETF review queue, with seemingly all the reviews done. Does this impact our public API?)

Should we consider bumping the next version to 1.0? Our API has been pretty stable...

**Comment by mxinden** [comment]
> Should we try to get https://github.com/quinn-rs/quinn/pull/1219 in?

That would be wonderful! :pray:

**Comment by Ralith** [comment]
I'd like to include mechanics for enabling MTUD automatically where supported (some sort of `PlatformConfig`?), since most users won't and shouldn't need to bother with target-specific configuration.

> How do we plan for QUIC V2?

IIRC QUIC V2 is mainly an anti-ossification measure that won't impact public API. It'd be healthy for us to have it but I don't think it's pressing. Might bear a double-check.

> Should we consider bumping the next version to 1.0?

I agree we're getting close, but if we're going to treat 1.0 as special we should probably defer a decision until we've actually not broken for a good while. Alternatively, we could abandon cosmetic concerns and just start bumping the major version without a care.

**Comment by mxinden** [comment]
> > How do we plan for QUIC V2?
> 
> IIRC QUIC V2 is mainly an anti-ossification measure that won't impact public API. It'd be healthy for us to have it but I don't think it's pressing. Might bear a double-check.

Correct, see:

> This document specifies QUIC version 2, which is identical to QUIC version 1 except for some trivial details.  Its purpose is to combat various ossification vectors and exercise the version negotiation framework.  It also serves as a template for the minimum changes in any future version of QUIC.
> 
> Note that "version 2" is an informal name for this proposal that indicates it is the second standards-track QUIC version.  The protocol specified here uses a version number other than 2 in the wire image, in order to minimize ossification risk.

https://datatracker.ietf.org/doc/draft-ietf-quic-v2/

**Comment by abonander** [comment]
> Should we consider bumping the next version to 1.0?

As long as `rustls` is part of the public API, I wouldn't recommend that.

**Comment by djc** [comment]
We should probably get #1529 in before release. I think that's probably the only thing blocking the release at this point?

**Comment by Ralith** [comment]
I think so; I should be able to review that within the next few days.

**Comment by XOR-op** [comment]
Since #1529 has been merged, should we plan to release 0.10? It looks like all the checkpoints have been resolved.

**Comment by djc** [comment]
Draft changelog:

* Initial support for PLPMTUD (#1510 with followup in #1529, thanks to aochagavia)
* Bump rustls to 0.21.0 (#1515, thanks to cpu)
* Fix: build and tests on FreeBSD 13.2 (#1555, thanks to Tirka)
* Fail FreeBSD CI if any step fails (#1557, thanks to Tirka)
* Fragmentation handling improvements (#1547)
* Add missing exports of stats types (#1546)
* Rename `min_guaranteed_mtu` to `min_mtu` for clarity (#1552)
* Duplicate `Transmit` and `EcnCodepoint` across -proto and -udp (#1541)
* quinn: take `Arc<dyn Runtime>` directly (#1534)
* Support external crypto implementations (#1496, thanks to nmittler)
* Do not require `&mut self` in `AsyncUdpSocket::poll_send` (#1519, thanks to dignifiedquire)
* Getters for stream concurrency metrics and related documentation (#1518, thanks to FlorianUekermann)
* Fallback to not using ECN if `IP_TOS` is not supported (#1516, thanks to link2xt)
* Implement fallback for `sendmmsg` and `recvmmsg` (#1504, thanks to link2xt)
* Borrow `self` in read_to_end, rather than consuming (#1502)
* Improve error when connecting with an unsupported version (#1482)
* Fix racy `Endpoint::wait_idle` (#1477)
* Re-export `udp::{RecvMeta, UdpState}` for `AsyncUdpSocket` (#1476, thanks to XOR-op)
* Route logs via `log` crate by default when `tracing` isn't used (#1473)
* Fail gracefully on attempts to connect to an unspecified IP address (#1474)
* add FreeBSD `IP_RECVDSTADDR` support (#1447, thanks to lucifer9)
* udp: add safe wrapper for `setsockopt()` (#1461)

## Documentation

* Allow initial MTU to be specified in bulk benchmark (#1456)
* Document how to close a stream correctly (#1493, thanks to flub)
* Update wording about QUIC being a draft (#1468, thanks to zicklag)
* Clarify async runtime support (#1497, thanks to mxinden)
* Fix usage message (#1484, thanks to dzvon)

# Internal improvements

* Allow benchmarking without packet protection (#1436, thanks to stormshield-damiend)
* Fix `no-protection` option in perf crate (#1550, thanks to aochagavia)
* Don't rely on sleeping in 0-RTT test (#1522)
* Update deny.toml (#1470, thanks to NukeManDan)
* Bump quinn-proto version (#1520, thanks to nmittler)
* Clippy fixes (#1466, thanks to StygianLightning)
* Bump MSRV to 1.63 (#1548)
* Bump quinn-udp version to 0.4 (#1535, thanks to link2xt)

**Comment by Ralith** [comment]
> Rename min_guaranteed_mtu to min_mtu for clarity

This is a bit confusing as a literal changelog entry because in 0.9 the parameter was called `initial_max_udp_payload_size`.

> udp: add safe wrapper for setsockopt()

This is purely internal.

LGTM otherwise!

**Comment by djc** [comment]
It's done! https://github.com/quinn-rs/quinn/releases/tag/0.10.0
