### ISSUE TITLE
Make a bugfix release of quinn-udp

### ISSUE THREAD

**Issue by link2xt** [quinn-rs/quinn#1532]
The latest release 0.3.2 does not include #1516 and because of this deltachat-core-rust is stuck patching the dependency:
https://github.com/deltachat/deltachat-core-rust/blob/cecc080931f7915dee968ab18e09c625fd2ebbe4/Cargo.toml#L28

**Comment by Ralith** [comment]
Thanks for reaching out! I don't think there's anything big to wait for here, but let's get in https://github.com/quinn-rs/quinn/pull/1533 in first to avoid future breakage.

**Comment by djc** [comment]
@link2xt if you submit a PR to bump the version number, I'll publish it soon after.

**Comment by djc** [comment]
Ahh, sorry, forgot that -udp depends on -proto. Conceptually it maybe shouldn't...

I guess we could move `EcnCodepoint` and `Transmit` over to -udp, but that would mean -proto needs to start depending on -udp, which feels not quite right? Maybe with some Cargo features to make everything except `EcnCodepoint`/`Transmit` optional?

I don't like the idea of adding another crate just for these...

**Comment by djc** [comment]
Nope, it wasn't published yet -- we proactively bumped the version when we made a semver-incompatible API change.

See #1528 for release planning.

**Comment by Ralith** [comment]
> I don't like the idea of adding another crate just for these...

I think the practical (if mildly tedious) solution is for -udp and -proto to provide independent but broadly identical definitions of these types, with quinn proper converting as needed.

**Comment by djc** [comment]
Going to close this, will release 0.4 as part of #1528.
