### ISSUE TITLE
quinn-proto: `ConnectionStats` field types are not exported

### ISSUE THREAD

**Issue by abonander** [quinn-rs/quinn#1536]
`UdpStats`, `FrameStats` and `PathStats` are not exported so their docs are not rendered:
![image](https://user-images.githubusercontent.com/3198595/232175640-0a35d4c8-0179-458d-96a0-9a145a812c0a.png)

The fields of these types are public and have doc-comments, suggesting this is just an oversight: https://github.com/quinn-rs/quinn/blob/3eb26361dba85f13b69e0eff6d934b28f70a37f8/quinn-proto/src/connection/stats.rs

**Comment by Ralith** [comment]
Yep, those should be exported; good catch.
