### ISSUE TITLE
Too much debug log

### ISSUE THREAD

**Issue by neevek** [quinn-rs/quinn#1538]
Hi, this line is repeatedly printed, it is still too much for a debug log:

```
[connection.rs:226] [D] drive; id=0
```

**Comment by Ralith** [comment]
Quinn does not print anything; that's governed by your `tracing` subscriber configuration. You should adjust that configuration not to print messages when Quinn enters a span.

**Comment by neevek** [comment]
> Quinn does not print anything; that's governed by your `tracing` subscriber configuration. You should adjust that configuration not to print messages when Quinn enters a span.

OK I'll check my settings, thanks.
