### ISSUE TITLE
Add method Connection::finish

### ISSUE THREAD

**Issue by kpp** [quinn-rs/quinn#1542]
There are methods `SendStream::{reset, finish}` but only `Connection::close`.

It would be nice to have a method `Connection::finish` to gracefully shut down the connection.

I can do that for you if want.

**Comment by djc** [comment]
What, to you, are important aspects in gracefully shutting down the connection (that `close()` does't give you today)?

**Comment by kpp** [comment]
`close()` docs:

> Pending operations will fail immediately with [ConnectionError::LocallyClosed](https://docs.rs/quinn/latest/quinn/enum.ConnectionError.html#variant.LocallyClosed). Delivery of data on un[finish](https://docs.rs/quinn/latest/quinn/struct.SendStream.html#method.finish)ed streams is not guaranteed, so the application must call this only when all important communications have been completed, e.g. by calling finish on outstanding [SendStream](https://docs.rs/quinn/latest/quinn/struct.SendStream.html)s and waiting for the resulting futures to complete.

So an important aspect is delivery of data on unfinished streams.

**Comment by Ralith** [comment]
Relying on `finish` for application-layer semantics is a bit dicey; see e.g. https://github.com/quinn-rs/quinn/issues/1487#issuecomment-1409980709. Usually it makes more sense to reason about connection state at a higher level, and only close a connection that you are logically done with. In that light, can you elaborate on the use case for this?

**Comment by djc** [comment]
Closing for lack of follow-up. Feel free to reopen if there is still something here that should be pursued.
