### ISSUE TITLE
Does it support webtransport

### ISSUE THREAD

**Issue by redoriental** [quinn-rs/quinn#1549]

**Comment by djc** [comment]
Quinn only provides a QUIC protocol implementation. As far as I know, WebTransport layers on top of HTTP/3, which in turn layers on top of QUIC. The hyper project is in the process of building a h3 crate with a h3-quinn adapter that supports running HTTP/3 over Quinn. Quinn does not provide support for HTTP/3 or WebTransport directly.

**Comment by Ralith** [comment]
WebTransport support is being actively developed within the `h3` crate. See https://github.com/hyperium/h3/issues/71, https://github.com/hyperium/h3/pull/183.

**Comment by darioalessandro** [comment]
Yes!! @ten3roberts  and I are working on it!
