### ISSUE TITLE
Question: how to set timeout of endpoint.accept()

### ISSUE THREAD

**Issue by Archieeeeee** [quinn-rs/quinn#1566]
Is there any config can be used to set timeout for server end, `max_idle_timeout` works for client

**Comment by Ralith** [comment]
Idle timeouts work the same for both endpoints, and should be used for closing the connection, not interrupting individual operations. To time out any async operation, consider a helper like [`tokio::time::timeout`](https://docs.rs/tokio/latest/tokio/time/fn.timeout.html).
