### ISSUE TITLE
Receive `Finished` flag along with data

### ISSUE THREAD

**Issue by serzhiio** [quinn-rs/quinn#1567]
As i see currently you need to call `.finish()` after all data is sent, and you need to wait for `Finished` event to be sure data stream is fully drained.
It would be more convenient, in my particular case, to receive this flag along with last portion of data, almost like WebSockets FIN flag. 
The Api could look like:
```
match recv_stream.read(false) {
  Ok(mut chunks) => {
      loop {
          match chunks.next(u16::MAX as _) {
               Ok(Some(chunk)) => {
                    callback(chunk.bytes.as_ref(), chunk.is_fin())
               }
               ...
          }
      }
}
```

**Comment by Ralith** [comment]
`Chunks::next` returns `Ok(None)` when you've reached the end of the stream.

**Comment by serzhiio** [comment]
Yeah, but if i wait for this extra event i need to cache all stream data even if there is only one chunk.
And when receiving data with `fin:true` flag i can parse it without caching bc i know i don't have to wait.

**Comment by Ralith** [comment]
Your code needs to handle data being delivered in arbitrary chunks regardless.
