### ISSUE TITLE
Unable to bind IPv6 socket on cross aarch64-linux-android

### ISSUE THREAD

**Issue by dignifiedquire** [quinn-rs/quinn#1568]
Currently running through some tests, and it looks like IPv6 is broken on my cross builds. I checked the flags and the offender is the `IPV6_DONTFRAG`,  which results in 

```
set_socket_option(&socket, libc::IPPROTO_IPV6, libc::IPV6_DONTFRAG, 1) = Err(
    Os {
        code: 92,
        kind: Uncategorized,
        message: "Protocol not available",
    },
)
```

**Comment by dignifiedquire** [comment]
I am not entirely sure: https://github.com/cross-rs/cross#supported-targets is the relevant docs. I believe this executes in Qemu.

**Comment by Ralith** [comment]
Do you know what the minimum kernel version you actually intend to support is? We could just look up the status of `IPV6_DONTFRAG` on whatever that is.

If indeed a kernel you need to support lacks that socket option, `quinn_udp::may_fragment()` should be modified to return `true` in that environment (perhaps by attempting it on a dummy socket) and we should skip the call.

**Comment by Arqu** [comment]
An overview of that environment:
```
- Env: github actions runner
- OS: Ubuntu 22.04.02
- Kernel: 5.15.0-1037-azure
- Cargo/Rust: 1.69.0
- Lowest android kernel: 3.14.0
- Tested android kernel: 4.15 (I think)
```

Since this is like 5 layers deep with cross (docker) + qemu (android) + whatever android version combo it's a bit hard to track all of it down, but the min kernel version for the android stuff we want to run is 3.14.0. However this is a lot more complicated since there are no kernel version guarantees for any given android version running on a device, mostly just rule of thumb based on what the "core release" included.

**Comment by Ralith** [comment]
Strange, `IPV6_DONTFRAG` seems to be supported since at least 3.0: https://elixir.bootlin.com/linux/v3.0/source/net/ipv6/ipv6_sockglue.c#L802

What address was the socket that gave you that error bound to?

**Comment by dignifiedquire** [comment]
> What address was the socket that gave you that error bound to?

https://doc.rust-lang.org/nightly/std/net/struct.Ipv6Addr.html#associatedconstant.LOCALHOST

**Comment by dignifiedquire** [comment]
I also tested setting all the flags except `DONTFRAG` and then it works without any issues.

**Comment by Ralith** [comment]
Thanks. I'm very confused by why that would fail, but I'd be happy to merge a mitigation as outlined above.

**Comment by Ralith** [comment]
Weird, I thought we bound before setting any socket options? Anyway, thanks for investigating.

**Comment by flub** [comment]
> Weird, I thought we bound before setting any socket options? Anyway, thanks for investigating.

We are doing some unusual things where we make our own `AsyncUdpSocket` which is backed by 3 different real sockets to enable us to do holepunching.  So we're to blame ourselves for the weird order things happen in.
