### ISSUE TITLE
Guide book says to use cert.pem when using certbot certficates, which causes the error: "invalid peer certificate: UnknownIssuer"

### ISSUE THREAD

**Issue by DontBreakAlex** [quinn-rs/quinn#1573]
Hi !

I just spend two hours diagnosing why `endpoint.connect(...)` was returning `TransportError(Error { code: Code::crypto(30), frame: None, reason: "invalid peer certificate: UnknownIssuer" })`.

It turns out I had written:
```Rust
let mut cert_chain_reader = BufReader::new(File::open("/etc/letsencrypt/live/pepito.mom/cert.pem")?);
```
When I needed:
```Rust
let mut cert_chain_reader = BufReader::new(File::open("/etc/letsencrypt/live/pepito.mom/fullchain.pem")?);
```

The [guide book](https://quinn-rs.github.io/quinn/quinn/certificate.html) says:

> certbot asks for the required data and writes the certificate to cert.pem and the private key to privkey.pem. These files can then be referenced in code.

Am I doing something wrong or should the guide book be updated ?

Thanks !

**Comment by djc** [comment]
Sorry about that! The book is wrong, would you be able to send a PR?

**Comment by DontBreakAlex** [comment]
Will do !
