### ISSUE TITLE
README.md says "see for usage" instead of "see examples for usage"

### ISSUE THREAD

**Issue by kettle11** [quinn-rs/quinn#1592]
This line mistakingly reads "see for usage": https://github.com/quinn-rs/quinn/blob/790ff720a9db4b8515792a7e05fdb54a8a30e54c/README.md?plain=1#L27

But looking at the history it appears it used to say "see Quinn/examples for usage" with a link to the examples.

**Comment by djc** [comment]
Thanks for reporting, want to send a PR?

**Comment by kettle11** [comment]
@djc Done! 

Here it is: https://github.com/quinn-rs/quinn/pull/1594
