### ISSUE TITLE
`Endpoint`s with default config allocate too much memory on creation

### ISSUE THREAD

**Issue by cairijun** [quinn-rs/quinn#1608]
Memory usage (RSS) of our app surges to hunders of MB in a few minutes after startup when building with quinn 0.10.1, comparing to ~50MB with quinn 0.9.X. With [dhat](https://crates.io/crates/dhat) we noticed large memory allocations during the creation `Endpoint`s:
![image](https://github.com/quinn-rs/quinn/assets/1297550/4c4fc083-efae-4a47-9898-1bcf7ff997f0)

We suspect [this commit](https://github.com/quinn-rs/quinn/pull/1529/commits/1c53b42056d5397ffb45d065d71f5d79fa1d071a), which increased the max udp payload size to 64KB, combining with the `recv_buf` size calculation,

https://github.com/quinn-rs/quinn/blob/0ae7c60b15637d7343410ba1e5cc3151e3814557/quinn/src/endpoint.rs#L673-L678

might be the root cause. On a GRO-enabled kernel we have [`udp_state.gro_segments() == 64`](https://github.com/quinn-rs/quinn/blob/0ae7c60b15637d7343410ba1e5cc3151e3814557/quinn-udp/src/unix.rs#L775), and [`BATCH_SIZE == 32`](https://github.com/quinn-rs/quinn/blob/0ae7c60b15637d7343410ba1e5cc3151e3814557/quinn-udp/src/unix.rs#L703), resulting in a 128MB `recv_buf` for each `Endpoint`.

**Comment by Ralith** [comment]
Thanks for the report! I agree that's unreasonably large. Using a constant `BATCH_SIZE` regardless of GRO does not make sense, and fixing that should address the bulk of the problem. We should probably not allocate 64KiB of buffer per packet, either, though it's not immediately obvious how to reduce that in the common case without imposing an otherwise unnecessary ceiling on PTMUD.

**Comment by mahkoh** [comment]
>Memory usage (RSS) of our app surges to hunders of MB in a few minutes after startup when building with quinn 0.10.1, comparing to ~50MB with quinn 0.9.X. 

Do you have overcommit disabled? `vec![0; LARGE]` will not actually put anything into RSS if overcommit is enabled. Or do you actually receive 64KB datagrams? If your MTU is 1500 or even 9000, most of the pages should never be touched and therefore never be put into RSS.

**Comment by Ralith** [comment]
For visibility: a fix for this has been published in 0.10.2.
