### ISSUE TITLE
Expose more `quinn-udp` UdpState properties

### ISSUE THREAD

**Issue by Icelk** [quinn-rs/quinn#1609]
In the implementation of `quinn-udp` (I'm focusing on [UNIX/Linux](https://github.com/quinn-rs/quinn/blob/main/quinn-udp/src/unix.rs)), the following properties/methods on `UdpState` are used:

- `state.max_gso_segments.store`
- `state.set_sendmsg_einval()`
- `state.sendmsg_einval()`

They are ~required~ recommended when implementing one's own `AsyncUdpSocket`. Exposing them would enable more correct external implementations.

I can make a PR if you'd like :)

**Comment by djc** [comment]
What's your use case?

**Comment by Icelk** [comment]
Implementing AsyncUdpSocket for tokio-uring.

**Comment by djc** [comment]
Makes sense, happy to take a look at a PR!
