### ISSUE TITLE
FrameStats: cannot find documentation on the values

### ISSUE THREAD

**Issue by grooviegermanikus** [quinn-rs/quinn#1617]
Hi. I really love your library and want to get more insights using the _Stats_ feature.
Yet I did not find a documentation on for example [FrameStats](https://docs.rs/quinn-proto/latest/quinn_proto/struct.FrameStats.html).

Would you mind provide descriptions of each field?

Thanks a lot!

**Comment by djc** [comment]
The documentation mentions that these are the "[n]umber of frames transmitted of each frame type" -- each field maps to a frame type as described in https://www.rfc-editor.org/rfc/rfc9000.html#name-frame-types-and-formats.

**Comment by grooviegermanikus** [comment]
sure makes sense !! thanks a lot
