### ISSUE TITLE
quicwg out of date

### ISSUE THREAD

**Issue by zzwxh** [quinn-rs/quinn#1618]
https://github.com/quicwg/base-drafts/wiki/Implementations

i found quinn only support draft28

**Comment by djc** [comment]
I updated it a bit, thanks for reporting.

**Comment by zzwxh** [comment]
Protocol IDs: 0xff00001c
you believe this is correct
quic v1 has a id of 0x1

**Comment by djc** [comment]
I've removed the protocol IDs, I don't think they're useful as we don't have a public server right now anyway.

**Comment by zzwxh** [comment]
fn interpret_version(version: u32) -> Result<Version, UnsupportedVersion> {
    match version {
        0xff00_001d..=0xff00_0020 => Ok(Version::V1Draft),
        0x0000_0001 | 0xff00_0021..=0xff00_0022 => Ok(Version::V1),
        _ => Err(UnsupportedVersion),
    }
}
you says quinn support quic v2
