### ISSUE TITLE
Protocol not available (os error 42)

### ISSUE THREAD

**Issue by jieliangma** [quinn-rs/quinn#1624]
version: 0.10.2
device: iPhone SE2, iOS 13.6.1
`quinn::Endpoint::client("0.0.0.0:0".parse()?)?` got an error: Protocol not available (os error 42)

**Comment by djc** [comment]
That's pretty strange. Can you dig into the code inside `Endpoint::client()` and see which call is failing? Is it the `UdpSocket::bind()`, something in `quinn_udp::unix::init()` (called by `wrap_with_socket()`)? We have had people use the library on iOS before so it should work but maybe the version you have is too old. Have you tried earlier versions?

**Comment by jieliangma** [comment]
in file src/unix.rs 
```
    #[cfg(any(target_os = "freebsd", target_os = "macos", target_os = "ios"))]
    {
        if is_ipv4 {
            set_socket_option(&*io, libc::IPPROTO_IP, libc::IP_DONTFRAG, OPTION_ON)?; //  this line error
        }
    }
```

**Comment by djc** [comment]
Yup, that's it. So we'll probably want to ignore this particular error value here, at least for macOS?
