### ISSUE TITLE
BBR v3 support?

### ISSUE THREAD

**Issue by moranno** [quinn-rs/quinn#1630]
Google has release BBR v3: https://github.com/google/bbr/tree/v3

Which has a lot of improvement: https://www.phoronix.com/news/Google-BBRv3-Linux

Hoping quinn's BBR v3 support is underway.

**Comment by Ralith** [comment]
We're not actively working on this. Contributions to implement v3 would be very welcome!

**Comment by Ralith** [comment]
See #1254.
