### ISSUE TITLE
Automatic Retry heuristics

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#1661]
[QUIC's Retry mechanism](https://www.rfc-editor.org/rfc/rfc9000.html#name-address-validation-using-re) is (primarily) a defense against resource exhaustion attacks by forcing peers to prove that they can receive packets sent to their address before allocating connection state. It is not the default mode because it costs an additional round-trip of latency. Quinn currently requires Retry only at the application's explicit request, but applications are unlikely to make effective use of this in practice. To provide more robustness by default, we should automatically enable Retry whenever the number of incoming connections whose address has not yet been validated is above some (proportionate?) threshold.

**Comment by Ralith** [comment]
Luke Curley of quicdev argues that enabling Retry is only useful if some mechanism exists to block malicious IPs, because an attacker can just as well use their real IP(s). A more general solution might therefore be to provide an API that allows the application to accept/reject/require retry on a connection before the handshake begins. This might not be of much use outside of the most advanced users, but at least it will be effective for them.

**Comment by djc** [comment]
> A more general solution might therefore be to provide an API that allows the application to accept/reject/require retry on a connection before the handshake begins. This might not be of much use outside of the most advanced users, but at least it will be effective for them.

Sounds good to me!

**Comment by VinTarZ** [comment]
I have made such api as part of fork with DoS mitigation for my online game, https://github.com/VinTarZ/quinn/tree/0.10.x

**Comment by gretchenfrage** [comment]
I am working on this :) once I have more of a working prototype made I will ask for feedback on API design in the Matrix server.
