### ISSUE TITLE
Question: Why the conntion is closed after RecvStream.read_buf()

### ISSUE THREAD

**Issue by Zhou-Pixel** [quinn-rs/quinn#1673]
# Code
![图片](https://github.com/quinn-rs/quinn/assets/72525794/a99c14ce-eed0-4bc9-ace8-46a2ddc98eed)

# Result
![图片](https://github.com/quinn-rs/quinn/assets/72525794/bf69da88-73c6-4b6e-928e-d28c5a6d5e36)

**Comment by Zhou-Pixel** [comment]
> Did you read the documentation for `ConnectionError::ApplicationClosed`?

Yes, I do.
The strange thing is why there is no problem reading and writing the first time, but it fails the second time, at the same time, the error_code is 0 and The reason is empty. It seems that the connection was closed manually, but I didn't close it.

**Comment by Ralith** [comment]
You didn't; your peer did.

**Comment by Zhou-Pixel** [comment]
> You didn't; your peer did.

My mistake, I forgot that quic is a stream and I need to deal with the problem of sticky packets, so when the server cannot serialize the Json text, it shuts down.

**Comment by Zhou-Pixel** [comment]
> You didn't; your peer did.

Thanks
