### ISSUE TITLE
Accept's Future Output 

### ISSUE THREAD

**Issue by jxs** [quinn-rs/quinn#1676]
[`Accept`'s](https://docs.rs/quinn/0.10.2/quinn/struct.Accept.html) `Future` `Output` is `Option<Connecting>`, yielding `None` when the endpoint is [closed](https://docs.rs/quinn/0.10.2/quinn/struct.Endpoint.html#method.close). 

`None` can be returned in two situations:
- [`endpoint.driver_lost` ](https://github.com/quinn-rs/quinn/blob/e1e1e6e392a382fbded42ca010505fecb8fe3655/quinn/src/endpoint.rs#L644) is `true`
- [`endpoint.state.connections.is_some()`](https://github.com/quinn-rs/quinn/blob/e1e1e6e392a382fbded42ca010505fecb8fe3655/quinn/src/endpoint.rs#L650-L652) is `true`.

When an [`Endpoint`](https://docs.rs/quinn/0.10.2/quinn/struct.Endpoint.html) is created it spawns the `EndpointDriver` which its futures ["terminate when all clones of the `Endpoint` have been dropped, or when an I/O error occurs"](https://github.com/quinn-rs/quinn/blob/e1e1e6e392a382fbded42ca010505fecb8fe3655/quinn/src/endpoint.rs#L306-L307).

In both this situations `EndpointDriver` sets `Endpoint`'s `driver_lost` to `true`, which if I understand correctly doesn't allow distinguishing betwen a graceful and an abrupt connection right?

If so can we introduce a mechanism to distinguish both situations and then allow `Accept`'s `Future` to be `Option<Result<Connection>>` to also let the end user acknowledge when the `Endpoint` was properly closed to when was not?

I can to submit a PR addressing this if accepted.

Thanks

**Comment by Ralith** [comment]
Did you see [`Connection::close_reason`](https://docs.rs/quinn/latest/quinn/struct.Connection.html#method.close_reason)?

**Comment by Ralith** [comment]
Oh, sorry, you're looking at `Endpoint::accept`, not `Connection::accept_*`. That will only return `None` if you call `Endpoint::close` yourself. Any other behavior is a serious Quinn bug.

**Comment by jxs** [comment]
ok, thanks for clarifying!
