### ISSUE TITLE
Should "discarding possible duplicate packet" really be a warning?

### ISSUE THREAD

**Issue by nazar-pc** [quinn-rs/quinn#1704]
We recently deployed QUIC support in libp2p-based networking stack and started getting annoying number of these messages:
```
2023-11-06T21:44:38.016589Z  WARN quinn_proto::connection: discarding possible duplicate packet
```

I'm now wondering if those are supposed to be warnings? Looks like debug message to me if those are the duplicates of the the same kind I suspect they are (not familiar with the codebase yet unfortunately).

**Comment by Ralith** [comment]
What kind do you suspect they are?

Duplicate packets can be an indication of some forms of attack. I'm guessing what you're seeing is some network path element causing that instead, which I hadn't anticipated being common. Since it seems like it is for you, I'm open to reducing the severity. Want to make a quick PR?

**Comment by nazar-pc** [comment]
> What kind do you suspect they are?

General retransmissions for UDP protocols since there are no guarantees about the delivery, I'm guessing there is some kind of timeout and if there is no confirmation packet will be sent again that receiving side will rightfully consider to be a duplicate.

> Want to make a quick PR?

Sure!

**Comment by Ralith** [comment]
> General retransmissions for UDP protocols since there are no guarantees about the delivery

Neither UDP itself nor QUIC operate this way. UDP doesn't care about delivery at all, and QUIC retransmits information, not packets. It's got to be something in between that's cloning packets. I think wifi's link-layer recovery might be a risk for that?

**Comment by nazar-pc** [comment]
> QUIC retransmits information, not packets

I see, thanks! My understanding of QUIC is close to zero.

We have a distributed network and no control over what users are running software on, so anything is possible and messages usually arrive in bursts of varying size.
