### ISSUE TITLE
I saw no advantage to download speed compared to a simple python http tcp server

### ISSUE THREAD

**Issue by shiqifeng2000** [quinn-rs/quinn#1712]
By using the example client/server, I am testing a bidirectional connection and transfer a video, 

But using python simple http server speed is 100M/s

by using the example client, the download speed is 69M/s

May i have some explanation about the speed?

**Comment by djc** [comment]
Does your simple HTTP server setup include TLS? If not, it's not a fair comparison.

**Comment by Ralith** [comment]
You also shouldn't expect QUIC to *improve* performance for simple linear data transfers under ideal network conditions. QUIC provides improved multiplexing, security, and recovery behavior, but can't easily improve on what TCP is already great at.

**Comment by shiqifeng2000** [comment]
> You also shouldn't expect QUIC to _improve_ performance for simple linear data transfers under ideal network conditions. QUIC provides improved multiplexing, security, and recovery behavior, but can't easily improve on what TCP is already great at.

I'm told the quic uses multiplexing for transfering, so if I download 2 or more, the performance maybe better?

Or is it because using fec redundant packeting here drag down the speed?

**Comment by shiqifeng2000** [comment]
> Does your simple HTTP server setup include TLS? If not, it's not a fair comparison.



> Does your simple HTTP server setup include TLS? If not, it's not a fair comparison.

![Screenshot from 2023-11-29 14-56-36](https://github.com/quinn-rs/quinn/assets/9416410/cbd4c589-56f9-4a27-a611-ba5d6d07bf40)

**Comment by Ralith** [comment]
> I'm told the quic uses multiplexing for transfering, so if I download 2 or more, the performance maybe better?

No. Your link's capacity is fixed.

> Or is it because using fec redundant packeting here drag down the speed?

FEC is not part of QUIC.

> which scenario is best for the quic

Consider using QUIC when TCP's limitations are causing you specific problems.

**Comment by jaketakula** [comment]
hey @shiqifeng2000,
all quick impls will in some degrees slower than tls1.3+tcp.
pls take a look at this good article for details and how to speed it up.
you can use tcp in local network abd quic in network gateways.

https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency

**Comment by shiqifeng2000** [comment]
> hey @shiqifeng2000, all quick impls will in some degrees slower than tls1.3+tcp. pls take a look at this good article for details and how to speed it up. you can use tcp in local network and quic in network gateways.
> 
> https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency

thank you, i will take a good look

**Comment by shiqifeng2000** [comment]
> > hey @shiqifeng2000, all quick impls will in some degrees slower than tls1.3+tcp. pls take a look at this good article for details and how to speed it up. you can use tcp in local network and quic in network gateways.
> > https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency
> 
> thank you, i will take a good look

![image](https://github.com/quinn-rs/quinn/assets/9416410/f04f5f89-d070-42c1-8375-b078cc60a6f6)
it seems the author has heavily optimized the transportation, they are
1. ack delay
2. gso
3. package increase

regarding our code, is there anything I can do to follow the suggestion above?
I tried to add some test code, but no effect, here's the code

    **let mut server_config = quinn::ServerConfig::with_crypto(Arc::new(server_crypto));
    let transport_config = Arc::get_mut(&mut server_config.transport).unwrap();
    transport_config.max_concurrent_uni_streams(0u8.into());
    let mut acks = quinn::AckFrequencyConfig::default();
    acks.ack_eliciting_threshold(10u32.into());
    transport_config.ack_frequency_config(Some(acks));
    transport_config.enable_segmentation_offload(true);**

**Comment by shiqifeng2000** [comment]
> hey @shiqifeng2000, all quick impls will in some degrees slower than tls1.3+tcp. pls take a look at this good article for details and how to speed it up. you can use tcp in local network and quic in network gateways.
> 
> https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency

> > hey @shiqifeng2000, all quick impls will in some degrees slower than tls1.3+tcp. pls take a look at this good article for details and how to speed it up. you can use tcp in local network and quic in network gateways.
> > https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency
> 
> thank you, i will take a good look

![image](https://github.com/quinn-rs/quinn/assets/9416410/f04f5f89-d070-42c1-8375-b078cc60a6f6)
it seems the author has heavily optimized the transportation, they are
1. ack delay
2. gso
3. package increase

regarding our code, is there anything I can do to follow the suggestion above?
I tried to add some test code, but no effect, here's the code

    **let mut server_config = quinn::ServerConfig::with_crypto(Arc::new(server_crypto));
    let transport_config = Arc::get_mut(&mut server_config.transport).unwrap();
    transport_config.max_concurrent_uni_streams(0u8.into());
    let mut acks = quinn::AckFrequencyConfig::default();
    acks.ack_eliciting_threshold(10u32.into());
    transport_config.ack_frequency_config(Some(acks));
    transport_config.enable_segmentation_offload(true);**

**Comment by shiqifeng2000** [comment]
> hey @shiqifeng2000, all quick impls will in some degrees slower than tls1.3+tcp. pls take a look at this good article for details and how to speed it up. you can use tcp in local network and quic in network gateways.
> 
> https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency

hi @jaketakula 

> > hey @shiqifeng2000, all quick impls will in some degrees slower than tls1.3+tcp. pls take a look at this good article for details and how to speed it up. you can use tcp in local network and quic in network gateways.
> > https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency
> 
> thank you, i will take a good look

![image](https://github.com/quinn-rs/quinn/assets/9416410/f04f5f89-d070-42c1-8375-b078cc60a6f6)
it seems the author has heavily optimized the transportation, they are
1. ack delay
2. gso
3. package increase

regarding our code, is there anything I can do to follow the suggestion above?
I tried to add some test code, but no effect, here's the code

    **let mut server_config = quinn::ServerConfig::with_crypto(Arc::new(server_crypto));
    let transport_config = Arc::get_mut(&mut server_config.transport).unwrap();
    transport_config.max_concurrent_uni_streams(0u8.into());
    let mut acks = quinn::AckFrequencyConfig::default();
    acks.ack_eliciting_threshold(10u32.into());
    transport_config.ack_frequency_config(Some(acks));
    transport_config.enable_segmentation_offload(true);**

**Comment by Ralith** [comment]
What OS are you on? Did you adjust the ACK frequency config on the client as well? What's your CPU load? Have you tried messing with the MTU? Have you profiled?

**Comment by shiqifeng2000** [comment]
> What OS are you on? Did you adjust the ACK frequency config on the client as well? What's your CPU load? Have you tried messing with the MTU? Have you profiled?

ubuntu 22, 

the code in testing is ack adjusting, I assume?
**let mut acks = quinn::AckFrequencyConfig::default();
acks.ack_eliciting_threshold(10u32.into());**

CPU 8 core, it takes about 160%, cpu model is **Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz**, I found mtu mutiple fields so did not try yet. Yes, I have profiled.

The transporting reached 200M~250M, just for 1 bi-transportation, that's very close to the **ack 10** part. 
The Gso part, I find only the **enable_segmentation_offload** api, and it claims

    /// GSO dramatically reduces CPU consumption when sending large numbers of packets with the same
    /// headers, such as when transmitting bulk data on a connection. However, it is not supported
    /// by all network interface drivers or packet inspection tools. `quinn-udp` will attempt to
    /// disable GSO automatically when unavailable, but this can lead to spurious packet loss at
    /// startup, temporarily degrading performance.

by further digging, that part should be **gso10**
/// This can be lower than the maximum platform capabilities, to avoid excessive
/// memory allocations when calling `poll_transmit()`. Benchmarks have shown
/// that numbers around 10 are a good compromise.
const MAX_TRANSMIT_SEGMENTS: usize = 10;

that should at least lift me to 348M, maybe this is close? but the client side do not support customizing transportation setting config, or say, directly.
![image](https://github.com/quinn-rs/quinn/assets/9416410/f3a2d70e-2984-448f-a7e2-e5f72e60d3ff)

![image](https://github.com/quinn-rs/quinn/assets/9416410/b4d9b2e5-2a3c-420b-ba7f-f037caa39f53)

by changing the quinn code to enable client transport setting, client speed rises.
![image](https://github.com/quinn-rs/quinn/assets/9416410/5248e5ae-d52a-486c-b13d-d53d8d964d41)

by changing MAX_TRANSMIT_SEGMENTS to 20, no effecting, maybe there's other cap setting to limit speed in quinn.

![image](https://github.com/quinn-rs/quinn/assets/9416410/1900794e-7906-4c7c-b496-edfc63d4bc37)

and as for mtu, there's 3 field in transport config, 
            **initial_mtu: INITIAL_MTU,
            min_mtu: INITIAL_MTU,
            mtu_discovery_config: Some(MtuDiscoveryConfig::default()),**
by changing **INITIAL_MTU** to 1460, it seems a little bit rising, but the speed is unsable, so not sure

Really hope quinn could provide some 'official tutorial' for speeding up the transfering

**Comment by Ralith** [comment]
> Yes, I have profiled.

What did the profiler tell you?

> The transporting reached 200M~250M

I thought you said you were getting "69M"? It's not clear if you're talking about MiB/s, MB/s, Mb/s or something else. Please label your units completely and consistently.

> The Gso part, I find only the enable_segmentation_offload api, and it claims

GSO is enabled by default when available. That API is only useful for turning it off when in a broken environment.

> but the client side do not support customizing transportation setting config

Yes, it does. See [`ClientConfig::transport_config`](https://docs.rs/quinn/latest/quinn/struct.ClientConfig.html#method.transport_config).

> by further digging, that part should be gso10

`MAX_TRANSMIT_SEGMENTS` is not related to GSO. GSO is enabled by default.

> and as for mtu, there's 3 field in transport config,

Increasing both `initial_mtu` and `min_mtu` is the best bet for testing. Many overheads in QUIC are per-packet, so this should give a reliable speedup for long-running bulk data transfers. Exercise caution raising `min_mtu` in production, for obvious reasons.

> Really hope quinn could provide some 'official tutorial' for speeding up the transfering

Quinn's default settings are tuned for a good balance of performance and reliability on a 100Mbps internet link. If there was a simple button to push to make it faster, that would be the default.

**Comment by shiqifeng2000** [comment]
my bad to confuse the unit. at first, I use the '**69M/s'** is byte, then the later unit are of '**Mbps**' since I read the topic and follow his unit, thats bits. The 69M/s means 480~560Mbps transportation, that's pretty fast according to the topic I read. So the speed is optimized by default?

by profiling, I mean I have tested and recorded the speed, suggest me if I need some tool to support the data

> ClientConfig::transport_config

Well, there is, but need to replace with new ones every time, it will be nicer if just use the previous one for updating

The later testing is based on bi-transportation,  both server and client try to send large data to each other, maybe that's the reason that drag down the speed, will test more
