### ISSUE TITLE
how to obtain the num of lost packet in congestion controller

### ISSUE THREAD

**Issue by eauxxs** [quinn-rs/quinn#1732]
Can only lost_bytes be obtained?

**Comment by Ralith** [comment]
That's not currently exposed to congestion controllers (though a running total is exposed to applications via `ConnectionStats`), but if you have a compelling use case you could add it pretty easily by passing `lost_packets.len()` down in `Connection::detect_lost_packets`.

**Comment by Ralith** [comment]
Closing for lack of response. Feel free to reopen if further discussion is required.
