### ISSUE TITLE
0.11.0 release planning

### ISSUE THREAD

**Issue by djc** [quinn-rs/quinn#1737]
Blocking issues:

- [x] https://github.com/quinn-rs/quinn/pull/1729
- [x] https://github.com/quinn-rs/quinn/pull/1734
- [x] https://github.com/quinn-rs/quinn/pull/1715
- [x] https://github.com/quinn-rs/quinn/pull/1821

We might want to try to push these over the finish line:

- [ ] https://github.com/quinn-rs/quinn/pull/1703
- [x] https://github.com/quinn-rs/quinn/pull/1840
- [x] https://github.com/quinn-rs/quinn/pull/1692

**Comment by Ralith** [comment]
I think #1729 subsumes #1692, since you'll no longer need heap allocation to transform `Transmit`s.

**Comment by complexspaces** [comment]
I don't know if `rustls-native-certs` ever supported Android (it seems like it [didn't](https://github.com/rustls/rustls-native-certs/issues/3)?), but it might be worth adding a small section to the README redirecting to the Android setup section of `rustls-platform-verifier` now if you anticipate Android users.

**Comment by Ralith** [comment]
We've had a few of those; good thought.

**Comment by gabrik** [comment]
is there any ETA for this?

**Comment by djc** [comment]
There is not -- if your project depends on it, please consider [sponsoring](https://opencollective.com/quinn-rs).

**Comment by gabrik** [comment]
I can help on #1715 if needed

**Comment by djc** [comment]
Sure, if you want to finish up my WIP commit there to get it to compile, addressing the open comments, and do the same thing for the server side, that would be welcome.

**Comment by djc** [comment]
We should also consider:

- #1740 (includes semver-incompatible changes)
- #1816 (includes semver-incoompatible changes)

And would be nice to include these:

- #1801 (no semver-incompatible changes)
- #1790 (no semver-incompatible changes)

**Comment by djc** [comment]
@flub recently discussed some benchmarking results in https://github.com/quinn-rs/quinn/pull/1729#issuecomment-2021022434 which indicate that there might be a performance regression on main compared to 0.10. @flub would you be able to run something like a bisection to figure out what regressed performance? @lijunwangs do you have a setup for benchmarking changes? Would be good to make sure there are no surprises.

**Comment by lijunwangs** [comment]
We don’t have solid Quinn performance test tool. But I do confirm that when I applied the main branch based code into a test environments where ~300k pps are going on, I did noticed increased packet processing time measured from the first chunk received until the last chunk is received. We have fixed max packet size about 1232 bytes in our application. And I also noticed increased stream read timeout during that. So we do need to investigate the performance impacts

**Comment by flub** [comment]
> @flub recently discussed some benchmarking results in [#1729 (comment)](https://github.com/quinn-rs/quinn/pull/1729#issuecomment-2021022434) which indicate that there might be a performance regression on main compared to 0.10. @flub would you be able to run something like a bisection to figure out what regressed performance?

Yes, I still intend to do some followup on this.  A straight bissection is a bit tricky right now since I can't drive our perf infra from the cli currently but have to go via commits and github actions.  But I'll see what we can do.

It may take some time though, do you have any rough dates in mind I should be aware off?

**Comment by djc** [comment]
Probably a few more days until release, but could perhaps hold it if that helps.

**Comment by gretchenfrage** [comment]
Probably is important to push through #1821 before release, right? Because it fixes a bug which did not exist in the previous release.

**Comment by Ralith** [comment]
Yep, that's a blocker.

**Comment by flub** [comment]
Apologies for taking a while, I've made some attempts at bisecting the performance regression and can't really identify anything reproducible and certain enough.  The only path remaining for me is to bisect with porting our entire stack to each commit in the bisection.  This is maybe not as much work as I fear, but also I'm entirely out of time to spend on this for now.

The good news for you however is that I can't really observe this in isolation in just Quinn.  So it probably is something affecting the way we (ab)use Quinn in our stack, which is something not as concerning for holding up your release.

**Comment by XerneraC** [comment]
Is there an update on this? By the looks of it, everything that blocked this has been resolved.

**Comment by djc** [comment]
I think the current state is that @Ralith is looking into fixing #1803. Not sure how likely that is to include breaking API changes?

**Comment by Ralith** [comment]
https://github.com/quinn-rs/quinn/issues/1803 should be completely invisible to the public API, so it doesn't need to block. I do think I can wrap it up this week, though, so it might be nice to snag it anyway.

**Comment by djc** [comment]
* Published quinn-udp v0.5.0 at registry `crates-io`
* Published quinn-proto v0.11.0 at registry `crates-io`
* Published quinn v0.11.0 at registry `crates-io`
* Pushed a 0.11.0 tag
