### ISSUE TITLE
poll send datagram

### ISSUE THREAD

**Issue by devsnek** [quinn-rs/quinn#1738]
I'd like to wait for free space in the datagram outgoing queue, instead of silently dropping other datagrams. In my mind, `send_datagram` should return a future you can poll, but that would replace the existing behavior which drops them. Would it be okay to do so? Or would it be better to add a new function like `poll_wait_for_datagram_queue_available(len)`?

**Comment by Ralith** [comment]
We had this in the past; see https://github.com/quinn-rs/quinn/pull/555 for discussion. It sounds like both behaviors are desirable in different cases. I'm not opposed to having APIs to support both (especially as `tokio::Notify` makes multi-waiter APIs much easier than they were in the past), but we shouldn't lose the current functionality.

A few notes to consider:
- A future to wait for buffer space would be a nice minimal extension to the current API, but is racy if multiple threads are sending. It'd need to be paired with a send operation that fails when blocked if you want to ensure data is never dropped.
- There is no benefit to waiting for buffer space except when the connection is congestion-bound.
- Blocking queueing of new datagrams de-facto prioritizes old datagrams. This is usually not desired.
