### ISSUE TITLE
Add Connection::is_closed method

### ISSUE THREAD

**Issue by jean-airoldie** [quinn-rs/quinn#1780]
## Problem

Multiple threads are using the same connection when the connection dies. All the threads race to restore the connection, potentially, reconnecting multiple times.

## Solution

Put the connection behind a RwLock, acquire the writer lock, check if the connection is closed via `is_closed` method, if it is, reconnect. This way the reconnection happens at most once.

**Comment by Ralith** [comment]
See [`Connection::close_reason`](https://docs.rs/quinn/latest/quinn/struct.Connection.html#method.close_reason).
