### ISSUE TITLE
Add riscv64 Support 

### ISSUE THREAD

**Issue by liberodark** [quinn-rs/quinn#1812]
Hi,

Have build issue related to ring from : 
https://gitlab.com/veloren/veloren/-/issues/1972
More info : 
https://paste.yunohost.org/opecoqopep.vbs
Also i can give you access on risc-v if you need.

**How to build :** 

```
#!/bin/bash

apt install -y git curl
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
git clone https://github.com/quinn-rs/quinn
cd quinn
source "$HOME/.cargo/env"
cargo build --release
```

Fail with `ring 0.16.7`
Work with `ring 0.17.8`

Best Regards

**Comment by djc** [comment]
Can you try with #1715?

**Comment by liberodark** [comment]
@djc no have make PR to fix that.

**Comment by djc** [comment]
@liberodark ring is a public dependency for us so upgrading it is not a trivial matter of just bumping the version. You'll have to wait for the PR to be merged (which is now ready for review -- it shouldn't be too long) just like everyone else.

**Comment by liberodark** [comment]
No problem im go to wait for that thank for your reply.
