### ISSUE TITLE
Is there a heartbeat mechanism?

### ISSUE THREAD

**Issue by redoriental** [quinn-rs/quinn#1817]
"I need to be immediately aware when the other party is offline.

**Comment by Ralith** [comment]
See [`TransportConfig::keep_alive_interval`](https://docs.rs/quinn/latest/quinn/struct.TransportConfig.html#method.keep_alive_interval), [`TransportConfig::max_idle_timeout`](https://docs.rs/quinn/latest/quinn/struct.TransportConfig.html#method.max_idle_timeout).
