### ISSUE TITLE
Debug formatting could be improved

### ISSUE THREAD

**Issue by gretchenfrage** [quinn-rs/quinn#1822]
For example, when trying to print a `quinn::Endpoint`, when it gets to `recv_buf`, it just prints a list of many many integers with little discernible meaning. Possibly would be worth looking for a crate that enhances derive debugging with the ability to attribute structs with fields to ignore rather than doing it manually.

**Comment by djc** [comment]
I don't think we want to drag in an additional dependency for this. But having a manual `Debug` impl that's more discerning than whatever we've got now would probably be helpful!

**Comment by gretchenfrage** [comment]
The thing about `recv_buf` specifically was fixed in #2081. Beyond that, I figure this issue is probably too broad to ever say "we're done", so I'm going to close it, and just say, we should fix debug impls when we notice that one is bad.
