### ISSUE TITLE
Create my own AsyncUdpSocket

### ISSUE THREAD

**Issue by szguoxz** [quinn-rs/quinn#1847]
I want to do something funny before the data hit quinn, so I am looking into AsyncUdpSocket.
for linux, I found send and recv is not symmetrical. For Send, we send out a transmit, but for Recv, we received a slice of IoSliceMut and RecvMeta.
Here is the structure of RecvMeta:
pub struct RecvMeta {
     pub addr: SocketAddr,
     pub len: usize,
    pub stride: usize,
     pub ecn: Option<EcnCodepoint>,
     pub dst_ip: Option<IpAddr>,
}
Just want to confirm that: info in every RecvMeta would be the same except: len and stride, right, after all, they are from the same transmit? Is it possible a recv will combine two transmit together? That's what I am trying to be sure.

For windows, it seems much simpler, you always only recv one recvmeta.

Thanks.

**Comment by Ralith** [comment]
`AsyncUdpSocket` presents a high-level interface around [`recvmmsg`](https://man7.org/linux/man-pages/man2/recvmmsg.2.html); refer to its documentation for specifics. There is no particular relationship to any specific group of transmit operations.
