### ISSUE TITLE
Expose Packet Decoder？

### ISSUE THREAD

**Issue by thynson** [quinn-rs/quinn#1860]
I'm trying to implement a simple QUIC Load Balancer, following [QUIC-LB] draft, in Rust.
It would be great if the `PartialDecode` related symbol can be exposed to the public.

[QUIC-LB]: https://datatracker.ietf.org/doc/draft-ietf-quic-load-balancers

**Comment by djc** [comment]
Can you make a PR with the changes you need? I'd probably be open to exposing a little more API around this (especially since, based on history, our `PartialDecode` is unlikely to change much).

**Comment by thynson** [comment]
I'm implementing it with s2n-quic for now, which already expose its packet decoder. And I'll try it out with quinn later when I finished a prototype.
