### ISSUE TITLE
How to receive data in blocking way

### ISSUE THREAD

**Issue by wanyt** [quinn-rs/quinn#1862]
In an MQTT communication scenario based on Quinn, the client needs to wait for data being sent by the server. How can the client wait to receive the data from the server? I am currently using a loop, but I feel that this approach consumes CPU resources excessively. Is there a way for the client to block and receive data?

this is my code:
```
loop {
        let resp = recv
            .read_to_end(usize::max_value())
            .await
            .map_err(|e| anyhow!("failed to read response: {}", e))?;
        let duration = response_start.elapsed();
        eprintln!(
            "response received in {:?} - {} KiB/s",
            duration,
            resp.len() as f32 / (duration_secs(&duration) * 1024.0)
        );

        io::stdout().write_all(&resp).unwrap();
        io::stdout().flush().unwrap();     
    }
```

**Comment by djc** [comment]
Why do you even need a loop here? The `recv.read_to_end()` call should yield only once, after the entire response is available.

**Comment by wanyt** [comment]
How should I continuously wait to receive data when I'm not sure when the data will come?
