### ISSUE TITLE
Inconsistent documentation on platform availability of `local_ip`

### ISSUE THREAD

**Issue by Pixelstormer** [quinn-rs/quinn#1864]
Of the three `local_ip` methods that exist on [`quinn_proto::Connection`](https://github.com/quinn-rs/quinn/blob/main/quinn-proto/src/connection/mod.rs#L1313), [`quinn::Connection`](https://github.com/quinn-rs/quinn/blob/main/quinn/src/connection.rs#L489), and [`quinn::Connecting`](https://github.com/quinn-rs/quinn/blob/main/quinn/src/connection.rs#L164), they each list a different set of platforms on which the method is supposedly available.

The proto `Connection` lists Linux and Windows, the quinn `Connection` lists only Linux, and `Connecting` lists Linux, FreeBSD and macOS. The documentation of all three of these functions should be reconciled to whatever the true set of supported platforms is.

**Comment by Ralith** [comment]
Thanks for the report! We should probably list this information in one place and link to it from elsewhere to avoid drift in the future.

**Comment by djc** [comment]
I think perhaps quinn-proto should not document platform support, because availability seems fully dependent on the caller?

**Comment by djc** [comment]
So I think the current list is:

* Windows
* Linux
* Android
* FreeBSD
* macOS
* iOS

For implementations that use an `AsyncUdpSocket` based on quinn-udp.
