### ISSUE TITLE
long running bi stream

### ISSUE THREAD

**Issue by szguoxz** [quinn-rs/quinn#1866]
Is it a good practice to open_bi, and keep it open forever, i.e., days, months?
is the connection/stream stable enough to be open, even for years?

**Comment by szguoxz** [comment]
I am wondering why? So you mean long running stream is OK for non framed use case?

**Comment by Ralith** [comment]
You can keep streams open for as little or as much time as you like. Are you having trouble with that?

**Comment by szguoxz** [comment]
I am just wondering why you suggest one frame per stream.
I am currently using length delimited frame. and my connection got stuck from time to time. (sometimes in a day or two days, some times in a few minutes if I am lucky).
I can't be sure this is the problem, as I still don't know how to reproduce it. So I don't want to blame the stream yet. I just want to clarify two things:

For cost wise, theoretically, which one is cheaper? length delimited or one frame per stream? as length delimited, every frame I need to two bytes to the payload. What is the cost for one stream per frame? Let's forget about MTU split ... etc. What is the addition costs we need to pay to transfer a stream? After all, you need a internal frame to implement unistream.read_to_end.

I know they are almost the same cost, buy theoretically, which one is cheaper? Why do you suggest the later?

**Comment by Ralith** [comment]
They are both very cheap, but have different semantics. The question has nothing to do with "cheaper". A single stream will always deliver data in order; separate streams allow for out-of-order processing if you want it, and can save you the trouble of implementing your own framing. You should use whichever approach makes more sense for your application.

> I am currently using length delimited frame. and my connection got stuck from time to time

Is this about the same problem you raised in #1867? Please only open one issue to describe a specific problem. It is difficult to track a discussion spread across multiple threads.
