### ISSUE TITLE
Weird issue when transferring large file

### ISSUE THREAD

**Issue by neevek** [quinn-rs/quinn#1885]
I encounter a problem when using Quinn to build a proxy. The topology is as follows:

```rust
HTTP proxy <-> Quinn Client <-> Quinn Server <-> HTTP proxy
```

When using curl or any other HTTP clients to request a large file through the proxy, I observe different behaviors based on the operating system:

* Ubuntu/Armbian:
  * curl exits with an error after 20s - 25s:
    `curl: (18) transfer closed with 296418866 bytes remaining to read.`
* MacOS:
  * No error occurs, and the file is completely transferred.

The Quinn server and client are run on Ubuntu, I tried running the Quinn client on MacOS, but the issue still exists.

I checked the trace log of Quinn before curl exit, there's a few lines that may be relevant:

```
2024-06-02 23:28:31.373 [quinn_proto::connection:2627] [T] got stream frame id=client bidirectional stream 3 offset=61105314 len=539 fin=true
2024-06-02 23:28:31.373 [quinn_proto::connection::packet_builder:94] [T] send; space=Data pn=2287
2024-06-02 23:28:31.373 [quinn_proto::connection:3259] [T] ACK ArrayRangeSet([52776..53359]), Delay = 724us
2024-06-02 23:28:31.373 [quinn_proto::connection:1000] [T] sending 42 bytes in 1 datagrams
```

This discrepancy suggests there might be a configuration issue or platform-specific bug, not sure if it is related to Quinn, but I'm not sure how to debug it.

**Comment by Ralith** [comment]
It looks like you're closing the stream earlier than you intended to. Try setting a breakpoint in `SendStream::close`, or adding equivalent logging.

**Comment by neevek** [comment]
This issue is related to another TCP proxy backend, which prematurely closes the connection, it is not an issue of Quinn.

**Comment by Ralith** [comment]
Thanks for following up!
