### ISSUE TITLE
Consider adding an expect message to unwrap in packet_builder.rs

### ISSUE THREAD

**Issue by casey** [quinn-rs/quinn#1928]
A buggy custom session implementation can hit this unwrap:

https://github.com/quinn-rs/quinn/blob/ff91ffe8154e2ff1137ff8d29cd7ca5fd1030452/quinn-proto/src/connection/packet_builder.rs#L141

It might be nice to have an `expect` message which gives a hint as to what went wrong.

**Comment by djc** [comment]
Sure, can you send a PR?

**Comment by casey** [comment]
Definitely! But I don't actually know what I'm doing wrong, so my PR would be:

```
 let zero_rtt = conn.zero_rtt_crypto.as_ref().expect("skill issue"); 
```

😅

**Comment by Ralith** [comment]
How about something like "sending packets in the application data space requires known 0-RTT or 1-RTT keys"?

**Comment by casey** [comment]
That message makes sense, but I'm not sure if it helps the custom session implementor figure out what they did wrong.

The error message "sending packets in the application data space requires known 0-RTT or 1-RTT keys" makes it sound like it was the client code which is using a quinn connection which uses this session implementation's fault, but in this case, the fault is with the session implementation.

Obviously my custom session implementation is wrong since it's hitting this error, and I think it's because I'm not properly stepping through the states of the handshake correctly.

Is there a way to phrase this which clearly indicates that this is a bug with the session implementation?

**Comment by Ralith** [comment]
> Is there a way to phrase this which clearly indicates that this is a bug with the session implementation?

That isn't desirable, because this might be triggered by a quinn bug as well.

> makes it sound like it was the client code

Incorrect operations by client code shouldn't ever produce internal panics.

**Comment by casey** [comment]
Ah, gotcha. Added the suggested message in #1951.
