### ISSUE TITLE
`recvmmsg` is disallowed by seccomp on Android x86

### ISSUE THREAD

**Issue by mxinden** [quinn-rs/quinn#1947]
#### What happened

We attempted switching Firefox Nightly to use `quinn-udp` for QUIC UDP I/O by default recently, though we had to roll back due to an error on Android x86. Investigating further, it seems like seccomp on Android x86 disallows `sendmsg` and `recvmmsg`. All details are in Bugzilla Bug [1910594](https://bugzilla.mozilla.org/show_bug.cgi?id=1910594) and [1910360](https://bugzilla.mozilla.org/show_bug.cgi?id=1910360#c5).

#### Reasoning

Looking at e.g. Android 13's [`SYSCALLS.TXT`](https://android.googlesource.com/platform/bionic/+/refs/tags/android-13.0.0_r83/libc/SYSCALLS.TXT) we can see support for `sendmsg` and `recvmmsg` on 64bit (`lp64`) and ARM:

```
# sockets
// [...]
ssize_t       __sendmsg:sendmsg(int, const struct msghdr*, unsigned int)  arm,lp64
// [...]
int           __recvmmsg:recvmmsg(int, struct mmsghdr*, unsigned int, int, const struct timespec*)   arm,lp64
```

While on x86, only the indirect calls through `socketcall` are allowed:

```
# sockets for x86. These are done as an "indexed" call to socketcall syscall.
// [...]
int           __sendmsg:socketcall:16(int, const struct msghdr*, unsigned int)  x86
// [...]
int           __recvmmsg:socketcall:19(int, struct mmsghdr*, unsigned int, int, const struct timespec*)   x86
```

#### Potential Solution

`libuv` has faced the same issue (see https://github.com/libuv/libuv/issues/2923). On x86 they use the indirect syscalls through `socketcall` (see https://github.com/libuv/libuv/pull/2925).

#### Historical context

The above might be due to historical reasons:

> On x86-32, socketcall() was historically the only entry point for
       the sockets API.  However, starting in Linux 4.3, direct system
       calls are provided on x86-32 for the sockets API.

https://man7.org/linux/man-pages/man2/socketcall.2.html

---

I still have to investigate a bit before proposing a fix. Opening this issue early to track progress.

**Comment by Ralith** [comment]
That's a weird one. Can we push for a fix upstream? Bearing mind that we'll need to work around the issue on older devices anyway.

**Comment by djc** [comment]
> That's a weird one. Can we push for a fix upstream? Bearing mind that we'll need to work around the issue on older devices anyway.

By upstream, do you mean Android? If so, Android 13 is from 2022 so I'm assuming they'll be reluctant to put in fixes like this.

**Comment by Ralith** [comment]
> By upstream, do you mean Android?

Right.

> Android 13 is from 2022 so I'm assuming they'll be reluctant to put in fixes like this.

I couldn't guess either way, but it's not clear from the description if this has already been fixed in newer Android versions. Would be nice to make things less bad in the future, if not.

**Comment by mxinden** [comment]
> Can we push for a fix upstream?

Intuitively I don't expect that such a pervasive change to a systems default `seccomp` filters on an ancient platform like Android x86 would be accepted. That said, I don't have any experience interacting with these projects.

For comparison, next to `libuv` mentioned above, here is what `mio` and Rust's `libc` did. The same problem applies not only to `sendmsg` and to `recvmmsg` but also to the `accept` system call family. While `accept` is supported on Android x86, `accept4` is disallowed by seccomp.

- Fix in Rust's `libc` using `accept4` through `socketcall` instead.
  - https://github.com/rust-lang/rust/issues/
  - https://github.com/rust-lang/libc/pull/2079
- Fix in `mio` using `accept` instead.
  - https://github.com/tokio-rs/mio/issues/1445
  - https://github.com/tokio-rs/mio/pull/1446

> > Android 13 is from 2022 so I'm assuming they'll be reluctant to put in fixes like this.
> 
> I couldn't guess either way, but it's not clear from the description if this has already been fixed in newer Android versions. Would be nice to make things less bad in the future, if not.

As far as I can tell, it is not fixed in the most recent Android version, that is Android 14. See `recvmmsg` call once defined for `arm` and `lp64` and once for `x86` in [`SYSCALLS.TXT`](https://android.googlesource.com/platform/bionic/+/refs/tags/android-14.0.0_r54/libc/SYSCALLS.TXT).

**Comment by mxinden** [comment]
With https://github.com/quinn-rs/quinn/pull/1966 merged and released, this is fixed. :face_exhaling: 

As always, thank you for your help Dirkjan and Benjamin!
