### ISSUE TITLE
"authentication failed" error raised in 0.11, but not in 0.10

### ISSUE THREAD

**Issue by matheus23** [quinn-rs/quinn#1974]
When we were working on our update of quinn 0.10 to 0.11 for https://github.com/n0-computer/iroh, we would sometimes get an error "authentication failed", more specifically:
```
TransportError(Error { code: PROTOCOL_VIOLATION, frame: None, reason: "authentication failed" })
```

It took a long while but we tracked it down to this scenario, involving two peers Alice and Bob, with Alice acting as both client and server simultaneously, and Bob acting as a server.
1. Both Alice and Bob have accept loops accepting new packets
2. Alice connects to bob, sending an Initial packet
3. Bob responds with an Intial and Handshake packet
4. [The connection continues and ends gracefully]
5. The datagram from 3 gets retransmitted
6. Alice thinks the packet she received is a new incoming connection and interprets it as such. It ends up containing bogus data (likely because she derives the wrong secret to decrypt the header).
   (This happens in ~10% of cases. The other 90% of cases the packet gets dropped and logs indicate "invalid reserved bits".)

The change here is due to the fact that now, authentication failures are raised to the user.
Before in quinn 0.10:
https://github.com/quinn-rs/quinn/blob/db2df614fcab3e9c17b3e5f325eb197920489779/quinn-proto/src/endpoint.rs#L524-L532

Now in quinn 0.11:
https://github.com/quinn-rs/quinn/blob/cef42cccef6fb6f02527ae4b2f42d7f7da878f62/quinn-proto/src/endpoint.rs#L593-L610

## Minimal Reproduction Test

I've written a test case that reliably reproduces this issue here:
https://github.com/n0-computer/quinn/commit/ea0b0c0f6a0e9f221aa992c955bf52b574620308

This is based on the current quinn `main` branch.

## Open Questions

Is there perhaps a way to distinguish a packet that indicates an attempt to *open* a connection from a packet that attempts to *answer* a handshake attempt?
If so, this should probably be used to filter out the packet earlier so it doesn't raise a failure to the user.

**Comment by Ralith** [comment]
> 4. [The connection continues and ends gracefully]
> 5. The datagram from 3 gets retransmitted

I'm surprised that data from a closed connection is retransmitted. Further, even if it *is* retransmitted, the draining period is supposed to silently eat this sort of thing. I'll have to inspect your repro (thanks!) to understand this in more depth.

> The other 90% of cases the packet gets dropped and logs indicate "invalid reserved bits"

This inconsistency arises from reserved bits being ~free to check ASAP, whereas we defer more costly work like packet authentication to after the application has an opportunity to apply DoS mitigations. Once you have an `Incoming`, we have to tell you *something* when the connection can't be established, and it might as well have details. 

> The change here is due to the fact that now, authentication failures are raised to the user.

As you might infer, it's perfectly safe to ignore accept errors, perhaps with some quiet logging. You'll get something similar any time anyone spews garbage at your socket, which will happen occasionally on the internet.

> Is there perhaps a way to distinguish a packet that indicates an attempt to open a connection from a packet that attempts to answer a handshake attempt?

The only way to distinguish the intent behind an Initial packet is to decrypt it. Initial packet keys are derived from the first initial packet's DCID, which will be inconsistent here, so this is impossible.

**Comment by matheus23** [comment]
> > 4. [The connection continues and ends gracefully]
> > 5. The datagram from 3 gets retransmitted
> 
> I'm surprised that data from a closed connection is retransmitted. Further, even if it _is_ retransmitted, the draining period is supposed to silently eat this sort of thing. I'll have to inspect your repro (thanks!) to understand this in more depth.

Sorry, retransmission here not in the sense of "quinn decided to retransmit", but "the network happened to retransmit". In our case the packet was sent via two paths at once and one path was significantly slower.

> > The change here is due to the fact that now, authentication failures are raised to the user.
> 
> As you might infer, it's perfectly safe to ignore accept errors, perhaps with some quiet logging. You'll get something similar any time anyone spews garbage at your socket, which will happen occasionally on the internet.

Okay. That's the solution which we were going with for now, good to have confirmation this is the right thing to do.

---

Thank you for the fast response. From what you're writing it looks like there's nothing to do on the quinn side to address this. We'll ignore & log any errors from `incoming.accept()`. Feel free to close this if you agree.

**Comment by Ralith** [comment]
Sounds good, thanks for following up! 

> In our case the packet was sent via two paths at once and one path was significantly slower.

That probably explains why the draining period didn't work out -- it's based on the current RTT estimate (a bit over 3x).
