### ISSUE TITLE
`DatagramState::drop_oversized` should update `DatagramState::outgoing_total`

### ISSUE THREAD

**Issue by dongcarl** [quinn-rs/quinn#1985]
I could be mistaken, but it seems that `DatagramState::outgoing_total` is updated every time `DatagramState::outgoing` is touched, except for in `DatagramState::drop_oversized`, is there a reason for this?

https://github.com/quinn-rs/quinn/blob/00df0485628dd6e3651a0a38fcf8b265adfd200d/quinn-proto/src/connection/datagrams.rs#L147-L159

**Comment by djc** [comment]
Ah, you're right! That does look like a bug -- see proposed trivial fix in #1987.
