### ISSUE TITLE
Custom initial cipher suite?

### ISSUE THREAD

**Issue by cloneable** [quinn-rs/quinn#1989]
Hi, I'm working on a custom protocol that's mostly QUIC-based and so far quinn has been great. Today, I wanted to upgrade to a newer version and things have changed a lot. It does not seem possible anymore to easily constrain the cipher suite. `Quic(Server|Client)Config` require `TLS13_AES_128_GCM_SHA256` as initial suite. (I understand QUIC mandates that suite, but I don't need true QUIC compatibility. And I understand AES-128 is still considered secure and stronger suites have only a theoretical advantage, though come with performance degradation.)

Is there an easy way to create a crypto config for client and server with different cipher suites that I simply missed? I could reimplement `Quic(Server|Client)Config`, but would also need to reimplement/copy `TlsSession`, which is a lot more code.

Thanks for any help!

**Comment by djc** [comment]
In what way do you want to constrain the cipher suite, and what's your goal in doing so? Using AES-128-GCM for just the initial space packets doesn't seem like a big deal -- the data space will still use your preferred cipher suite per the config's configured cipher suite order.

**Comment by Ralith** [comment]
Note also that the initial cipher suite doesn't actually provide security anyway -- its role is purely to defend against ossification.
