### ISSUE TITLE
"unused manifest key" warning occurs upon cargo check

### ISSUE THREAD

**Issue by gretchenfrage** [quinn-rs/quinn#2004]
Running the main branch (commit `08ee9ee471b61fe2c7a7248dfb628b0edcf6aca9`) with the latest cargo version (`cargo 1.81.0 (2dbb1af80 2024-08-20)`, `rustc 1.81.0 (eeb90cda1 2024-09-04)`) emits the following warning:

```
warning: /home/phoenix/repos/quinn/quinn-udp/Cargo.toml: unused manifest key: target.cfg(any(target_os = "linux", target_os = "windows")).bench
```

**Comment by djc** [comment]
I've also seen this, but not sure what to do about it. `Cargo.toml` context:

https://github.com/quinn-rs/quinn/blob/main/quinn-udp/Cargo.toml#L35

`throughput` benchmark using Criterion:

https://github.com/quinn-rs/quinn/blob/main/quinn-udp/benches/throughput.rs

**Comment by mxinden** [comment]
Might be resolved through https://github.com/quinn-rs/quinn/pull/2010 which fixes the invalid `cfg`.

I introduced this in https://github.com/quinn-rs/quinn/pull/1915. Sorry about that.

**Comment by Ralith** [comment]
Is this fixed?

**Comment by gretchenfrage** [comment]
Yes, this appears to be fixed :)
