### ISSUE TITLE
invalid authority or bad dns_name error when using IPv6 abbr

### ISSUE THREAD

**Issue by mokeyish** [quinn-rs/quinn#2005]
Send DNS request to `https://[2001:4860:4860::8888]/dns-query` using H3

| IP | Host | Status |
| -- | -- | -- |
| 2001:4860:4860::8888 | `2001:4860:4860::8888` | invalid authority  |
| 2001:4860:4860::8888 | `[2001:4860:4860::8888]` |  bad dns_name |
| 2001:4860:4860::8888 | `2001:4860:4860:0000:0000:0000:0000:8888` | invalid authority |
| 2001:4860:4860::8888 | `dns.google` | success |

1. Error: bad dns_name
   This should be a problem with [pki-types](https://github.com/rustls/pki-types/issues/62). 

   Maybe it keep the original string representation of IP?
   
2. Error: invalid authority

   Does this need to support the abbreviated IPv6?

**Comment by Ralith** [comment]
Quinn isn't an HTTP/3 implementation, let alone a DNS client implementation, and these errors don't look like anything Quinn generates. Please produce a reproducible example of whatever error(s) you're concerned about coming from a Quinn API, or close this issue in favor of one reported on a the crate actually responsible.

**Comment by mokeyish** [comment]
Yes, upon further testing, the root cause is not Quinn.

I've fixed it at here: https://github.com/mokeyish/pki-types/commit/4ad51ec1f97ceb3809892396ef704d1d9485ef88

![image](https://github.com/user-attachments/assets/16c6a440-9d56-4063-a221-0771dd9b0207)

**Comment by djc** [comment]
I don't think that belongs in rustls-pki-types either, though. Probably something Hickory should do?

**Comment by mokeyish** [comment]
@djc Modifying `rustls-pki-types` can avoid multiple modifications in third-party libraries. This error occurs in both HTTP/2 and HTTP/3.


I use curl and its Ipv6 address also contains square brackets.

![image](https://github.com/user-attachments/assets/786f2cac-fcc6-4e0e-8000-7e2ad00bdde6)

Modifying rustls-pki-types can avoid similar potential problems in the future.

@cpu what you think?


---

@djc Yes, it can be fixed on Hickory too. But many places have to be modified.

https://github.com/hickory-dns/hickory-dns/blob/main/crates/proto/src/h3/h3_client_stream.rs#L383

![image](https://github.com/user-attachments/assets/393d4a24-2bca-4ca3-a661-8b6bf9263495)

**Comment by cpu** [comment]
> Modifying rustls-pki-types can avoid similar potential problems in the future.
> 
> @cpu what you think?

I shared my opinion [on the `pki-types` issue](https://github.com/rustls/pki-types/issues/62#issuecomment-2400252333). Fundamentally what `pki-types` represents for the type in question are IP addresses, and the form with square brackets isn't an IP address, it's a semantically and syntactically separate concept:

> Nothing in Rustls operates with URLs so I don't think it's appropriate to support IPv6 URLs. IMO this should be handled at a higher layer.

I agree with @djc that Hickory seems like the correct place.
