### ISSUE TITLE
Some types appear in `quinn`'s public API which are not accessible through `quinn` directly

### ISSUE THREAD

**Issue by gretchenfrage** [quinn-rs/quinn#2012]
One example of this was noted in #1757:

> - quinn does not re-export `quinn_proto::TransportError` and other downstream-API-exposed types despite that being a public part of quinn's API via [quinn's re-exporting of `quinn_proto::ConnectionError`](https://docs.rs/quinn/latest/quinn/enum.ConnectionError.html)

Another example is that [`StreamId`](https://docs.rs/quinn/latest/quinn/struct.StreamId.html)'s public API involves `Side` and `Dir`, but `Side` and `Dir` cannot be referenced without adding `quinn_proto` in addition to `quinn` as a dependency.

If this is indeed something we wish to avoid, it would be nice to have some automated tool which could detect such cases.

**Comment by djc** [comment]
We generally want to fix these. Don't know that automated tools for this exist?

**Comment by gretchenfrage** [comment]
Yes, I wasn't aware of one existing and at a cursory glance I didn't find one. Which seems a bit odd given how useful and not-that-hard this seems.
