### ISSUE TITLE
New release with aws-lc support?

### ISSUE THREAD

**Issue by joshtriplett** [quinn-rs/quinn#2026]
Thank you for adding support for alternative rustls backends!

Would it be possible to get a new release of quinn that includes that change, so that other software built atop quinn can start to adapt accordingly?

**Comment by Ralith** [comment]
I don't think we have any hard blockers, yeah. We should take care to branch before #2001 to make a patch release. Might want to slip in a fix for whatever's going on in #2020.

**Comment by Ralith** [comment]
https://github.com/quinn-rs/quinn/pull/2027 has the fix.

**Comment by joshtriplett** [comment]
Looks like #2027 has now been merged.

**Comment by djc** [comment]
Preparing releases in #2034.
