### ISSUE TITLE
Async certificate resolver

### ISSUE THREAD

**Issue by MatthewCash** [quinn-rs/quinn#2070]
Is there a way to asynchronously load and use a certificate after ClientHello? This is possible in tokio-rustls with `LazyConfigAcceptor` but I have not found a way to do it with qinn.

My use case is for the server to dynamically pick a cert based on SNI, read the cert's file asynchronously, and then use it for the connection.

**Comment by djc** [comment]
Yeah, we don't have support for the `Acceptor` yet. I think there was some recent discussion (probably in Discord), but it's a little gnarly to fit into our current API.

**Comment by Ralith** [comment]
I think this is fundamentally a dup of https://github.com/quinn-rs/quinn/issues/2024. See discussion there. We definitely want this feature, but it's not trivial.
