### ISSUE TITLE
Usages of `#[doc(hidden)] pub`

### ISSUE THREAD

**Issue by gretchenfrage** [quinn-rs/quinn#2097]
I found 13 places in this repo that use `#[doc(hidden)]` on pub types for various reasons. In my opinion, there is usually a better way to do something than that, and from what I'm seeing, most of these occurrences seem to date back to the 2018-2019 era of the project.

The way I see it:

 - If it's needed for tests, mark it `#[cfg(test)]`.
 - If it's needed for some weird thing, like perf testing or an interop container, gate it behind a feature flag, and document that that feature flag is not covered by semver commitments. It extra defensiveness desired, mimic [the thing the Hyper project does](https://github.com/hyperium/hyper/blob/30f2961e89eb306780d856e6e2c1ee10ffbbafd2/src/trace.rs#L5) with their `RUSTFLAGS='--cfg hyper_unstable_xyz'` thing.
 - If it's needed for Quinn, then that means that proto is favoring quinn as a privileged user, which is bad ideologically.

---

I found these usages of `#[doc(hidden)]`:

- [x] `quinn::send_stream::SendStream::poll_stopped`
  - As far as I can tell, the only usage of this anywhere is literally in the same module
  - Suggestion: Just make it private
  - #2100 resolves
- [x] `quinn::connection::Connection::force_key_update`
  - Used in interop container
  - Suggestion: Either make part of public API, or gate behind some sort of "interop-container" feature
  - #2101 resolves
- [x] `quinn_proto::connection::Connection::initiate_key_update`
  - Used in tests
  - Used in Quinn, in the `force_key_update` function, which is the previous item on this list
  - Suggestion: If make `force_key_update` part of public API, make this part of public API. If gate `force_key_update` behind "interop-container" feature, make this `#[cfg(any(test, feature = "interop-container"))]`
  - #2101 resolves
- [x] `quinn_proto::config::EndpointConfig::get_max_udp_payload_size`
  - Used in tests
  - Used in Quinn
  - Suggestion: Make part of public API
    - Possibly add getters for all config values?
  - #2102 resolves
- [x] `quinn_proto::connection::streams::ClosedStream::new`
  - Used in Quinn
  - Suggestion: Make part of public API, or rework Quinn usage to not need it
  - #2103 resolves
- [x] `quinn_proto::fuzzing`
  - Already marked `#[cfg(fuzzing)]`
  - Presumably used in fuzzing
  - Suggestion: Just remove the `#[doc(hidden)]`? I don't think it'll appear behind docs if it's gated behind fuzzing.
  - #2104 resolves
- [x] `quinn_proto::StreamId.0`
  - Used in perf
  - Suggestion: Make part of public API. It could be useful for applications to access this. It doesn't have to be making the field itself public, it could be adding from and into implementations or whatever.
  - #2099 resolves
- [x] `quinn_proto::EcnCodepoint` all variants (this counts for 3 of the 13)
  - Used in Quinn
  - Suggestion: Make part of public API.
  - #2105 resolves
- [x] `quinn_udp::EcnCodepoint` all variants (this counts for 3 of the 13)
  - The code for this is identical to the proto version
  - Used in tests
  - Used in Quinn
  - Suggestion: Make part of public API.
  - #2105 resolves

**Comment by djc** [comment]
Thanks for doing this analysis!

> * `quinn::send_stream::SendStream::poll_stopped`     
>   * As far as I can tell, the only usage of this anywhere is literally in the same module
>   * Suggestion: Just make it private

Agreed.

> * `quinn::connection::Connection::force_key_update`
>   * Used in interop container
>   * Suggestion: Either make part of public API, or gate behind some sort of "interop-container" feature

I'd be okay with making this part of the public API.

> * `quinn_proto::connection::Connection::initiate_key_update`
>   * Used in tests
>   * Used in Quinn, in the `force_key_update` function, which is the previous item on this list
>   * Suggestion: If make `force_key_update` part of public API, make this part of public API. If gate `force_key_update` behind "interop-container" feature, make this `#[cfg(any(test, feature = "interop-container"))]`

Same here.

> * `quinn_proto::config::EndpointConfig::get_max_udp_payload_size`
>   * Used in tests
>   * Used in Quinn
>   * Suggestion: Make part of public API
>     * Possibly add getters for all config values?

Makes sense to make this public, not very motivated to make the other stuff public unless there's more of a motivation.

> * `quinn_proto::connection::streams::ClosedStream::new`      
>   * Used in Quinn
>   * Suggestion: Make part of public API, or rework Quinn usage to not need it

Maybe we can derive `Default` for `ClosedStream` instead?

> * `quinn_proto::fuzzing`      
>   * Already marked `#[cfg(fuzzing)]`
>   * Presumably used in fuzzing
>   * Suggestion: Just remove the `#[doc(hidden)]`? I don't think it'll appear behind docs if it's gated behind fuzzing.

Works for me.

> * `quinn_proto::StreamId.0`
>   * Used in perf
>   * Suggestion: Make part of public API. It could be useful for applications to access this. It doesn't have to be making the field itself public, it could be adding from and into implementations or whatever.

Suggest #2099.

> * `quinn_proto::EcnCodepoint` all variants (this counts for 3 of the 13)      
>   * Used in Quinn
>   * Suggestion: Make part of public API.
> 
> * `quinn_udp::EcnCodepoint` all variants (this counts for 3 of the 13)      
>   * The code for this is identical to the proto version
>   * Used in tests
>   * Used in Quinn
>   * Suggestion: Make part of public API.

Sounds good to me.

**Comment by gretchenfrage** [comment]
Congras, we done it
