### ISSUE TITLE
Move into quic-rs organization and possibly rename to quic?

### ISSUE THREAD

**Issue by newpavlov** [quinn-rs/quinn#21]
@dyxushuai and @cssivision own `quic` crate and have created `quic-rs` org. I think it would be nice if you three will work together. What do you think?

**Comment by djc** [comment]
It looks like they have so far not done any actual work; rather, they have claimed a crate name on crates.io without writing any code, and it also looks like they copied text from my README. As such, I don't see what I would gain from working with them (except for the crate name, which I don't care much for).

**Comment by dyxushuai** [comment]
@newpavlov Sorry, I was busy with my work in these days, and we will commence to finish the remaining work from June. Thanks a lot

**Comment by newpavlov** [comment]
@dyxushuai 
djc has [indicated](https://internals.rust-lang.org/t/quic-protocol-support-in-tokio/7381/9) his interest in gaining access to the quic-rs org. What do you say? As a potential consumer I personally would prefer to have a single high-quality implementation under `quic` crate name, rather than 2-3 competing projects of varying quality.

**Comment by Ralith** [comment]
With quinn successfully participating in draft-17 interop, and the `quic` crate still empty, perhaps it's time to revisit this?

**Comment by Ralith** [comment]
Closing as the owners of the `quic` name are unresponsive and at this point we're pretty committed to our name anyway.
