### ISSUE TITLE
Provide local and remote socket addresses from a `Connecting`

### ISSUE THREAD

**Issue by Demi-Marie** [quinn-rs/quinn#508]
libp2p needs to know the local and remote socket addresses for every incoming connection as soon as the connection is accepted.  Is this a feature that you would be willing to include?  If so, I will submit a PR.

**Comment by Ralith** [comment]
You can get the local address from `Endpoint::local_addr`, or just hold onto whatever you passed to `EndpointBuilder::bind`. We don't have plans to support multiple local addresses, so this should be sufficient, but let us know if it's not.

Exposing the remote address from `Connecting` makes perfect sense to me. I imagine many applications will want this even just for diagnostics. A PR would be very welcome!

**Comment by Ralith** [comment]
Alternatively, since this doesn't make a lot of sense for outgoing connections, perhaps `<Incoming as Stream>::Item` could be made into a struct containing `Connecting` and associated metadata, but my gut feeling is that's less ergonomic for dubious benefit.

**Comment by DemiMarie-parity** [comment]
Libp2p needs to know the destination IP address of the UDP datagram that initiated the connection.  This allows it to publish new addresses at which the local host can be reached.  This address is generally different from what was passed to `EndpointBuilder::bind` if a wildcard address was used for the latter.  On Linux, it can be obtained by setting the `IPV6_RECVPKTINFO` option for IPv6 sockets, or the `IP_PKTINFO` option for IPv4 sockets.

**Comment by Ralith** [comment]
Ah, good point, I forgot about wildcard IPs. Exposing that makes sense, though it'll require a certain amount of piping, and perhaps attention to win32/macos/BSD compatibility.

**Comment by DemiMarie-parity** [comment]
Windows is going to require us to handle sockets ourselves, just as we already do on \*nix.  I don’t have access to a Windows machine, so I am not particularly comfortable writing this code.  I am, however, willing to write an implementation for Linux.

**Comment by Ralith** [comment]
If we're lucky it'll be exactly the same, but obscure cmsg stuff is pretty hit-or-miss portability wise. Linux would be a good start for us to build off of, at least!

**Comment by DemiMarie-parity** [comment]
Here is what I have found:

| OS | Linux | FreeBSD | OpenBSD | NetBSD | macOS | Solaris (and presumably AIX, etc) | Windows |
| -- | ----- | ------- | ------- | ------ | ----- | ----------------- | ------- |
| IPv4 destination address | `IP_PKTINFO` | `IP_RECVDSTADDR` (or `IP_ORIGDSTADDR`) | `IP_RECVDSTADDR` | all are supported | ? | `IP_RECVPKTINFO` | `IP_PKTINFO` |
| IPv4 ingress interface | `IP_PKTINFO` | `IP_RECVIF` | not supported | all are supported | ? |  `IP_RECVPKTINFO` | `IP_PKTINFO` |
| IPv6 destination address | `IPV6_RECVPKTINFO` | `IPV6_PKTINFO` | `IPV6_PKTINFO` | `IPV6_RECVPKTINFO` | `IPV6_PKTINFO` | `IPV6_RECVPKTINFO` | `IPV6_RECVPKTINFO` | `IPV6_PKTINFO` |
| IPv6 ingress interface | `IPV6_RECVPKTINFO` | `IPV6_PKTINFO` | `IPV6_PKTINFO` | `IPV6_RECVPKTINFO` | `IPV6_PKTINFO` | `IPV6_RECVPKTINFO` | `IPV6_RECVPKTINFO` | `IPV6_PKTINFO` |

**Comment by Ralith** [comment]
Nice work! Do you expect to need interfaces too?

**Comment by DemiMarie-parity** [comment]
Probably not right away, although they would be nice to have.  I think we should have a crate that abstracts these differences, and then port async-std and tokio to use it.

**Comment by Ralith** [comment]
Adding support for semi-portable cmsg stuff to foundational libraries is a very tricky engineering problem, particularly when trying to be zero-cost. We're already doing similar things by hand for ECN support and I think continuing in that vein is reasonable.

That said, if you have ideas for how to address this sort of thing more reusably, don't let me stand in your way! I know tokio, at minimum, is receptive to exposing cmsg-related capabilities if a good API can be found.

**Comment by Ralith** [comment]
Bear in mind also that we expect Quinn to continue to dig deeper into esoteric and bleeding-edge platform-specific APIs as part of ongoing performance work, e.g. #501, so any attempt to create a generic "advanced datagram socket" abstraction will have a moving target.

**Comment by DemiMarie-parity** [comment]
@Ralith I think `io_uring` on Linux will be the biggest performance win of them all, at least for APIs that don’t require special privilege.  That very much should be incorporated into Tokio and async-std, as it also supports filesystem I/O.

**Comment by Ralith** [comment]
While io_uring is pretty cool, and I'm strongly supportive of its adoption in general-purpose toolkits, it doesn't solve the problems addressed by segmentation offload.

**Comment by DemiMarie-parity** [comment]
As far as control messages, I think libraries can provide a thin wrapper around the raw system calls with a reasonable amount of effort.  Users would be expected to provide their own buffers.

**Comment by Ralith** [comment]
I think we need this to handle the case where a single socket accepts connections on multiple addresses on the same subnet. Currently, the source address of outgoing packets is not guaranteed to match what the peer expects in that situation. See https://blog.powerdns.com/2012/10/08/on-binding-datagram-udp-sockets-to-the-any-addresses/ for related discussion.

**Comment by Demi-Marie** [comment]
This is actually less of an issue for QUIC than it is for DNS, since QUIC supports roaming of clients natively.  We do need to get this right for servers, though.

**Comment by Ralith** [comment]
Migration can be disabled for a given connection by the server, so even clients may need this.

**Comment by zz85** [comment]
I was looking up whether quinn supports `IP_PKTINFO` and found this issue. @Demi-Marie, just wondering if you had the chance to work on this issue? It seems that one way `IP_PKTINFO` can be set on socket would be to extend the `send_ext` and `recv_ext` methods

**Comment by Ralith** [comment]
That would be the correct approach, yeah.

**Comment by Matthias247** [comment]
I have implemented the Linux version of this in #943. It works fine. It might also work on other platforms - but I didn't get to verify this so far, so I haven't enabled the flag on other platforms.

I also have another change which will allow to reuse that particular incoming IP address for all outgoing transmissions on the same connection. But I will park that for another CR.

**Comment by Ralith** [comment]
Looks like this was fixed by https://github.com/quinn-rs/quinn/pull/943.
