### ISSUE TITLE
Benchmark throughput

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#59]
Quantitative, reproducible benchmarks are needed to judge the performance impact of changes, and to guide us towards supporting efficient high-bandwidth communications. A good start would be a [criterion](https://crates.io/crates/criterion) benchmark that uses the high-level quinn API to pass a blob of data end-to-end through two quinn endpoints and the host UDP stack.

**Comment by djc** [comment]
That would be great! As always, we're available to help you out with any problems or questions you might run in to. 👍

**Comment by Ralith** [comment]
Other benchmarks I'd also like to have:
- Rate at which connections can be opened and immediately closed
- Rate at which a single connection can open streams that are immediately closed
- Throughput under various patterns of packet loss, reordering, latency, and/or changes in link capacity.

**Comment by Ralith** [comment]
#198 now contains a simple criterion benchmark for sending 128KiB streams.

**Comment by Matthias247** [comment]
can probably be closed since the bulk benchmark is now rather decent?

**Comment by Ralith** [comment]
Yeah, I think so. We could always use more benchmarks for other cases, but those can be addressed separately.
