### ISSUE TITLE
Stream transmits are unfair

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#611]
Currently we make no effort to send stream data in any particular order, which can produce unfair behavior when multiple congestion-bound streams are active simultaneously. A better default would be to distribute bandwidth resources evenly between all active streams, e.g. by round robin.

**Comment by Ralith** [comment]
Groundwork for this underway at #699.

**Comment by Matthias247** [comment]
I think this can be closed since streams now do round robin

**Comment by Ralith** [comment]
Good catch, thanks!
