### ISSUE TITLE
Path MTU discovery

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#69]
We should implement [packetization-layer path MTU discovery](https://tools.ietf.org/html/rfc4821) per the draft's instructions.

**Comment by Ralith** [comment]
On Linux, this will require setting the socket option `IP_MTU_DISCOVER` to `IP_PMTUDISC_PROBE` to set the "don't fragment" flag and bypass the kernel's built-in ICMP-based MTU estimation.

**Comment by djc** [comment]
Note that this is the exact language in draft-16:

> To optimize bandwidth efficiency, endpoints SHOULD use [Packetization Layer PMTU Discovery](https://tools.ietf.org/html/rfc4821). Endpoints MAY use PMTU Discovery ([PMTUDv4](https://www.rfc-editor.org/info/rfc1191), [PMTUDv6](https://www.rfc-editor.org/info/rfc8201)) for detecting the PMTU, setting the PMTU appropriately, and storing the result of previous PMTU determinations.

So, implementations MAY use both PMTUD and PLPMTUD.

**Comment by Ralith** [comment]
Once this is implemented, we should (as a separate feature) emit an event indicating when the maximum datagram frame size changes.

**Comment by abonander** [comment]
For API consumers of `quinn-proto` a nice step forward would be to at least make it possible to change the size of newly encoded packets for a given connection/endpoint. Then at least the application could use datagram frames to perform its own DPLMTUD.

**Comment by djc** [comment]
@abonander how/why did you end up here? In #1510, we're about to merge our DPLPMTUD implementation. Would that cover your use cases?

**Comment by abonander** [comment]
I searched "path MTU" in the repo to see if support for PMTUD was supported and this was the first result under "Issues": 
![image](https://user-images.githubusercontent.com/3198595/229930093-a5add551-2d5f-4759-b505-6808647bb840.png)

I guess I missed the second result, heh.

In case that solution ends up being untenable, however, I still think it would be good to allow an application to provide its own feedback, which would also allow it to work cooperatively with DPLMTUD. 

Like on Linux, where we get `EMSGSIZE` back if we try to send a packet larger than the estimated MTU; right now, it's not obvious what I should do with that error besides ignore it and drop the packet, which feels wrong.

**Comment by Ralith** [comment]
You should generally disable any kernel-side MTU discovery (and IP-layer fragmentation) and let quinn-proto do it's thing, which will prevent `EMSGSIZE` from being delivered at all.
