### ISSUE TITLE
BBR congestion control

### ISSUE THREAD

**Issue by Demi-Marie** [quinn-rs/quinn#693]
Google uses it in production, and it should massively increase throughput on bad networks, while simultaneously fighting bufferbloat.

**Comment by Ralith** [comment]
It'd be cool to support advanced congestion control algorithms. However, congestion control is an active research area, and even BBR is subject to ongoing work; last time I reviewed it there was no remotely complete documentation for the current state of the art. Therefore I'd like to approach this by making congestion control pluggable, probably through a trait object. Some interface design will be necessary, including a review of the field to see what information leading congestion control algorithms require.

**Comment by djc** [comment]
@Ralith if you can outline where the current approach to congestion control is happening I'd like to take a whack at extracting what we have now into separate state/abstraction.

**Comment by Ralith** [comment]
Awesome! `Connection::on_packet_acked` and `Connection::congestion_event` are the heart of the current implementation. See also [the reference pseudocode in the draft](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#name-congestion-control-pseudoco). Communication with the rest of the state machine is through these functions being called, resulting in updates to `self.path.congestion_window`, which is also subject to being reset during migration (but not rebinding).

Abstracting the current implementation out sounds like a good start, and will likely be beneficial in terms of shrinking `connection.rs` regardless. However, I think a significantly richer interface, including e.g. timing information, will be necessary for supporting algorithms like BBR. It makes sense to pursue that as a second pass.

**Comment by Ralith** [comment]
Other algorithms to explore and hopefully support: CUBIC, HyStart

**Comment by Ralith** [comment]
Relevant blog post from quiche: https://blog.cloudflare.com/cubic-and-hystart-support-in-quiche/amp/

We should have a look at their approach to abstracting congestion control.
