### ISSUE TITLE
Interop ECN test `E`

### ISSUE THREAD

**Issue by stammw** [quinn-rs/quinn#707]
> Set ECT(0) on outgoing packets and verify that ACK frames with ECN information are received. (Note: test can fail if path bleaches ECN.)

**Comment by larseggert** [comment]
Based on https://interop.seemann.io/, it doesn't look like quinn supports ECN? Would you in that case signal that to the runner, i.e., return `unsupported` for this test?

**Comment by djc** [comment]
Quinn does have support for ECN; can you file a new issue?

**Comment by larseggert** [comment]
#1841
