### ISSUE TITLE
proto: write outgoing packets to caller-supplied memory

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#729]
`Connection::poll_transmit` allocates and immediately returns a `Vec<u8>`. There's no reason it couldn't instead take a `&mut [MaybeUninit<u8>]` or similar, giving the caller much greater flexibility to reduce allocations/copies, particularly when working with e.g. registered io_uring buffers.

**Comment by lmpn** [comment]
This PR https://github.com/quinn-rs/quinn/pull/1545 seems to have addressed this issue

**Comment by Ralith** [comment]
It has not; refer to the signature of `Connetion::poll_transmit`.

**Comment by lmpn** [comment]
I'm giving it a try 👍

**Comment by cameronelliott** [comment]
Just surfing by, and saw this.
I'm just going to dump my two cents for what it's worth. 
Please ignore if it is not relevant for you.

This type of issue is super important for io_uring, AF_XDP, DPDK, (Networking APIs to get to 100Gbits/sec++)

Actually to take Quinn or any Rust Quic stack to the next level the whole RX & TX hot paths should be allocation-free except by the consumer of the Quic stack.

It would be great to have a Rust Quic stack that allows caller-supplied buffers for both the RX & TX paths, and is allocation-free on the hot path.
(When I say RX, I mean the post-decryption RX destination, a sans-io Quic has the caller do the raw RX)

**Comment by Ralith** [comment]
This was fixed by @lmpn's generous contribution in #1697.

> I mean the post-decryption RX destination

We already decrypt in-place in caller-supplied memory, and only alloc/copy on the receive path when needed to reduce memory usage. Memory allocation is not currently a bottleneck for Quinn; if you want to hit massive throughput, parallelism and encryption are your main bottlenecks. If you're interested in hitting demanding performance targets with Quinn, feel free to open a new issue to discuss any obstacles you encounter.
