### ISSUE TITLE
ECN on Windows

### ISSUE THREAD

**Issue by Demi-Marie** [quinn-rs/quinn#765]
This might be possible, although the APIs are undocumented.

**Comment by Ralith** [comment]
It would be useful to cite evidence.

**Comment by DemiMarie-parity** [comment]
Receiving ECN is possible via the [`IP_RECVTOS` option at `IPPROTO_IP`](https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ip-socket-options) and the [`IPV6_RECVTCLASS` option at `IPPROTO_IPV6`](https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ipv6-socket-options).  Setting is definitely possible if one has administrative privileges.  I am not sure about otherwise.

**Comment by DemiMarie-parity** [comment]
Setting it might be possible via the [undocumented `IPV6_ECN` and `IP_ECN` socket options](/aL3891/RioSharp/blob/4fdb3b5426ecab3ce60cccda2289bb8a1bc2cd14/RioSharp/WinSock.cs).

**Comment by DemiMarie-parity** [comment]
As per https://github.com/microsoft/msquic/issues/559#issuecomment-650610256 I don’t believe this is supported on current versions of Windows.  Closing.

**Comment by Demi-Marie** [comment]
Reopening in light of https://github.com/microsoft/msquic/issues/559#issuecomment-677783801 which actually implements ECN in MsQuic.  Since `msquic.dll` is not an OS-provided DLL, I am confident that this will continue to work in future releases of Windows.

**Comment by panxy2013** [comment]
in microsoft document, we can write UDP client / server, and use wirshark can find, IP ECN 2bits can be modify by windows socket API WSASendMsg

but how to use in Rust, does quinn-udp can support such action?
1. send UDP with ECN bit = 0x01 or 0x02
2. Recieve UDP and can get ECN bit from receive UDP packet

https://learn.microsoft.com/en-us/windows/win32/winsock/winsock-ecn

Thanks

**Comment by djc** [comment]
We don't support this yet in quinn-udp, would you be able to send a PR to use windows-sys APIs to implement this?

**Comment by panxy2013** [comment]
Well, since I'm newer to Rust, I don't have the ability to write good Rust code at the moment
i am working with ALVR project, which use C++/Rust language.

i will use workaround to solve the current problem(Rust call C API to send ECN UDP packet)
Maybe i can try it, Thank you for your explanation

**Comment by stormshield-damiend** [comment]
I did a quick study about this support and i think it is doable, i will work on this and submit a PR when done.

**Comment by stormshield-damiend** [comment]
Little update in teaser mode :
- i now detect the WSARecvMsg function pointer using a dedicated WSAIoctl call as this function is an extension of the network stack
- i have modified recv() and send() function to use socket2 sendmsg() and WSARecvMsg function if detected, if not i fallback to the previous version of the code
- perf client and server still work with the new code
- i am now looking at how to encode and decode control message to enable and PKTINFO and also ECN

**Comment by Ralith** [comment]
> use socket2 sendmsg() and WSARecvMsg function if detected, if not i fallback to the previous version of the code

Out of curiosity, when do we expect this to fail?

**Comment by stormshield-damiend** [comment]
> > use socket2 sendmsg() and WSARecvMsg function if detected, if not i fallback to the previous version of the code
> 
> Out of curiosity, when do we expect this to fail?

From what i read, this function was introduced with TCP/IP version 6 extension on Windows XP, what is strange is that nowadays you still need to detect it dynamically event if it seems supported by default since Windows 8.1.

**Comment by Ralith** [comment]
Huh, that is funny. I'm not sure it's worth the maintenance trouble to maintain a fallback for such old versions of Windows, in any case.

**Comment by stormshield-damiend** [comment]
Little update : 
- new code support ECN and IN[6]_PKTINFO using WSARecvMsg / WSASendMsg and a new wsa_cmsg.rs
- perf client and server work with the new code
- performance seem to be in the same order of magnitude
- tests are currently broken due to new PKTINFO support (i am working on them at the moment)

I plan to send a draft PR as soon as possible

**Comment by djc** [comment]
Fixed in #1701.
