### ISSUE TITLE
0-RTT is sometimes unexpectedly rejected

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#799]
Both the quant maintainer and [quic-tracker](https://quic-tracker.info.ucl.ac.be/traces/20200606/544) have recently reported 0-RTT sometimes being rejected when it shouldn't be. Manual local testing with quant and the interop server has so far failed to reproduce this. The server logs "dropping unexpected 0-RTT packet" instead of "0-RTT enabled", indicating that the call to rustls' `get_0rtt_keys()` failed, so something's happening at that layer: either `SessionCommon::get_suite()` is returning `None`, the PSK isn't being successfully decoded in `CompleteClientHelloHandling::handle_client_hello`, or `ExtensionProcessing::process_common` is unsetting the `quic.early_secret` due to some condition that requires early data to be rejected.

If we can manage to reproduce this locally, it should be straightforward to identify which of these cases is responsible by stepping through with a debugger and/or adding diagnostic prints inside rustls. The responsible case can then be sanity-checked against the TLS 1.3 spec.

**Comment by djc** [comment]
How much time should we invest in trying this manually? It seems like it be quicker to just add diagnostic prints directly, since apparently Lars can reproduce this quite easily.

**Comment by Ralith** [comment]
Mainly it's just difficult to coordinate with Lars due to timezones and availability, so if there's any iteration necessary it'd be far easier to do so locally. Dumping all the relevant variables from rustls on the interop server is a reasonable thing to do in lieu of any alternatives, though, certainly.

**Comment by Ralith** [comment]
This was also reproduced once with ngtcp2's client by me, and once by Tatsuhiro. Unfortunately that was before I deployed the build with debug prints, and both of us have failed to reproduce it since. The difficulty suggests this must somehow be sensitive to timing or encryption keys.

**Comment by Ralith** [comment]
I think we have a culprit: rustls's `ServerSessionMemoryCache`, the default system for storing resumable sessions, is a hash table that bounds memory use by removing `cache.keys().next()` whenever an insert brings it above the limit. Hash tables have no particular order, so this can remove the entry that was just added. The default size limit is 256 elements, which seems fairly consistent with our rare but recurring observations of failures, and with our inability to reproduce after restarting the server with changes (and hence emptying the cache) or in local tests (where the cache never fills up to begin with).

This is IMO very surprising behavior for rustls, though technically harmless since rejecting resumption only costs a bit of latency. Still, I'm not sure why the default configuration isn't a stateless cryptographic scheme which requires zero memory and has no such issues. That'd almost be easier to adopt than an ordered hash table.

@ctz, any thoughts?

**Comment by Ralith** [comment]
Confirmed experimentally that the cache is discarding freshly issued tickets almost immediately before they're used. Suspiciously often, even--this is actually *far* easier to reproduce than you'd expect, at least sometimes. Must be some idiosyncrasy of `HashTable` causing recent data to be more likely to be returned from `next`

**Comment by djc** [comment]
The stateless cryptographic scheme would require the user to manage the keys, right? Unless you perhaps reuse some derivative of the certificate's private key, in which case stuff would invalidate if you rotate the certificate.

**Comment by Ralith** [comment]
Replicating the existing functionality with a stateless cryptographic scheme would not require anything from the user. `ServerSessionMemoryCache` already, as the name suggests, does not persist state, so an alternative implementation would work fine by generating a fresh key when constructed. Failing 0-RTT across server restarts by default is perfectly fine.

**Comment by ctz** [comment]
> @ctz, any thoughts?

I think I should make these have a LRU eviction strategy. It's most likely to be the useful behaviour.

**Comment by Ralith** [comment]
That would definitely solve the immediate problem, but a decent LRU hash table is a significant increase in complexity. Is there a good reason not to use the cryptographic approach?

**Comment by ctz** [comment]
rustls supports the stateless approach (aka "tickets") but it's not a sound idea to do 0RTT resumption with them: see https://tools.ietf.org/html/rfc8446#section-8

**Comment by Ralith** [comment]
Oh, right. Thanks!

**Comment by larseggert** [comment]
AFAIK most (all?) other TLS stacks used with QUIC use some sort of resumption tickets. You might want to discuss with other TLS implementers why they all thought this was an acceptable choice.

**Comment by DemiMarie-parity** [comment]
@larseggert I suspect this is because stateful approaches don’t scale well in multi-server scale-out deployments.  There is no guarantee that a session will be resumed on the same server that it was created on, and storing the state in a database adds both complexity and latency.  RFC8446 is clear that clients must not assume that servers implement anti-replay protections for 0-RTT data, and many higher-level protocols need to implement their own replay protection anyway.

**Comment by DemiMarie-parity** [comment]
Chromium, for example, only uses 0-RTT for idempotent HTTP methods.  Since it already will retry such requests without prompting the user in certain situations, using 0-RTT doesn’t create additional vulnerabilities.  A server which allows a non-idempotent GET request is broken.

**Comment by Ralith** [comment]
As Demi says, it looks like stateless tickets are permissible (if perhaps a poor default) as the RFC places ultimate responsibility for ensuring 0-RTT replays are harmless at the feet of the application. But for the purposes of resolving this issue an LRU cache will do.

**Comment by Ralith** [comment]
@djc has rustls switched to a LRU cache? If so, this can be closed.

**Comment by djc** [comment]
I think so, yes: https://github.com/rustls/rustls/commit/f12853839e80dc5bfa9de1c269e44f3be24de0e4.
