### ISSUE TITLE
Update to Tokio 0.3

### ISSUE THREAD

**Issue by SriRamanujam** [quinn-rs/quinn#872]

**Comment by djc** [comment]
The `AsyncFd` PR is here: https://github.com/tokio-rs/tokio/pull/2903. I think we need to implement our UDP wrapper. It also looks like the 0.7 mio `UdpSocket` has lost its `only_v6()` method, so we have to get that reimplemented upstream or figure out some other way to detect dual-stack sockets.

**Comment by djc** [comment]
(I have been discussing with an Apple engineer from the quicdev Slack whether there's a better way to do things on Darwin or whether there's a bug on their side, I'll see what I can get out of that.)

**Comment by djc** [comment]
Very WIP PR in #873.

**Comment by Ralith** [comment]
I'm concerned that the move to `AsyncFd` doesn't give us a way forward for specialized UDP operations on non-Unix platforms.

**Comment by djc** [comment]
They're open to feedback on the PR, I think.

**Comment by Darksonn** [comment]
We are very open to feedback on the best way forward. The reason it didn't make it for 0.3.0 was unanswered questions on the best way to design it.

**Comment by Ralith** [comment]
Discussion on the Tokio discord revealed that we don't actually have the capacity for specialized UDP operations outside Unix on 0.2 either, so we're good to proceed once `AsyncFd` or equivalent is in.

**Comment by Ralith** [comment]
See also https://github.com/tokio-rs/tokio/issues/2968.

**Comment by Darksonn** [comment]
We have released `AsyncFd`.

**Comment by djc** [comment]
Let's use #856 for this.
