### ISSUE TITLE
Expose RTT probe value to user?

### ISSUE THREAD

**Issue by jamadazi** [quinn-rs/quinn#888]
I know that quinn internally keeps track of the round-trip-time of a connection. Could an API be added to expose this value?

This is very useful information, to know the latency of the connection. Quinn can readily provide this information. By adding such a function, applications can easily know this information without needing application-level logic/protocol for it.

**Comment by djc** [comment]
Seems like a fine idea to me. Do you want try and write a patch?

**Comment by jamadazi** [comment]
Yes, this is a simple thing that someone like me with no experience with the project can do.

I did it. Now posting the PR.
