### ISSUE TITLE
Examples running broken by message 'ERROR: failed to connect: timed out'

### ISSUE THREAD

**Issue by ArvoGuo** [quinn-rs/quinn#900]
I had fllowed the part of Getting Started , but got some error. I'm not familiar with rust, and not know the solution.

![image](https://user-images.githubusercontent.com/7940591/98651872-c64ccd80-2375-11eb-9f6b-6cdedaa45107.png)

**Comment by TimonPost** [comment]
Hey there. Before diving into the source code, I would like to redirect you to this branch #891. I rewrote this example and during that, I can remember having the same error. Im curious if you notice the same behavior there as well.

**Comment by Ralith** [comment]
You're listening explicitly on IPv4, but connecting to localhost by name. Your system may be resolving "localhost" to an IPv6 address. Try replacing localhost with 127.0.0.1.

**Comment by djc** [comment]
Would the README change in #906 have helped present this? (Not sure if this is where you got the idea from.)

**Comment by Ralith** [comment]
Closing for lack of feedback; feel free to reopen if you're still having issues.
