### ISSUE TITLE
Provide a way to notify the user when Connection closes

### ISSUE THREAD

**Issue by madadam** [quinn-rs/quinn#907]
It would be useful to have a way to get notified when `Connection` closes. Our use case is this:

We would like to keep open connections in some kind of container, so that when we want to send something to a peer, we just retrieve the corresponding connection from this container and use it. But we also need to remove dead connections from this container, otherwise it can keep growing indefinitely. Currently the only way (that I know of) to tell that a connection is dead is to actively probe it by sending something on it. But there might be connections that are used very rarely, or even just a couple of times and then never again. So we would have to keep periodically probing those connection to find the ones which died which is annoying and complex.

One way I imagine this could work is to add a `oneshot` channel and fire it when the `ConnectionDriver` future completes. Then somehow expose the receiving half of this channel to the user.

**Comment by djc** [comment]
IIRC you can already do this because the `Incoming{Uni,Bi}Streams` stream will terminate (return `None`) when the connection is closed. Have you tried that? If it doesn't work, why not? (If it does, how could we have highlighted in the documentation so that you could have found it on your own.)

**Comment by djc** [comment]
(Also, would like to hear about what your use case actually is.)

**Comment by madadam** [comment]
> Have you tried that?

Hm, I haven't yet, but it might work. The reason it didn't occur to me is that for various reasons we handle the sending logic separately from the receiving logic (we have separate "outgoing" connections and "incoming" connections) and I was too focused on the sending part only. OK, going to try it out, thanks for the nudge!

**Comment by dirvine** [comment]
> (Also, would like to hear about what your use case actually is.)

It's a wrapper around quinn that acts as the IP networking layer. (we add thinkgs like a connection cache to allow nodes to rejoin the IP network using endpoints it previously saw, plus some NAT traversal, which is only igd at the moment). It's used for clients and also p2p nodes (overlay layer). We are looking at having all connections in that wrapper (we call qp2p)  and upper layers to use the connections from there and not worry about the connection existing or not. They will set idle timers etc. 

Ideally qp2p should handle closed connections and clean those up for cases where consumers did not or could not clean them us. We may have the receive stream in a uni-dir connection handled in a reader while the send capability exists in upper layers (sometimes several). 

We also have our p2p nodes getting client connections and passing these up to consumers for client handling (past the overlay layer which handles infrastructure only). So getteing these connections and basically giving them up several layers and middle layers jut forgetting about them (if that makes sense).

**Comment by djc** [comment]
Ah sorry -- was aware of MaidSafe, but didn't see anything in @madadam's profile linking them to MaidSafe.

I think the way we currently have should suffice, so I'll close this, but feel free to reopen if the proposed mechanism doesn't satisfy your needs.
