### ISSUE TITLE
H3 test go_away_from_client (intermittently?) fails in CI

### ISSUE THREAD

**Issue by djc** [quinn-rs/quinn#912]
Happened here, in testing a completely unrelated PR:

https://github.com/quinn-rs/quinn/pull/909/checks?check_run_id=1396835062

```
---- tests::go_away_from_client stdout ----
thread 'tests::go_away_from_client' panicked at 'assertion failed: `Ok(())` does not match `Err(Error::Http(HttpError::RequestRejected, None))`', quinn-h3/src/tests/mod.rs:295:5
```

I haven't seen this before.

**Comment by stammw** [comment]
We could just remove or ignore those `h3`-related tests ? How do you see the future of this crate ?

**Comment by djc** [comment]
Unfortunately I haven't been following along with hyper's h3 work very closely, so you probably have a better read on the future of this crate than I do. I seem to remember you preferred this crate's API over Sean's proposed API for the hyper efforts?

**Comment by stammw** [comment]
For the moment, Sean's API implementation is progressing quite slowly. It is now able to run requests without QPACK or connection life-cycle feature.

I like `quinn-h3` API but I don't really have any preference. 

I don't know what to do with `quinn-h3`, it can't stay pending forever. Releasing it as an alpha would be nice, but I worry about my available bandwidth to maintain it, if it ever gets popular. 

I think we cannot remove it as it is used in interop, and the efforts to transition from `quinn-h3` to `h3` in interop module don't really worth it.

**Comment by Ralith** [comment]
Without speaking to the status of quinn-h3, I think it's fair to see the (h3-related) aspects of the interop infra as being logically part of the h3 implementation. If there's a need for a hyper-flavored interop tool, it should probably be developed as part of hyper.

**Comment by djc** [comment]
I do get the feeling the interop stuff is being deemphasized upstream in favor of the QUIC network simulator (and we might be falling behind a bit as long as we don't have a QNS setup).

**Comment by djc** [comment]
Another reason not to dump quinn-h3 just yet is that I've found in my recent refactoring that quinn-h3 tests exercise some code paths that our other tests do not, so keeping h3 around does improve code coverage for quinn/quinn-proto for now.

**Comment by Ralith** [comment]
Closing this as we've removed the test in question.
