### ISSUE TITLE
Laminar vs Quinn

### ISSUE THREAD

**Issue by warrenalphonso** [quinn-rs/quinn#916]
I see there'll be an update to the Quinn book describing this #865, but I decided to ask here anyway for anyone else searching this repo for info comparing Quinn to Laminar. I notice @TimonPost is a contributor of both. Quinn seems a much more general networking protocol whereas Laminar seems focused on game networking. Am I understanding the two correctly? Is Quinn worth looking at for game networking? Thanks!

**Comment by Ralith** [comment]
My work on Quinn is motivated by my requirements for a robust, featureful transport for my own game development projects, so certainly I think so. Some others feel Quinn is a bit heavyweight for this purpose; https://github.com/kyren/turbulence may be of interest as a simpler alternative.

**Comment by warrenalphonso** [comment]
From what I understood from the README, Turbulence is meant to be used an interface with a tool that actually sends and received packets. Is Quinn that sort of tool, or is Quinn more like Turbulence in that it needs another tool to send and receive packets? 

Forgive the basic questions. I still don’t think I understand the differences between Laminar, Quinn, and now Turbulence.

**Comment by Ralith** [comment]
The `quinn` crate handles I/O for you internally, and is designed for your application layer to work on top of directly. `quinn-proto` can be plugged into a UDP socket manually, if for some reason you need that. QUIC in general should not be ran over anything higher level than UDP, though. Typically you'd plug turbulence into a UDP socket or, if you're in a browser, a WebRTC session. If you need browser-friendliness, that's a good reason to favor turbulence.

**Comment by TimonPost** [comment]
I can not share any quinn detailed comparison to laminar. Laminar does lack some key features like encryption and connection establishment. Next to that its development has been low for the 1.5 year. 

The key question in protocol selection is what kind of game-networking are you dealing with?

**Comment by djc** [comment]
Note that Quinn is merely an implementation of the QUIC protocol -- it does not define its own protocol. The QUIC protocol is defined quite well by the IETFC RFC drafts.

https://tools.ietf.org/html/draft-ietf-quic-transport-32

**Comment by warrenalphonso** [comment]
Thank you for the replies. 

I’m not sure how to classify different kinds of game-networking, but suppose I need very low latency for a fast-paced multiplayer game. Is there any reason to choose laminar over Quinn for this use case? 

Thanks for writing the book on Quinn, @TimonPost. After reading it, I’m still unsure about the differences between Quinn and laminar. Multiplexing seems to be important theme in the book; does laminar not support multiplexing? 

I understand that Quinn is an implementation of the QUIC protocol, but as someone without much networking domain knowledge, how do I decide when to commit to Quinn over laminar? Is one easier to setup then the other? What potential functionality do I lose by choosing one over the other?

**Comment by TimonPost** [comment]
For fast-phased low latency games, TCP is by definition not applicable, see the TCP issue chapter. Laminar is build to the model described [here](https://gafferongames.com/categories/game-networking/) to have packet acknowledgment based on the assumption of a constant message stream (described by the model). netcode and valve-network-socket are working on this same model.

You need to ask the following questions, is packet drop allowed? Should my packets arrive in-order or in-sequence? Is security a concern for you? Is reliability necessarily?

**Comment by warrenalphonso** [comment]
I came across that link before, and it helped me understand the inspiration for Laminar. I still don’t understand the differences between Laminar and Quinn. 

For the questions you ask, 

> You need to ask the following questions, is packet drop allowed? Should my packets arrive in-order or in-sequence? Is security a concern for you? Is reliability necessarily?

What responses make using Quinn the better option? Which make Laminar the better option?

**Comment by jamadazi** [comment]
Relevant to this discussion: I intend to make a crate that drives `quinn-proto` from the bevy runtime (by polling a nonblocking UDP socket), to avoid the dependency on `tokio` from using `quinn`. I will post an update when that's ready.

**Comment by djc** [comment]
I'm surprised to hear Bevy has its own async runtime, but that sounds good!

Let us know if you have any questions or run into any issues.

(I think we might also be happy to make quinn less dependent on the particulars of the tokio runtime, if that would help.)

**Comment by jamadazi** [comment]
AFAIK bevy doesn't have an async runtime, but the `quinn-proto` core does not require async. I can just poll the UDP socket and track the relevant state.

For a game, which is an application that refreshes all the time (does not sleep/wait), it's not a waste to repeatedly poll the socket and update the protocol every frame.

**Comment by djc** [comment]
Ah, fair enough.

**Comment by jamadazi** [comment]
Yeah, thank you for designing `quinn` in this way (having `quinn-proto` as the low-level core). It makes things very nice. :)

I can have a tokio-based server and a game client that are compatible and use the same underlying QUIC+crypto implementation.

**Comment by Ralith** [comment]
Closing this as there's no action for us to take here. Anyone with related questions should feel free to drop in on the gitter/matrix chat to discuss!
