### ISSUE TITLE
Build failed on Linux

### ISSUE THREAD

**Issue by jona-1993** [quinn-rs/quinn#928]
Hi,

I can't build the server and client on Manjaro Linux. 

I have this error:

$ cargo run --verbose --example server ./ 
...
Compiling quinn v0.6.1 (/home/jona1993/Bureau/quinn/quinn)
Running `rustc --crate-name quinn --edition=2018 quinn/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="certificate-transparency"' --cfg 'feature="default"' --cfg 'feature="native-certs"' --cfg 'feature="rustls"' --cfg 'feature="tls-rustls"' --cfg 'feature="webpki"' -C metadata=4707029b872475d0 -C extra-filename=-4707029b872475d0 --out-dir /home/jona1993/Bureau/quinn/target/debug/deps -C incremental=/home/jona1993/Bureau/quinn/target/debug/incremental -L dependency=/home/jona1993/Bureau/quinn/target/debug/deps --extern bytes=/home/jona1993/Bureau/quinn/target/debug/deps/libbytes-132544d621c1e922.rmeta --extern futures=/home/jona1993/Bureau/quinn/target/debug/deps/libfutures-ec01a20cd1ba0e55.rmeta --extern libc=/home/jona1993/Bureau/quinn/target/debug/deps/liblibc-89279ce17dbf6aed.rmeta --extern mio=/home/jona1993/Bureau/quinn/target/debug/deps/libmio-7d4e29593d9fecb5.rmeta --extern proto=/home/jona1993/Bureau/quinn/target/debug/deps/libquinn_proto-c77971162d457871.rmeta --extern rustls=/home/jona1993/Bureau/quinn/target/debug/deps/librustls-f460949ff94ada3a.rmeta --extern thiserror=/home/jona1993/Bureau/quinn/target/debug/deps/libthiserror-18430524a81fdaa1.rmeta --extern tokio=/home/jona1993/Bureau/quinn/target/debug/deps/libtokio-96636c1167ea3c00.rmeta --extern tracing=/home/jona1993/Bureau/quinn/target/debug/deps/libtracing-976b01f8ec586a1d.rmeta --extern webpki=/home/jona1993/Bureau/quinn/target/debug/deps/libwebpki-b777aa3e3e5339a3.rmeta -L native=/home/jona1993/Bureau/quinn/target/debug/build/ring-6a6605d43da55d7d/out`
error[E0596]: cannot borrow `self` as mutable, as it is not declared as mutable
   --> quinn/src/connection.rs:259:26
    |
258 |     fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
    |             ---- help: consider changing this to be mutable: `mut self`
259 |         let conn = &mut *self.0.lock().unwrap();
    |                          ^^^^ cannot borrow as mutable

error[E0596]: cannot borrow `self` as mutable, as it is not declared as mutable
   --> quinn/src/endpoint.rs:191:30
    |
190 |     fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
    |             ---- help: consider changing this to be mutable: `mut self`
191 |         let endpoint = &mut *self.0.lock().unwrap();
    |                              ^^^^ cannot borrow as mutable

error[E0596]: cannot borrow `self` as mutable, as it is not declared as mutable
   --> quinn/src/endpoint.rs:441:30
    |
440 |     fn poll_next(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Option<Self::Item>> {
    |                  ---- help: consider changing this to be mutable: `mut self`
441 |         let endpoint = &mut *self.0.lock().unwrap();
    |                              ^^^^ cannot borrow as mutable

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0596`.
error: could not compile `quinn`.

Caused by:
  process didn't exit successfully: `rustc --crate-name quinn --edition=2018 quinn/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="certificate-transparency"' --cfg 'feature="default"' --cfg 'feature="native-certs"' --cfg 'feature="rustls"' --cfg 'feature="tls-rustls"' --cfg 'feature="webpki"' -C metadata=4707029b872475d0 -C extra-filename=-4707029b872475d0 --out-dir /home/jona1993/Bureau/quinn/target/debug/deps -C incremental=/home/jona1993/Bureau/quinn/target/debug/incremental -L dependency=/home/jona1993/Bureau/quinn/target/debug/deps --extern bytes=/home/jona1993/Bureau/quinn/target/debug/deps/libbytes-132544d621c1e922.rmeta --extern futures=/home/jona1993/Bureau/quinn/target/debug/deps/libfutures-ec01a20cd1ba0e55.rmeta --extern libc=/home/jona1993/Bureau/quinn/target/debug/deps/liblibc-89279ce17dbf6aed.rmeta --extern mio=/home/jona1993/Bureau/quinn/target/debug/deps/libmio-7d4e29593d9fecb5.rmeta --extern proto=/home/jona1993/Bureau/quinn/target/debug/deps/libquinn_proto-c77971162d457871.rmeta --extern rustls=/home/jona1993/Bureau/quinn/target/debug/deps/librustls-f460949ff94ada3a.rmeta --extern thiserror=/home/jona1993/Bureau/quinn/target/debug/deps/libthiserror-18430524a81fdaa1.rmeta --extern tokio=/home/jona1993/Bureau/quinn/target/debug/deps/libtokio-96636c1167ea3c00.rmeta --extern tracing=/home/jona1993/Bureau/quinn/target/debug/deps/libtracing-976b01f8ec586a1d.rmeta --extern webpki=/home/jona1993/Bureau/quinn/target/debug/deps/libwebpki-b777aa3e3e5339a3.rmeta -L native=/home/jona1993/Bureau/quinn/target/debug/build/ring-6a6605d43da55d7d/out` (exit code: 1)

Have a nice day !

**Comment by djc** [comment]
What version of Rust are you using?

**Comment by jona-1993** [comment]
$ cargo --version

cargo 1.45.0 (744bd1fbb 2020-06-15)

**Comment by djc** [comment]
I think you'll need a later Rust for this, though I forget exactly what changed. In principle we don't support anything but the latest stable version.

**Comment by jona-1993** [comment]
Oh thank you, it works now.

I used this command before for update rust.

$ rustup update

It's better with the last version ;)

**Comment by kim** [comment]
FWIW, this also occurs on `nightly` from ~4months ago. Wondering if that’s a regression in the compiler, but unsure where to look.

**Comment by djc** [comment]
I changed this in f212256435754503ce248495b6b65ee6f2211f80 (from #844), I'm pretty sure this was in response to changes in Rust 1.46.0, but I can't find anything in the Rust release notes about what might have changed.

**Comment by kim** [comment]
I tried a few nightlies, and it looks like it works again after ~2020-10. Sorry
for the noise.
