### ISSUE TITLE
Allow user to retrieve RTT estimation

### ISSUE THREAD

**Issue by jean-airoldie** [quinn-rs/quinn#931]
From what I understand, by doing a quick grep search, quinn seem to be keeping track of the rtt latency for an active connection.

https://github.com/quinn-rs/quinn/blob/1ea0b897fa50abe97f02ae1b2b8b5c9c4ba24a30/quinn-proto/src/connection/paths.rs#L53

AFAIK this data is currently not publicly accessible, but I think it would make sense to allow the user to retrieve that information.

My specific use case is that I would like to keep track of the rtt latency per connection over time using a histogram. For this to be possible, I would need to both be able to retrieve the latency estimation, but also be notified when it is updated.

With that in mind, a possibility (although a bit complex), would be to allow the user to provide a type per connection that implements a trait such as the following:
```rust
pub trait RttUpdate {
  fn update_rtt(&self, rtt: Duration) {
    // Default impl is a noop.
  }
}
```
Where `RttUpdate::update_rtt` would be called each time the RTT is updated.

**Comment by djc** [comment]
Did you find the code added in #889?

**Comment by jean-airoldie** [comment]
Thx, I didn't see that.

This kinda works for my use case, however its not optimal because I can't know when the rtt was updated. For instance, if I parse the rtt at a constant interval (say every 10 seconds), I can't know whether the rtt was updated or not since the last interval, which would lead to data point duplication.

**Comment by jean-airoldie** [comment]
Looking at ralith's comment:
https://github.com/quinn-rs/quinn/pull/889#pullrequestreview-524708003
> LGTM. I wonder if we might eventually want to switch to exposing a single aggregate statistics structure to avoid churning the lock excessively, but that's an issue for another time.

I think it would be interesting to allow setting a consumer for the quinn connection statistics. IMO this would be way better than having to manually parse the values for each connection at a regular interval, and it would reduce contention for the lock.

Something like:
```rust
trait StatsConsumer {
  fn rrt_update(&self, rtt: Duration);
  fn bytes_recv_update(&self, nb_bytes: usize);
  fn bytes_sent_update(&self, nb_bytse: usze);
  // etc. (idk what statistics would be exposed)
}
```
And then a way to set the consumer for each connection (although setting the consumer before the connection is initiated would be better).
```rust
impl Connection {
  fn set_consumer(&self, consumer: Box<StatsConsumer>) {
    //...
  }
}
```

**Comment by Ralith** [comment]
> its not optimal because I can't know when the rtt was updated

The RTT is updated every single time an acknowledgement is received, which can be very frequent, almost certainly moreso than you actually want to sample it at.

>  I can't know whether the rtt was updated or not since the last interval, which would lead to data point duplication.

I don't follow. Sampling the RTT at regular intervals gives distinct data points; if they're the same value it's because the estimate is still the same, which is perfectly fine.

> I think it would be interesting to allow setting a consumer for the quinn connection statistics.

In my experience this type of callback-style interface is much more difficult to use than a simple accessor.

**Comment by jean-airoldie** [comment]
> I don't follow. Sampling the RTT at regular intervals gives distinct data points; if they're the same value it's because the estimate is still the same, which is perfectly fine. RTT is a continuous measurement.

I was under the impression that it wasn't frequently updated.

> In my experience this type of callback-style interface is much more difficult to use than a simple accessor.

They are. But in cases when your data is even driven you kinda have to.

Cool, so basically the RTT is very frequently updated, so just checking the value at a regular interval is almost guaranteed to have a up to date value, assuming that there was some activity on the connection. So for my use case that works fine. Thanks.

**Comment by jean-airoldie** [comment]
> The RTT is updated every single time an acknowledgement is received, which can be very frequent, almost certainly moreso than you actually want to sample it at.

Is this acknowledgement received with each packet? Or is there one per stream?

**Comment by Ralith** [comment]
The peer can send acknowledgements on whatever schedule it wishes, but a well-behaved peer will generally send one for every few packets received.

**Comment by StarStarJ** [comment]
Would it also be possible to get a copy of the whole `RttEstimator` object and add getters for the `latest` and `var` member variables or is that against the philosophy of this library?

I'd like to track the rtt jitter more accurately and the smoothed rtt isn't accurate at least in this scenario.

**Comment by djc** [comment]
@StarStarJ what is your use case/motivation? What problem are you trying to solve?

(Probably better to open a new issue about it rather than add to this old one.)
