### ISSUE TITLE
Does quinn already works with Chrome's QuicTransport?

### ISSUE THREAD

**Issue by endel** [quinn-rs/quinn#934]
The `QuicTransport` can be enabled on Chrome via `chrome://flags`. I'm wondering if quinn's implementation is already compatible with it? 

I've tried running the example `cargo run --example server ./` and connect to it via Chrome's `QuicTransport`, but this error showed up:

```
Failed to establish a connection to quic-transport://localhost:4433/: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_IETF_GQUIC_ERROR_MISSING (peer doesn't support any known protocol).
```

Thanks for your support!

**Comment by djc** [comment]
That sounds like Google QUIC (a predecessor of IETF QUIC). We only implement IETF QUIC, and have no intention of supporting GQUIC (since it should go away as soon as IETF QUIC is stabilized).

**Comment by Matthias247** [comment]
I think this could also be due to a missing ALPN. I think the WebTransport stuff might already run over IETF Quic

**Comment by endel** [comment]
@Matthias247 I'm actually looking forward for testing the WebTransport hands-on, information about it seems very scarce so far though. Do you know if WebTransport as it is today is usable with quinn somehow? Thanks!

**Comment by Ralith** [comment]
[The IETF draft](https://tools.ietf.org/id/draft-vvv-webtransport-quic-02.html#rfc.section.9.1) specifies an ALPN of wq-vvv-01. Try that?

**Comment by djc** [comment]
So is Chrome's QuicTransport the same thing as the proposed WebTransport standard?

**Comment by Ralith** [comment]
> [The WebTransport interface is based on the QuicTransport interface initially described in the W3C ORTC CG, and has been adapted for use in this specification.](https://w3c.github.io/webtransport/#acknowledgements)

**Comment by Ralith** [comment]
Closing as this was either an ALPN mismatch and/or a transient limitation on Chrome's side. Feel free to open a new issue if you're still having trouble talking to a current WebTransport implementation.
