### ISSUE TITLE
How to bind on custom socket backend?

### ISSUE THREAD

**Issue by badpooh** [quinn-rs/quinn#947]
I want to use raw socket on quinn, but quinn API only take `std::net::UdpSocket`, so I wonder how can I do that?

**Comment by badpooh** [comment]
Or how can I use custom socket than `std::net::UdpSocket`, it make more sense.

**Comment by djc** [comment]
What do you mean by "raw socket", exactly? Are you aware of the `FromRawFd` trait that's implemented for `std::net::UdpSocket`? (It might also be relevant what OS you're targeting.)

**Comment by badpooh** [comment]
I actually want to use protocol like icmp, which is raw socket to bypass the Great Firewall. `Socket2` crate did support raw socket, but I don't know how to pass it to `quinn`.

**Comment by Ralith** [comment]
QUIC is intrinsically defined in terms of UDP, so `quinn` does not support operating directly on top of IP using raw sockets. The requirement for elevated privileges and lack of support in NATs and firewalls makes them a bit niche. If you want to experiment with them anyway, you could make a fork, or build a prototype directly on top of `quinn-proto`.

**Comment by Matthias247** [comment]
There could be the idea is to use the OS raw socket APIs, but to still send UDP datagrams. Then the library would need to make sure it does the UDP things (which is mostly about writing the port number, and extracing/skipping it on receive). That should be doable by implementing a different socket backend. But I feel like the request here is rather a protocol modification?

**Comment by badpooh** [comment]
I'm moving from Go to Rust. Go have a `net.PacketConn` interface to represent udp socket and raw socket, then I can implement custom socket backend to do complex operations by implementing `net.PacketConn` interface. I think `std::net::UdpSocket` is lack of abstraction, maybe I should make a fork to build a more general socket backend interface on top of `quinn-proto`?

**Comment by Ralith** [comment]
`quinn-proto` is already agnostic to the underlying I/O mechanism, and could in theory be used to build a protocol that works directly on top of IP, although that protocol would not be QUIC.

**Comment by jamadazi** [comment]
Yes, I have also thought about possibly experimenting with trying to use quinn-proto over various non-UDP things (I wonder if WebRTC could work? it can send unreliable datagrams...), to get the features of QUIC in environments where I want/require a protocol that's not UDP.

Crazy stuff...
