### ISSUE TITLE
streams received_reset panics with large final offsets 

### ISSUE THREAD

**Issue by jafow** [quinn-rs/quinn#966]
Fuzzing against the `Streams` target raised this new panic, flagging here for discussion. 

### example output
```text
target/x86_64-unknown-linux-gnu/release/streams: Running 1 inputs 1 time(s) each.
Running: fuzz/artifacts/streams/minimized-from-06eda8ebc2230c5f8f7f12042c3d1c7684018c48
thread '<unnamed>' panicked at 'attempt to add with overflow', quinn-proto/src/connection/streams.rs:365:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

see attached tarball with a minimized example input to reproduce
[minimized-from-06eda8ebc2230c5f8f7f12042c3d1c7684018c48.tar.gz](https://github.com/quinn-rs/quinn/files/5762262/minimized-from-06eda8ebc2230c5f8f7f12042c3d1c7684018c48.tar.gz)

I expect this could be resolved by setting a limit in the fuzzing input, ie on the size of the `ResetStream` final offset and is a non-issue. Alternately there could be [another validation check added](https://github.com/quinn-rs/quinn/blob/main/quinn-proto/src/connection/streams.rs#L337) but that might be overkill

To run this 
1. install [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz#installation)
2. extract the example input attached
3. do `cargo fuzz run streams /path/to/the/minimized-case`

**Comment by Ralith** [comment]
This was actually a genuine bug; great find! Fix in the linked PR.
