### ISSUE TITLE
Consider supporting an older MSRV?

### ISSUE THREAD

**Issue by seanmonstar** [quinn-rs/quinn#979]
I brought this up on Discord, and djc suggested I open an issue. Would it be reasonable to support an older MSRV, perhaps similar to what Tokio itself supports (6 months old, currently supports 1.45)?

**Comment by djc** [comment]
Is there some documentation on what has driven the 6-month window on the Tokio side? It seems reasonable to me with the current rate of change in the language/std.

**Comment by seanmonstar** [comment]
I can't find anything more than just the proposal. I assume it's a guesstimate balance of "users may not be able to update rustc immediately" and "I want to use new features eventually".
