### ISSUE TITLE
Assembler::defragment causes high CPU load

### ISSUE THREAD

**Issue by Matthias247** [quinn-rs/quinn#981]
Here is a flamegraph of a benchmark I ran yesterday:

![image](https://user-images.githubusercontent.com/6330334/105130497-04641d00-5a9c-11eb-88a9-66837335c75c.png)

This one is a on loopback connection with simulated latency, which leads to rather high congestion windows (if flow control limits are also high).

In this case we can observe the receiving end of the connection drowning in `defragment` calls, which take up the majority of the CPU time.

I think there is a major contributing factor here:
[The assembler kicks in if at least 32 packets are queued](https://github.com/quinn-rs/quinn/blob/main/quinn-proto/src/connection/assembler.rs#L213-L215), which will likely always be the case in case a burst of packets is received. I think this can even happen in a less artificial scenario.

I think it might be worthwhile to rethink this strategy - especially for users which intend to receive lots of data.
One option I can imagine is to skip defragmentation of chunks which make up the majority of the MTU (e.g. > 75%). Now that's a bit tricky at this layer, because it isn't aware of the  MTU. But maybe just hardcoding it to 750 bytes might be good enough (at least as long as we don't imagine MTUs to be growing into jumbo-frame territory).

Another option is to immediately copy data of the datagram buffers into a more efficiently sized receive buffer datastructure. But that would be more interesting if the datagram wouldn't already be `Bytes` allocated earlier on and still be on the stack of the endpoint. This way it might just end up double-copying.

**Comment by djc** [comment]
The defragmentation heuristic kicking in is definitely pretty simplistic (and the number 32 is pretty arbitrary), so I think the right fix here is to tweak that. How about if we take the `payload.len()` in `Connection::process_payload()` and pass it down through `Streams::received()` and `Recv::ingest()` to `Assembler::insert()` (potentially storing it in the `Chunk`)? Assuming the header size is more or less constant, we can then make a decent estimate of wasted memory and trigger defragmentation on some threshold.

**Comment by Matthias247** [comment]
Sounds like a reasonable idea to me. Instead of the actual size just a fraction (0 - 100) could also be sufficient if one wants to save some data (but that might be lost due to alignment reasons anyway).

Most packets from nicely playing peers should be nearly full MTU sized. Therefore defragmentation should be rarely necessary. But I agree that it's good thing to have, in order to protect against bad peer behavior.

**Comment by djc** [comment]
Yes, this code is not there for capable/well-intentioned peers, but for the other kinds. 👍
