### ISSUE TITLE
Reading is prone to spurious driver wakeups

### ISSUE THREAD

**Issue by Ralith** [quinn-rs/quinn#984]
`quinn::RecvStream::poll_read_generic` currently wakes the connection driver on every successful operation in case we need to transmit flow control credit. As of #880 and #894 we no longer issue credit after every read, so we can reduce CPU load by only waking the connection driver if flow control actually does need to be issued.

**Comment by geieredgar** [comment]
Now that #992 has landed in main via #991, we could close this issue.

**Comment by djc** [comment]
Yup!
